---
galaxy_info:
  role_name: tc_launch
  namespace: susunola
  author: Tencent Cloud Ansible Collection Contributors (@susunola)
  description: Launch Tencent Cloud CVM instances with tags and security groups
  company: Tencent Cloud
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Generic
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - tencentcloud
    - cvm
    - cloud
    - instance
dependencies: []
