---
galaxy_info:
  author: Tencent Cloud Ansible Collection Contributors
  description: Provision TencentDB for SQL Server instances, backup strategy and accounts
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
dependencies: []
