---
tc_tse_api_gateway_state: present
tc_tse_api_gateway_gateway: {}
tc_tse_api_gateway_autoscaler_strategies: []
tc_tse_api_gateway_autoscaler_bindings: []
tc_tse_api_gateway_services: []
tc_tse_api_gateway_routes: []
tc_tse_api_gateway_canary_rules: []
tc_tse_api_gateway_consumers: []
tc_tse_api_gateway_consumer_groups: []
tc_tse_api_gateway_consumer_group_memberships: []
tc_tse_api_gateway_model_api_group_auths: []
tc_tse_api_gateway_secret_keys: []
tc_tse_api_gateway_model_services: []
tc_tse_api_gateway_model_apis: []
tc_tse_api_gateway_certificates: []
tc_tse_api_gateway_waf_domains: []
tc_tse_api_gateway_waf_protections: []
tc_tse_api_gateway_rate_limits: []
tc_tse_api_gateway_cors_policies: []
tc_tse_api_gateway_ip_restrictions: []
tc_tse_api_gateway_public_networks: []
tc_tse_api_gateway_allow_destroy: false
