---
tc_tsf_microservice_platform_state: present
tc_tsf_microservice_platform_clusters: []
tc_tsf_microservice_platform_repositories: []
tc_tsf_microservice_platform_namespaces: []
tc_tsf_microservice_platform_applications: []
tc_tsf_microservice_platform_application_configs: []
tc_tsf_microservice_platform_microservices: []
tc_tsf_microservice_platform_vm_deployment_groups: []
tc_tsf_microservice_platform_container_deployment_groups: []
tc_tsf_microservice_platform_lanes: []
tc_tsf_microservice_platform_lane_rules: []
tc_tsf_microservice_platform_allow_destroy: false
