# -*- coding: utf-8 -*-
# Copyright (c) 2026 Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT_PATH = REPO_ROOT / "scripts" / "check_doc_links.py"


def _load_script():
    spec = importlib.util.spec_from_file_location("check_doc_links", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def links_check():
    return _load_script()


@pytest.fixture
def tree(tmp_path, links_check):
    """Point the guard at a throwaway tree with one Markdown file."""
    saved = links_check.REPO_ROOT
    links_check.REPO_ROOT = str(tmp_path)
    (tmp_path / "docs").mkdir()
    yield tmp_path
    links_check.REPO_ROOT = saved


def write(tmp_path, name, body):
    path = tmp_path / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


# --------------------------------------------------------------------------
# the real repository
# --------------------------------------------------------------------------

def test_repository_links_resolve(links_check):
    broken, checked = links_check.check()
    assert broken == [], broken
    assert checked > 900


def test_main_check_exits_zero(links_check):
    assert links_check.main(["--check"]) == 0


# --------------------------------------------------------------------------
# what counts as broken
# --------------------------------------------------------------------------

def test_missing_target_is_reported(tree, links_check):
    """README.md pointed at CHANGELOG.rst, which the release workflow writes
    to changelogs/CHANGELOG.rst."""
    write(tree, "README.md", "See the [changelog](CHANGELOG.rst).\n")
    broken, checked = links_check.check()
    assert checked == 1
    assert broken == [("README.md", "CHANGELOG.rst")]


def test_existing_target_is_accepted(tree, links_check):
    write(tree, "changelogs/CHANGELOG.rst", "notes\n")
    write(tree, "README.md", "See the [changelog](changelogs/CHANGELOG.rst).\n")
    assert links_check.check() == ([], 1)


def test_link_is_resolved_against_its_own_file(tree, links_check):
    """A relative link in docs/ is relative to docs/, not to the root."""
    write(tree, "docs/guide.md", "See [the map](capability-map.html).\n")
    write(tree, "docs/capability-map.html", "<html></html>\n")
    assert links_check.check() == ([], 1)


def test_anchor_is_not_a_file(tree, links_check):
    """A heading anchor is generated by the renderer, so there is no file to
    resolve and the link is not counted."""
    write(tree, "README.md", "See [requirements](#requirements).\n")
    assert links_check.check() == ([], 0)


def test_fragment_is_stripped_from_a_file_link(tree, links_check):
    write(tree, "docs/capability-map.html", "<html></html>\n")
    write(tree, "README.md", "[map](docs/capability-map.html#products)\n")
    assert links_check.check() == ([], 1)


def test_external_link_is_left_alone(tree, links_check):
    write(tree, "README.md",
          "[spec](https://semver.org/) [mail](mailto:x@example.com) "
          "[site](/absolute/path)\n")
    assert links_check.check() == ([], 0)


def test_templated_target_is_left_alone(tree, links_check):
    write(tree, "README.md", "[doc]({{ docsite_url }}/index.html)\n")
    assert links_check.check() == ([], 0)


def test_fenced_code_block_is_skipped(tree, links_check):
    """An example may contain a link the reader is meant to adapt."""
    write(tree, "README.md", "```markdown\n[doc](not-a-real-file.md)\n```\n")
    assert links_check.check() == ([], 0)


def test_generated_build_output_is_skipped(tree, links_check):
    write(tree, "docs/docsite/build/html/index.md", "[x](missing.md)\n")
    assert links_check.check() == ([], 0)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def test_main_check_fails_and_names_the_file(tree, links_check, capsys):
    write(tree, "README.md", "[gone](docs/nowhere.md)\n")
    assert links_check.main(["--check"]) == 1
    assert "README.md -> docs/nowhere.md" in capsys.readouterr().err


def test_main_without_check_reports_the_count(tree, links_check, capsys):
    write(tree, "README.md", "[gone](docs/nowhere.md)\n")
    assert links_check.main([]) == 0
    assert "1 relative link(s) checked, 1 broken" in capsys.readouterr().out
