from __future__ import absolute_import, division, print_function

__metaclass__ = type

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT_PATH = REPO_ROOT / "scripts" / "check_module_tiers.py"


def _load_script():
    spec = importlib.util.spec_from_file_location("check_module_tiers", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def tiers():
    return _load_script()


@pytest.fixture
def fake_modules(tmp_path, tiers):
    """Point the script's MODULES_DIR at a throwaway directory."""
    old_dir = tiers.MODULES_DIR
    tiers.MODULES_DIR = tmp_path
    yield tmp_path
    tiers.MODULES_DIR = old_dir


def _write_module(fake_modules, name, generated=False):
    marker = (
        "# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.\n"
        if generated else ""
    )
    (fake_modules / (name + ".py")).write_text(
        marker + "DOCUMENTATION = '''\nmodule: %s\n'''\n" % name, encoding="utf-8"
    )


def test_classify_generated(tiers, fake_modules):
    _write_module(fake_modules, "example_info", generated=True)
    assert tiers.classify("example_info") == "generated"


def test_classify_core(tiers, fake_modules):
    _write_module(fake_modules, "vpc")
    assert tiers.classify("vpc") == "core"


def test_classify_unclassified(tiers, fake_modules):
    _write_module(fake_modules, "mystery_module")
    assert tiers.classify("mystery_module") == "unclassified"


def test_check_detects_unclassified(tiers, fake_modules):
    _write_module(fake_modules, "vpc")
    _write_module(fake_modules, "mystery_module")
    problems, result = tiers.check()
    assert result["core"] == ["vpc"]
    assert result["unclassified"] == ["mystery_module"]
    assert any("mystery_module" in problem and "CORE_MODULES" in problem
               for problem in problems)


def test_check_detects_generated_listed_as_core(tiers, fake_modules):
    _write_module(fake_modules, "vpc", generated=True)
    problems, result = tiers.check()
    assert any("must not also be listed in CORE_MODULES" in problem
               for problem in problems)
    assert result["generated"] == ["vpc"]


def test_check_clean(tiers, fake_modules):
    _write_module(fake_modules, "vpc")
    _write_module(fake_modules, "vpc_info")
    _write_module(fake_modules, "example_info", generated=True)
    problems, result = tiers.check()
    assert problems == []
    assert result["core"] == ["vpc", "vpc_info"]
    assert result["generated"] == ["example_info"]


def test_real_collection_classifies_everything(tiers):
    # Every module currently shipped must be classified; this is what CI
    # enforces, so a new module cannot land unclassified.
    problems, result = tiers.check()
    assert problems == []
    assert result["unclassified"] == []
    assert len(result["core"]) > 10
    assert len(result["generated"]) > 100
