---
galaxy_info:
  role_name: tc_serverless_application
  namespace: susunola
  author: Tencent Cloud Ansible Collection Contributors (@susunola)
  description: Deploy an SCF application with aliases, triggers and optional API Gateway exposure
  company: Tencent Cloud
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Generic
      versions: [all]
  galaxy_tags: [tencentcloud, scf, serverless, cloud]
dependencies: []
