---
galaxy_info:
  author: Tencent Cloud Ansible Collection Contributors
  description: Provision Auto Scaling groups with policies and scheduled actions.
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: GenericLinux
      versions: [all]
dependencies: []
