---
galaxy_info:
  role_name: tc_tem_application
  namespace: susunola
  author: Tencent Cloud Ansible Collection Contributors (@susunola)
  description: Provision and deploy a complete Tencent Cloud TEM application
  company: Tencent Cloud
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Generic
      versions: [all]
  galaxy_tags: [tencentcloud, tem, application, cloud]
dependencies: []
