#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Document what a module returns with the payload its own tests produce.

Why
---
976 of the 1,027 modules shipped a ``RETURN`` block with no ``sample``: the
keys are named, the shape is not shown. The samples that do exist were written
by hand, one at a time, because the obvious generator is worse than nothing --
deriving a sample from the SDK response model produced ``"string"`` and ``0``
for ``cvm_instance``, longer than the curated sample and saying less.

What this does
--------------
Runs the module unit tests with a recorder attached to the harness's
``exit_json``, keeps the payload each module actually produced, and writes that
payload under every documented return key that has no sample. The tests
already assert on those payloads, so a sample cannot invent a field the module
never returns: ``--check`` re-runs the capture and fails when a sample names a
key its module's tests never produced.

Two rules keep the result honest:

* **generated modules are skipped.** ``generate_info_modules.py`` owns those
  files and its ``--check`` would flag the edit, so a generated module keeps
  its unsampled ``RETURN`` until the generator learns to emit one.
* **only what the tests produced is written.** A documented key no test
  payload carries (a key that appears only on an error path, say) is left
  alone rather than filled with something plausible.

The capture is normalised the same way in both directions: ``None`` values and
the keys Ansible adds to every result are dropped, and a list sample shows its
first element, which is what a reader needs to see the shape.

Usage
-----
    python scripts/add_return_samples.py            # write the samples
    python scripts/add_return_samples.py --check    # CI: samples match tests
    python scripts/add_return_samples.py --print    # the census
"""

from __future__ import absolute_import, division, print_function

import argparse
import collections
import importlib
import json
import os
import re
import sys
from pathlib import Path

import pytest
import yaml

__metaclass__ = type

REPO_ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = REPO_ROOT / "plugins" / "modules"
TESTS_DIR = REPO_ROOT / "tests" / "unit" / "plugins" / "modules"


def _bootstrap_import_path():
    """Make ``tests.`` and ``ansible_collections.`` importable from here.

    The collection's own tests import each other as ``tests.unit....`` and the
    collection itself as ``ansible_collections.<namespace>.<name>``. pytest
    inserts the right parent for the first, but only for the files it collects
    by relative path, so this script sets both up itself and runs wherever the
    collection tree is checked out.
    """
    # ``tests`` is an implicit namespace package: the collection root is what
    # makes ``from tests.unit... import harness`` resolve.
    sys.path.insert(0, str(REPO_ROOT))
    parents = REPO_ROOT.parents
    if len(parents) > 2 and parents[1].name == "ansible_collections":
        sys.path.insert(0, str(parents[2]))


_bootstrap_import_path()

RETURN_RE = re.compile(r"RETURN\s*=\s*r?(['\"]{3})(?P<body>.*?)\1", re.S)

#: A file the generator owns: it rewrites RETURN wholesale, so a sample added
#: here would be flagged by ``generate_info_modules.py --check``.
GENERATED_RE = re.compile(r"^# Generated by scripts/generate_info_modules\.py",
                          re.M)

#: Keys Ansible itself adds to every module result; a sample showing
#: ``changed`` teaches a reader nothing about the module.
ANSIBLE_KEYS = frozenset((
    "changed", "failed", "invocation", "msg", "warnings", "deprecations",
    "diff", "skipped", "exception",
))

#: The capture must resolve this many modules, or it proved nothing: the first
#: version of this script compared a resolved path against an unresolved one
#: and captured zero modules, which a gate would have reported as "clean".
MIN_CAPTURED_MODULES = 400

#: pep8 fails a module line beyond 160 characters, and a payload may carry a
#: base64 blob or a one-line JSON document that cannot be wrapped. Such a key
#: keeps its description and gets no sample rather than a truncated one.
MAX_SAMPLE_LINE = 150

#: Every captured sample carries this comment, so ``--check`` can tell a
#: sample this script wrote (and must keep matching the tests) from one a
#: maintainer wrote by hand (which may document fields a unit test's fake
#: response does not carry). YAML drops comments, so the rendered docs are
#: unchanged.
SAMPLE_MARKER = ("# shape captured from this module's unit tests -- "
                 "scripts/add_return_samples.py")


#: Returned by :func:`prune` for a value a sample cannot show: a payload may
#: carry an object a test handed the module directly, and a real module
#: serialises those through the SDK, so the key is dropped rather than
#: documented as a Python repr (which would not be reproducible either).
_DROPPED = object()


def prune(value):
    """Keep the JSON-shaped part of *value*; drop ``None`` and Ansible's keys."""
    if isinstance(value, dict):
        pruned = {}
        for key, item in value.items():
            if item is None or key in ANSIBLE_KEYS:
                continue
            kept = prune(item)
            if kept is not _DROPPED:
                pruned[key] = kept
        return pruned
    if isinstance(value, list):
        return [kept for kept in (prune(item) for item in value)
                if kept is not _DROPPED]
    if isinstance(value, bool) or isinstance(value, (int, float, str)):
        return value
    return _DROPPED


def sample_of(value):
    """Return the sample a captured value becomes: first element, pruned.

    ``None`` means there is nothing to show: the value was an object the test
    built itself, or a list of nothing but those.
    """
    if isinstance(value, list):
        items = [kept for kept in (prune(item) for item in value)
                 if kept is not _DROPPED]
        return [items[0]] if items else None
    kept = prune(value)
    return None if kept is _DROPPED else kept


def keys_of(value):
    """Return the key structure of *value* (values become ``None``)."""
    if isinstance(value, dict):
        return {key: keys_of(item) for key, item in value.items()}
    if isinstance(value, list):
        return [keys_of(value[0])] if value else []
    return None


def is_subset(sample, captured):
    """True when every key in *sample* exists in *captured* with that shape."""
    if isinstance(sample, dict):
        return isinstance(captured, dict) and all(
            key in captured and is_subset(item, captured[key])
            for key, item in sample.items())
    if isinstance(sample, list):
        return isinstance(captured, list) and all(
            is_subset(item, other) for item in sample for other in captured)
    return True


def module_text(name):
    """Return the source of module *name*."""
    return (MODULES_DIR / ("%s.py" % name)).read_text(encoding="utf-8")


def return_body(name):
    """Return the RETURN block of module *name*, or ``None``."""
    match = RETURN_RE.search(module_text(name))
    return match.group("body") if match else None


def documented_entries(name):
    """Return the RETURN entries of module *name* keyed by return key."""
    body = return_body(name)
    if body is None:
        return {}
    try:
        parsed = yaml.safe_load(body)
    except yaml.YAMLError:
        return {}
    if not isinstance(parsed, dict):
        return {}
    return {key: value for key, value in parsed.items()
            if isinstance(value, dict)}


def unsampled_modules():
    """Return the modules whose RETURN has entries but no sample."""
    found = []
    for path in sorted(MODULES_DIR.glob("*.py")):
        text = path.read_text(encoding="utf-8")
        match = RETURN_RE.search(text)
        if not match or "sample:" in match.group("body"):
            continue
        found.append(path.stem)
    return found


def generated_modules():
    """Return the modules ``generate_info_modules.py`` owns."""
    return {path.stem for path in MODULES_DIR.glob("*.py")
            if GENERATED_RE.search(path.read_text(encoding="utf-8"))}


class PayloadRecorder(object):
    """A pytest plugin that records the ``exit_json`` payload of each module.

    Two hooks catch the two ways a test intercepts a result. The harness
    replaces ``harness._exit_json``, and ``TencentCloudModule.exit_json`` --
    the method the hand-written modules call -- is wrapped as well, because a
    test that patches ``AnsibleModule.exit_json`` itself (``cos_*_info`` and
    the other raw-``AnsibleModule`` modules do) would otherwise be invisible:
    the wrapper records and then calls whatever ``exit_json`` is in place,
    including the test's own.
    """

    def __init__(self, modules_dir):
        self.modules_dir = os.path.realpath(str(modules_dir))
        self.payloads = collections.defaultdict(list)
        self.current = None
        try:
            self.harness = importlib.import_module(
                "ansible_collections.susunola.tencentcloud.tests.unit."
                "plugins.modules.harness")
        except ImportError as exc:  # noqa: BLE001 - the message is the point
            raise SystemExit(
                "cannot import the collection's test harness (%s): run this "
                "from the collection root with PYTHONPATH set to the directory "
                "that contains ansible_collections" % exc)

    def module_files(self, item):
        """Return the module files the test *item* exercises."""
        found = set()
        module = getattr(item, "module", None)
        if module is None:
            return found
        for value in vars(module).values():
            path = getattr(value, "__file__", None)
            if not path:
                continue
            resolved = os.path.realpath(path)
            if os.path.dirname(resolved) == self.modules_dir:
                found.add(resolved)
        return found

    def pytest_runtest_setup(self, item):
        files = self.module_files(item)
        self.current = sorted(files)[0] if len(files) == 1 else None

    def record(self, payload):
        """Keep *payload* for the current module, ignoring a repeat."""
        if not self.current:
            return
        payload.setdefault("changed", False)
        kept = self.payloads[os.path.realpath(self.current)]
        if not kept or kept[-1] != payload:
            kept.append(payload)

    def install(self):
        recorder = self
        harness = self.harness

        def _exit_json(module, **kwargs):
            recorder.record(kwargs)
            raise harness.AnsibleExitJson(kwargs)

        harness._exit_json = _exit_json

        # ``TencentCloudModule.exit_json`` is what a hand-written module calls;
        # wrapping it sees the payload before any test-level patch of
        # ``AnsibleModule.exit_json`` replaces the method underneath.
        try:
            base = importlib.import_module(
                "ansible_collections.susunola.tencentcloud.plugins."
                "module_utils.base")
        except ImportError:
            return
        original = base.TencentCloudModule.exit_json

        def _tencent_exit_json(module, **kwargs):
            recorder.record(kwargs)
            return original(module, **kwargs)

        base.TencentCloudModule.exit_json = _tencent_exit_json


def capture(test_paths=None):
    """Run the module unit tests and return ``{module_name: [payload, ...]}``.

    A test run that does not pass is not a source of truth: a failing test, a
    collection error or an environment missing the SDK all leave modules
    without payloads, which would quietly turn into unverified samples.
    """
    recorder = PayloadRecorder(MODULES_DIR)
    recorder.install()
    targets = [str(path) for path in (test_paths or [TESTS_DIR])]
    rc = pytest.main(["-q", "-p", "no:randomly", "--no-header",
                      "-p", "no:cacheprovider"] + targets, plugins=[recorder])
    if rc != pytest.ExitCode.OK:
        raise SystemExit(
            "the module unit tests did not pass (pytest exit code %s): the "
            "payloads a RETURN sample is derived from cannot be trusted until "
            "they do" % int(rc))
    return {Path(path).stem: payloads
            for path, payloads in recorder.payloads.items()}


def choose_sample(payloads, key):
    """Return the sample for *key*: the largest one, chosen deterministically."""
    candidates = []
    for payload in payloads:
        if key not in payload:
            continue
        sample = sample_of(payload[key])
        candidates.append((len(json.dumps(sample, sort_keys=True, default=str)),
                           json.dumps(sample, sort_keys=True, default=str),
                           sample))
    if not candidates:
        return None
    return sorted(candidates)[-1][2]


class _IndentedDumper(yaml.SafeDumper):
    """A dumper that indents block sequences under their key.

    ``yaml.safe_dump`` writes a sequence at its parent's indentation
    (``key:`` then ``- item`` at the same column). That is valid YAML, but the
    samples in this repository indent the dash, and docs/panorama.html renders
    them, so the generated ones match.
    """

    def increase_indent(self, flow=False, indentless=False):
        return super(_IndentedDumper, self).increase_indent(flow, False)


def render_sample(sample):
    """Return the ``sample:`` block for *sample* as indented YAML lines.

    A dict or a list becomes a block; a scalar goes inline (``sample: false``)
    -- PyYAML ends a bare scalar document with ``...``, which is not something
    to put in a RETURN block.
    """
    if not isinstance(sample, (dict, list)):
        dumped = yaml.dump(sample, Dumper=_IndentedDumper,
                           default_flow_style=True, allow_unicode=True,
                           width=100)
        dumped = " ".join(line for line in dumped.split("\n")
                          if line.strip() and line.strip() != "...")
        return ["  sample: %s" % dumped.strip()]
    dumped = yaml.dump(sample, Dumper=_IndentedDumper, default_flow_style=False,
                       sort_keys=False, allow_unicode=True, width=100)
    lines = ["  sample:", "    %s" % SAMPLE_MARKER]
    for line in dumped.rstrip("\n").split("\n"):
        lines.append("    %s" % line if line else "")
    return lines


def insert_sample(text, key, sample):
    """Insert the ``sample:`` block for *key* into the RETURN block of *text*.

    A ``RETURN`` block is YAML at column zero: the return key starts the line
    and the entry's fields are indented under it, so the sample goes in after
    the last field of that entry.
    """
    match = RETURN_RE.search(text)
    if match is None:
        raise ValueError("no RETURN block")
    body = match.group("body")
    entry = re.search(r"^[\"']?%s[\"']?\s*:" % re.escape(key), body, re.M)
    if entry is None:
        raise ValueError("no RETURN entry for %r" % key)
    rest = body[entry.end():]
    end = re.search(r"^\S", rest, re.M)
    insert_at = entry.end() + (end.start() if end else len(rest))
    prefix, suffix = body[:insert_at], body[insert_at:]
    # A RETURN block may end on the last field's line (``... type: dict"""``),
    # so the insertion point is not always a line boundary.
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    new_body = prefix + "\n".join(render_sample(sample)) + "\n" + suffix
    return text[:match.start("body")] + new_body + text[match.end("body"):]


def write_samples(payloads, out=sys.stdout):
    """Write a sample into every unsampled documented entry the capture saw."""
    generated = generated_modules()
    written = skipped_generated = no_payload = no_value = 0
    failed = []
    too_long = []
    for name in unsampled_modules():
        if name in generated:
            skipped_generated += 1
            continue
        if name not in payloads:
            no_payload += 1
            continue
        text = module_text(name)
        entries = documented_entries(name)
        added = 0
        for key, entry in entries.items():
            if "sample" in entry:
                continue
            sample = choose_sample(payloads[name], key)
            if sample is None:
                no_value += 1
                continue
            if max(len(line) for line in render_sample(sample)) > MAX_SAMPLE_LINE:
                too_long.append("%s: %s" % (name, key))
                continue
            try:
                text = insert_sample(text, key, sample)
            except (ValueError, yaml.representer.RepresenterError) as exc:
                failed.append("%s: %s" % (name, exc))
                continue
            added += 1
        if added:
            (MODULES_DIR / ("%s.py" % name)).write_text(text, encoding="utf-8")
            written += 1
    print("%d module(s) gained a sample; %d generated module(s) skipped, "
          "%d without a captured payload, %d documented key(s) no payload "
          "carried" % (written, skipped_generated, no_payload, no_value),
          file=out)
    for failure in failed:
        print("  skipped: %s" % failure, file=out)
    if too_long:
        print("%d documented key(s) keep no sample: the payload does not fit a "
              "line under %d characters (%s)"
              % (len(too_long), MAX_SAMPLE_LINE, ", ".join(too_long)), file=out)
    return 1 if failed else 0


def marked_keys(name):
    """Return the RETURN keys of module *name* whose sample this script wrote."""
    body = return_body(name)
    if body is None:
        return set()
    marked = set()
    for key in documented_entries(name):
        entry = re.search(r"^[\"']?%s[\"']?\s*:" % re.escape(key), body, re.M)
        if entry is None:
            continue
        rest = body[entry.end():]
        end = re.search(r"^\S", rest, re.M)
        span = rest[:end.start() if end else len(rest)]
        if SAMPLE_MARKER in span:
            marked.add(key)
    return marked


def check_samples(payloads, out=sys.stdout, err=sys.stderr):
    """Fail when a captured sample stops matching the payloads its tests make.

    Only samples carrying :data:`SAMPLE_MARKER` are checked. A sample written
    by hand may legitimately document fields a unit test's fake response does
    not carry -- ``vpc`` describes the API's full response while its test
    stubs six fields -- so the two kinds are told apart by the marker rather
    than by guessing.
    """
    problems = []
    verified = 0
    for path in sorted(MODULES_DIR.glob("*.py")):
        name = path.stem
        if name not in payloads:
            continue
        entries = documented_entries(name)
        for key in sorted(marked_keys(name)):
            sample = entries.get(key, {}).get("sample")
            if sample is None:
                problems.append("%s: the marker on %r has no sample under it"
                                % (name, key))
                continue
            captured = [keys_of(sample_of(payload[key]))
                        for payload in payloads[name] if key in payload]
            if not captured:
                problems.append(
                    "%s: RETURN key %r has a captured sample but no test "
                    "payload carries that key" % (name, key))
                continue
            verified += 1
            if not any(keys_of(sample) == shape for shape in captured):
                problems.append(
                    "%s: the sample under %r no longer matches what the tests "
                    "produce (%s) -- re-run scripts/add_return_samples.py"
                    % (name, key, json.dumps(keys_of(sample), sort_keys=True,
                                             default=str)))
    if verified < MIN_CAPTURED_MODULES // 2:
        problems.append(
            "only %d captured sample(s) could be checked against a payload "
            "(expected at least %d): the capture did not run"
            % (verified, MIN_CAPTURED_MODULES // 2))
    print("checked %d sample(s) against the payloads their modules produced"
          % verified, file=out)
    for problem in problems:
        print("  %s" % problem, file=out)
    if problems:
        print("every RETURN sample must show keys the module's own tests "
              "produce; fix the sample or the module", file=err)
        return 1
    return 0


def main(argv=None, out=None, err=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify every sample against the captured payloads")
    parser.add_argument("--print", dest="show", action="store_true",
                        help="report the census without writing anything")
    parser.add_argument("--modules", metavar="NAMES",
                        help="limit the work to these modules (comma separated)")
    args = parser.parse_args(argv)
    out = out if out is not None else sys.stdout
    err = err if err is not None else sys.stderr

    selection = args.modules.split(",") if args.modules else None
    test_paths = sorted(TESTS_DIR.glob("test_*.py"))
    if selection:
        wanted = set()
        for name in selection:
            wanted.add("test_%s" % name)
            wanted.add("test_%s_main" % name)
        test_paths = [path for path in test_paths if path.stem in wanted]
    payloads = capture(test_paths)

    if args.show:
        print("captured payloads for %d module(s)" % len(payloads), file=out)
        print("modules with a RETURN but no sample: %d"
              % len(unsampled_modules()), file=out)
        return 0
    if args.check:
        return check_samples(payloads, out=out, err=err)
    if len(payloads) < MIN_CAPTURED_MODULES and not selection:
        print("the capture resolved only %d module(s); refusing to write "
              "samples from an incomplete run" % len(payloads), file=err)
        return 1
    return write_samples(payloads, out=out)


if __name__ == "__main__":
    sys.exit(main())
