# -*- coding: utf-8 -*-
"""Module tier governance check.

Every module in ``plugins/modules/`` must belong to exactly one tier; a
module that belongs to none (or to two) fails the check. The assignment is
rule-based so it cannot rot:

* **generated** -- the file carries the generator marker
  ``# Generated by scripts/generate_info_modules.py``. These ``_info``
  modules are produced from SPECS and must never be edited by hand.
* **core** -- hand-written modules listed in CORE_MODULES below. These are
  the quality anchor of the collection: idempotent write modules with check
  mode, diff output, contract tests and unit tests, plus the hand-written
  ``*_info`` modules that the generator cannot express.

A module that is neither generated nor listed is unclassified and fails the
check, so a new module cannot land without a deliberate tier decision.

Run with ``--check`` (used in CI) to exit 1 when any module is unclassified,
misassigned or stale; run without arguments to print the current tier table
for the README/docs.

See ``docs/module_tiers.md`` for the tier definitions and the acceptance
criteria of each tier.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = REPO_ROOT / "plugins" / "modules"

GENERATED_MARKER = "# Generated by scripts/generate_info_modules.py -- regenerate instead of editing."

# Hand-written modules (tier "core"). Keep this list complete: a hand-written
# module that is not listed here is reported as unclassified.
CORE_MODULES = {
    # Idempotent write modules with check mode and contract tests.
    "cam_policy",
    "cam_policy_attachment",
    "cam_group_membership",
    "cam_group",
    "cam_role",
    "cam_user",
    "api_gateway_service",
    "api_gateway_api",
    "api_gateway_api_key",
    "api_gateway_service_release",
    "api_gateway_usage_plan",
    "api_gateway_usage_plan_binding",
    "api_gateway_usage_plan_key_binding",
    "as_scaling_group",
    "as_scaling_policy",
    "as_scheduled_action",
    "cbs_disk",
    "cbs_snapshot",
    "cdb_instance",
    "cdb_parameter_template",
    "cdb_backup_config",
    "cdb_database",
    "cdb_account",
    "cdb_account_privilege",
    "cdb_audit_config",
    "ccn",
    "ccn_attachment",
    "cdn_domain",
    "clb_rule",
    "clb_target_group",
    "cls_logset",
    "cls_config",
    "cls_config_machine_group_binding",
    "cls_shipper",
    "cls_index",
    "cls_machine_group",
    "cls_topic",
    "cloudaudit_track",
    "ckafka_topic",
    "ckafka_user",
    "ckafka_route",
    "ckafka_acl_rule",
    "ckafka_acl",
    "clb_listener",
    "clb_listener_target",
    "clb_load_balancer",
    "cos_bucket",
    "cos_bucket_policy",
    "cos_bucket_replication",
    "config_rule",
    "cmq_queue",
    "cmq_topic",
    "cmq_subscription",
    "cfs_file_system",
    "cfw_address_template",
    "customer_gateway",
    "cvm_chc",
    "cvm_image",
    "cvm_instance",
    "cynosdb_account",
    "dnspod_record",
    "dnspod_domain",
    "dts_consumer_group",
    "dts_migration_job",
    "dbbrain_sql_filter",
    "eip",
    "elasticsearch_instance",
    "elasticsearch_index",
    "gaap_proxy",
    "key_pair",
    "kms_key",
    "kms_key_rotation",
    "lighthouse_instance",
    "mongodb_instance",
    "mongodb_backup_config",
    "mongodb_account",
    "mariadb_account",
    "mariadb_backup_config",
    "mariadb_account_privilege",
    "sqlserver_account",
    "monitor_alarm_policy",
    "monitor_alarm_policy_notice",
    "monitor_prometheus_scrape_job",
    "monitor_prometheus_record_rule",
    "monitor_prometheus_alert_group",
    "monitor_prometheus_instance",
    "monitor_prometheus_cluster_agent",
    "monitor_grafana_instance",
    "monitor_prometheus_grafana_binding",
    "monitor_grafana_integration",
    "monitor_grafana_whitelist",
    "monitor_grafana_internet",
    "monitor_grafana_notification_channel",
    "monitor_prometheus_global_notification",
    "monitor_prometheus_alertmanager_config",
    "nat_gateway",
    "nat_gateway_rule",
    "network_interface",
    "network_acl",
    "peering_connection",
    "organization_node",
    "organization_member",
    "organization_member_identity",
    "organization_member_policy",
    "private_dns_record",
    "private_dns_zone",
    "postgresql_account",
    "postgresql_parameter_template",
    "postgresql_backup_plan",
    "privatelink_endpoint_service",
    "privatelink_endpoint",
    "redis_instance",
    "redis_parameter_template",
    "redis_backup_config",
    "redis_account",
    "route_table",
    "scf_alias",
    "scf_function",
    "scf_trigger",
    "scf_version",
    "security_group",
    "security_group_rule",
    "ssl_certificate",
    "ssm_parameter",
    "subnet",
    "tag",
    "tat_command",
    "tdmq_topic",
    "tdmq_namespace",
    "tdmq_namespace_role",
    "tdmq_rabbitmq_vhost",
    "tdmq_rabbitmq_user",
    "tdmq_rabbitmq_permission",
    "tdmq_rabbitmq_binding",
    "tdmq_rocketmq_namespace",
    "tdmq_rocketmq_topic",
    "tdmq_rocketmq_group",
    "tdmq_rocketmq_role",
    "tdmq_rocketmq_permission",
    "tdmq_rocketmq_cluster",
    "tdmq_subscription",
    "teo_dns_record",
    "tcr_instance",
    "tcr_namespace",
    "tcr_repository",
    "tcr_replication_instance",
    "tcr_replication_rule",
    "tke_addon",
    "tke_cluster",
    "tke_cluster_endpoint",
    "tke_cluster_authentication",
    "tke_cluster_audit",
    "tke_backup_storage_location",
    "tke_node_pool",
    "vpc",
    "vpc_flow_log",
    "vpn_gateway",
    "waf_ip_access_control",
    "waf_protect_group",
    "waf_host",
    "waf_custom_rule",
    "vpn_connection",
    # Hand-written *_info modules that the generator cannot express.
    "cam_policy_info",
    "cam_role_info",
    "cam_user_info",
    "cos_bucket_info",
    "cvm_instance_info",
    "eip_info",
    "key_pair_info",
    "route_table_info",
    "security_group_info",
    "subnet_info",
    "vpc_info",
}


def discover_modules():
    """Return the names of every module in ``plugins/modules``."""
    return sorted(
        path.stem
        for path in MODULES_DIR.glob("*.py")
        if not path.name.startswith("__")
    )


def classify(module_name):
    """Return the tier of *module_name* (generated, core or unclassified)."""
    text = (MODULES_DIR / (module_name + ".py")).read_text(encoding="utf-8")
    if GENERATED_MARKER in text:
        return "generated"
    if module_name in CORE_MODULES:
        return "core"
    return "unclassified"


def check():
    """Return (problems, tiers) where tiers maps tier -> sorted modules."""
    problems = []
    tiers = {"core": [], "generated": [], "unclassified": []}
    for module_name in discover_modules():
        tier = classify(module_name)
        tiers[tier].append(module_name)
        if tier == "unclassified":
            problems.append(
                "%s is neither generated nor listed in CORE_MODULES; add it "
                "to one of the tiers in scripts/check_module_tiers.py"
                % module_name
            )
    generated_as_core = [name for name in tiers["generated"] if name in CORE_MODULES]
    if generated_as_core:
        problems.append(
            "generated modules must not also be listed in CORE_MODULES: %s"
            % ", ".join(sorted(generated_as_core))
        )
    return problems, tiers


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="do not print the tier table; fail on any inconsistency",
    )
    args = parser.parse_args(argv)

    problems, tiers = check()
    if args.check:
        if problems:
            print("module tier problems:", file=sys.stderr)
            for problem in problems:
                print("  - %s" % problem, file=sys.stderr)
            return 1
        print("module tiers: %d core, %d generated"
              % (len(tiers["core"]), len(tiers["generated"])))
        return 0

    for tier in ("core", "generated", "unclassified"):
        print("%s (%d):" % (tier, len(tiers[tier])))
        for name in tiers[tier]:
            print("  %s" % name)
    if problems:
        print("problems:", file=sys.stderr)
        for problem in problems:
            print("  - %s" % problem, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
