#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""Ratchet for the P0 remediation freeze.

Counts must not rise. 2.0 target ceilings live in docs/core-allowlist.yml
and are checked with --strict (allowlist membership) once P1 starts deleting
modules. Default mode is freeze-only so this guard can land before the cut.
"""
from __future__ import absolute_import, division, print_function

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST = ROOT / "docs" / "core-allowlist.yml"
GENERATOR_BANNER = "Generated by scripts/generate_info_modules.py"

# P0 freeze ceilings captured from main at the freeze commit. Only lower them.
FREEZE = {
    "modules": 1027,
    "generated_modules": 502,
    "roles": 68,
    "extra_plugins": 16,
    "ignore_entries": 144,
    "readme_lines": 1370,
}

PLUGIN_DIRS = (
    "plugins/action",
    "plugins/callback",
    "plugins/connection",
    "plugins/event_source",
    "plugins/inventory",
    "plugins/lookup",
)


def _py_stems(directory):
    path = ROOT / directory
    if not path.is_dir():
        return []
    return sorted(p.stem for p in path.glob("*.py") if p.name != "__init__.py")


def _count_ignore_entries():
    total = 0
    sanity = ROOT / "tests" / "sanity"
    if not sanity.is_dir():
        return 0
    for path in sorted(sanity.glob("ignore-*.txt")):
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                total += 1
    return total


def measure():
    modules_dir = ROOT / "plugins" / "modules"
    modules = list(modules_dir.glob("*.py"))
    generated = 0
    for path in modules:
        head = path.read_text(encoding="utf-8", errors="replace")[:600]
        if GENERATOR_BANNER in head:
            generated += 1
    roles_dir = ROOT / "roles"
    roles = [p.name for p in roles_dir.iterdir() if p.is_dir()] if roles_dir.is_dir() else []
    extra_plugins = []
    for directory in PLUGIN_DIRS:
        extra_plugins.extend("%s/%s" % (directory, name) for name in _py_stems(directory))
    readme = ROOT / "README.md"
    readme_lines = len(readme.read_text(encoding="utf-8").splitlines()) if readme.exists() else 0
    return {
        "modules": len(modules),
        "generated_modules": generated,
        "roles": len(roles),
        "extra_plugins": len(extra_plugins),
        "ignore_entries": _count_ignore_entries(),
        "readme_lines": readme_lines,
        "module_names": sorted(p.stem for p in modules),
        "role_names": sorted(roles),
        "plugin_names": extra_plugins,
    }


def load_allowlist():
    if yaml is None:
        print("FAIL: PyYAML is required to read docs/core-allowlist.yml", file=sys.stderr)
        sys.exit(2)
    data = yaml.safe_load(ALLOWLIST.read_text(encoding="utf-8"))
    modules = list(data.get("modules") or [])
    if len(modules) != len(set(modules)):
        print("FAIL: docs/core-allowlist.yml has duplicate module names", file=sys.stderr)
        sys.exit(1)
    if len(modules) > int(data.get("max_modules", 120)):
        print(
            "FAIL: allowlist has %d modules, max_modules is %d"
            % (len(modules), data["max_modules"]),
            file=sys.stderr,
        )
        sys.exit(1)
    return data


def check_freeze(stats):
    failed = False
    for key, ceiling in FREEZE.items():
        value = stats[key]
        if value > ceiling:
            print(
                "FAIL: %s is %d, freeze ceiling is %d (counts must not rise)"
                % (key, value, ceiling),
                file=sys.stderr,
            )
            failed = True
        else:
            print("ok: %s %d <= freeze %d" % (key, value, ceiling))
    return failed


def check_strict(stats, allowlist):
    failed = False
    allowed = set(allowlist["modules"])
    present = set(stats["module_names"])
    extra = sorted(present - allowed)
    if extra:
        print(
            "FAIL: --strict: %d modules are not on the 2.0 allowlist (showing up to 30):"
            % len(extra),
            file=sys.stderr,
        )
        for name in extra[:30]:
            print("  %s" % name, file=sys.stderr)
        failed = True
    if stats["generated_modules"] > int(allowlist.get("max_generated_modules", 0)):
        print(
            "FAIL: --strict: generated modules %d exceed max_generated_modules %s"
            % (stats["generated_modules"], allowlist.get("max_generated_modules", 0)),
            file=sys.stderr,
        )
        failed = True
    allowed_roles = set(allowlist.get("roles") or [])
    extra_roles = sorted(set(stats["role_names"]) - allowed_roles)
    if extra_roles and stats["roles"] > int(allowlist.get("max_roles", 3)):
        print(
            "FAIL: --strict: roles not on the 2.0 allowlist: %s" % ", ".join(extra_roles),
            file=sys.stderr,
        )
        failed = True
    return failed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--print", action="store_true", dest="do_print")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="also require every shipped module/role to be on the 2.0 allowlist",
    )
    args = parser.parse_args(argv)
    stats = measure()
    if args.do_print:
        for key in FREEZE:
            print("%s %d (freeze %d)" % (key, stats[key], FREEZE[key]))
        print("allowlist_target_modules %d" % len(load_allowlist()["modules"]))
        return 0
    failed = check_freeze(stats)
    if args.strict:
        failed = check_strict(stats, load_allowlist()) or failed
    else:
        allowlist = load_allowlist()
        print(
            "note: 2.0 allowlist is %d modules / %d roles; --strict not enabled"
            % (len(allowlist["modules"]), len(allowlist.get("roles") or []))
        )
    if failed:
        return 1
    print("ok: remediation freeze holds")
    return 0


if __name__ == "__main__":
    sys.exit(main())
