#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Check that every relative link in the repository's prose resolves.

Why
---
The README is the first page of the collection, and ``docs/`` is what a
reviewer reads. Both are full of relative links, and a relative link is the
one thing a Markdown renderer cannot tell you about: GitHub answers a link to
a file that is not there with a 404, and nothing in the repository noticed.
The README pointed at ``CHANGELOG.rst``, which lives in ``changelogs/``, for
as long as the release workflow has been writing it there.

What it checks
--------------
Every ``[text](target)`` in the Markdown files this repository ships, where
*target* is relative -- absolute URLs, ``mailto:`` links and site-absolute
paths are left alone -- is resolved against the file that contains it.

Deliberately skipped:

* fenced code blocks, because an example may legitimately contain a link the
  reader is meant to adapt rather than follow;
* the ``#fragment`` part of a link, because heading anchors are generated by
  the renderer and are not files;
* the docsite build output, which is generated.

Usage
-----
    python scripts/check_doc_links.py            # list every link and its state
    python scripts/check_doc_links.py --check    # exit 1 on a broken link
"""

from __future__ import absolute_import, division, print_function

import argparse
import os
import re
import sys

__metaclass__ = type

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: Files that are part of what a reader sees, as repository-relative globs.
SOURCES = ("README.md", "docs", "roles", "tests", "changelogs")

#: Directories under a source that hold generated output rather than prose.
SKIP_DIRS = ("build", "output", "__pycache__")

LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
FENCE_RE = re.compile(r"^```.*?^```", re.S | re.M)


def markdown_files():
    """Return every Markdown file a reader is meant to read, sorted."""
    found = []
    for source in SOURCES:
        path = os.path.join(REPO_ROOT, source)
        if os.path.isfile(path):
            found.append(path)
            continue
        for root, dirs, names in os.walk(path):
            dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
            for name in sorted(names):
                if name.endswith(".md"):
                    found.append(os.path.join(root, name))
    return sorted(set(found))


def _is_external(target):
    return (target.startswith(("http://", "https://", "mailto:", "/", "#"))
            or "{{" in target or "{%" in target)


def links(path):
    """Yield every relative link target in one file."""
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    # Remove fenced blocks before scanning so an example's link is not
    # reported as a broken file.
    text = FENCE_RE.sub("", text)
    for match in LINK_RE.finditer(text):
        target = match.group(1)
        if not _is_external(target):
            yield target


def check():
    """Return ([(path, target)], checked_count) for every broken link."""
    broken = []
    checked = 0
    for path in markdown_files():
        for target in links(path):
            checked += 1
            resolved = os.path.normpath(
                os.path.join(os.path.dirname(path), target.split("#")[0]))
            if not os.path.exists(resolved):
                broken.append((os.path.relpath(path, REPO_ROOT), target))
    return broken, checked


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when a relative link does not resolve")
    args = parser.parse_args(argv)

    broken, checked = check()
    if broken:
        print("broken relative link(s):", file=sys.stderr)
        for path, target in broken:
            print("  - %s -> %s" % (path, target), file=sys.stderr)
        if args.check:
            return 1
    if args.check:
        print("doc links: %d relative link(s) in %d file(s) resolve"
              % (checked, len(markdown_files())))
        return 0
    print("doc links: %d relative link(s) checked, %d broken"
          % (checked, len(broken)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
