# -*- coding: utf-8 -*-
"""Generate read-only ``*_info`` modules for Tencent Cloud services.

Every generated module mirrors ``plugins/modules/subnet_info.py``: a
``build_request`` helper plus a ``run_module`` that pages through the
service's describe/list API with ``module_utils.paging.Paginator``.

The generator is re-runnable: rewriting a module with identical content
leaves the file untouched. Run with ``--check`` to verify the generated
modules are up to date (used in CI).

Field names, request/response shapes and pagination types in SPECS were
verified by introspecting the ``tencentcloud-sdk-python-<service>``
packages; do not edit them by guesswork.

Auto-discovered specs live in ``scripts/info_specs_auto.py`` (written by
``scripts/discover_info_specs.py``) and are appended to SPECS at import
time; curated SPECS stay untouched and their output remains byte-identical.

For every spec that fits the simple offset/limit or page-number shape the
generator also emits a unit test file (``tests/unit/plugins/modules/
test_<module>.py``); test files without the generated marker are considered
hand-finished and are never rewritten.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = REPO_ROOT / "plugins" / "modules"
TESTS_DIR = REPO_ROOT / "tests" / "unit" / "plugins" / "modules"
MARKER = "# Generated by scripts/generate_info_modules.py -- regenerate instead of editing."

VERSION_ADDED = "0.6.0"
# Modules generated before the 0.6.0 batch keep their original version_added.
LEGACY_VERSION_ADDED = "0.4.0"
AUTHOR = "Tencent Cloud Ansible Collection Contributors (@susunola)"
DOC_FRAGMENT = "tencentcloud.cloud.tencentcloud"

# Hand-curated per-module specification. All SDK field names were verified
# against the installed tencentcloud-sdk-python-<service> packages.
#
# Keys:
#   module           Ansible module name (file plugins/modules/<module>.py)
#   version_added    optional; defaults to VERSION_ADDED (legacy modules pin
#                    LEGACY_VERSION_ADDED so their output stays unchanged)
#   service_package  SDK package, e.g. tencentcloud.clb.v20180317
#   client_module    module holding the client class, e.g. clb_client
#   client_class     SDK client class name
#   sdk_package      pip package named in the ImportError message
#   endpoint         default API endpoint
#   action / request_class / response_items / response_total
#                    describe/list action and its request class, response
#                    list field and total-count field (dotted when nested)
#   ids              optional dict(param=..., field=..., doc=...) for the
#                    <resource>_ids option; None when the API cannot filter
#                    by ID (dnspod) or uses a dedicated describe action (kms)
#   ids_action       optional dedicated describe-by-ids action used when the
#                    ids option is given (kms: DescribeKeys)
#   filters          optional dict(doc=...) enabling the filters option
#                    (API must expose a Filters list of Filter{Name,Values});
#                    optional keys: model (default "Filter"), name_field
#                    (default "Name"), value_field (default "Values", cdn's
#                    DomainFilter uses Value) and name_wrap (wrap the name in
#                    a list, for cynosdb's QueryFilter{Names,Values})
#   extra_params     list of extra options, e.g. dnspod's required domain;
#                    optional params are only set on the request when given,
#                    params with "required" or "default" are always set
#   result_key       Ansible return key for the resource list
#   page_size_default  optional page_size default (cloudaudit's MaxResults
#                    caps at 50)
#   pagination_type  "int" (Offset/Limit ints, most services), "page"
#                    (PageNumber/PageSize, monitor), "token" (NextToken/
#                    MaxResults, cloudaudit), "list" (unpaginated single
#                    call returning an items list) or "none" (unpaginated
#                    single call returning one object, billing); verified
#                    via docstrings
#   page_number_field / page_size_field
#                    optional overrides for the pagination field names
#                    ("page": PageNo/PageSize for gme, Page/Limit for lcic;
#                    "int": Length instead of Limit for iot; "token": Limit
#                    instead of MaxResults for ams). page_size_field may be
#                    None for token specs without a page-size field (chdfs)
#   token_request_field / token_response_field
#                    optional overrides for the token continuation fields
#                    (default NextToken/NextToken; ams uses PageToken, chdfs
#                    FileSystemMarker-style names, faceid Cursor/NextCursor)
#   list_over_field  token mode: bool response field that ends pagination
#                    when true (default ListOver; None to disable)
#   has_more_field   token mode: bool response field that ends pagination
#                    when false (default None; faceid uses HasNextPage)
#   response_total   may be None for int/page/token specs whose response
#                    carries no total-count field; pagination then stops at
#                    the first short page and total_count falls back to the
#                    number of items returned
SPECS = [
    {
        "module": "clb_load_balancer_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.clb.v20180317",
        "client_module": "clb_client",
        "client_class": "ClbClient",
        "sdk_package": "tencentcloud-sdk-python-clb",
        "endpoint": "clb.tencentcloudapi.com",
        "action": "DescribeLoadBalancers",
        "request_class": "DescribeLoadBalancersRequest",
        "ids": {
            "param": "load_balancer_ids",
            "field": "LoadBalancerIds",
            "doc": "Load balancer IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "CLB API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "LoadBalancerSet",
        "response_total": "TotalCount",
        "result_key": "load_balancers",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CLB load balancers",
        "description": "Returns CLB (Cloud Load Balancer) instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CLB load balancers.",
        "return_total_doc": "Number of load balancers reported by the API.",
        "examples": """\
- name: List all CLB load balancers
  tencentcloud.cloud.clb_load_balancer_info:
    region: ap-guangzhou

- name: Find load balancers by ID
  tencentcloud.cloud.clb_load_balancer_info:
    region: ap-guangzhou
    load_balancer_ids: [lb-xxxxxxxx]
""",
    },
    {
        "module": "cdb_instance_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.cdb.v20170320",
        "client_module": "cdb_client",
        "client_class": "CdbClient",
        "sdk_package": "tencentcloud-sdk-python-cdb",
        "endpoint": "cdb.tencentcloudapi.com",
        "action": "DescribeDBInstances",
        "request_class": "DescribeDBInstancesRequest",
        "ids": {
            "param": "instance_ids",
            "field": "InstanceIds",
            "doc": "Instance IDs to return.",
        },
        "filters": None,  # DescribeDBInstances has no Filters field.
        "extra_params": [],
        "response_items": "Items",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for MySQL instances",
        "description": "Returns TencentDB for MySQL (CDB) instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TencentDB for MySQL instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all TencentDB for MySQL instances
  tencentcloud.cloud.cdb_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.cdb_instance_info:
    region: ap-guangzhou
    instance_ids: [cdb-xxxxxxxx]
""",
    },
    {
        "module": "tke_cluster_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.tke.v20180525",
        "client_module": "tke_client",
        "client_class": "TkeClient",
        "sdk_package": "tencentcloud-sdk-python-tke",
        "endpoint": "tke.tencentcloudapi.com",
        "action": "DescribeClusters",
        "request_class": "DescribeClustersRequest",
        "ids": {
            "param": "cluster_ids",
            "field": "ClusterIds",
            "doc": "Cluster IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "TKE API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "Clusters",
        "response_total": "TotalCount",
        "result_key": "clusters",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud TKE clusters",
        "description": "Returns TKE (Tencent Kubernetes Engine) clusters visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TKE clusters.",
        "return_total_doc": "Number of clusters reported by the API.",
        "examples": """\
- name: List all TKE clusters
  tencentcloud.cloud.tke_cluster_info:
    region: ap-guangzhou

- name: Find clusters by ID
  tencentcloud.cloud.tke_cluster_info:
    region: ap-guangzhou
    cluster_ids: [cls-xxxxxxxx]
""",
    },
    {
        "module": "cbs_disk_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.cbs.v20170312",
        "client_module": "cbs_client",
        "client_class": "CbsClient",
        "sdk_package": "tencentcloud-sdk-python-cbs",
        "endpoint": "cbs.tencentcloudapi.com",
        "action": "DescribeDisks",
        "request_class": "DescribeDisksRequest",
        "ids": {
            "param": "disk_ids",
            "field": "DiskIds",
            "doc": "Cloud disk IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "CBS API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "DiskSet",
        "response_total": "TotalCount",
        "result_key": "disks",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CBS disks",
        "description": "Returns CBS (Cloud Block Storage) disks visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CBS disks.",
        "return_total_doc": "Number of disks reported by the API.",
        "examples": """\
- name: List all CBS disks
  tencentcloud.cloud.cbs_disk_info:
    region: ap-guangzhou
  register: disks

- name: Find disks by ID
  tencentcloud.cloud.cbs_disk_info:
    region: ap-guangzhou
    disk_ids: [disk-xxxxxxxx]
""",
    },
    {
        "module": "redis_instance_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.redis.v20180412",
        "client_module": "redis_client",
        "client_class": "RedisClient",
        "sdk_package": "tencentcloud-sdk-python-redis",
        "endpoint": "redis.tencentcloudapi.com",
        "action": "DescribeInstances",
        "request_class": "DescribeInstancesRequest",
        "ids": {
            "param": "instance_ids",
            "field": "InstanceIds",
            "doc": "Instance IDs to return.",
        },
        "filters": None,  # DescribeInstances has no Filters field.
        "extra_params": [],
        "response_items": "InstanceSet",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for Redis instances",
        "description": "Returns TencentDB for Redis instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TencentDB for Redis instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all TencentDB for Redis instances
  tencentcloud.cloud.redis_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.redis_instance_info:
    region: ap-guangzhou
    instance_ids: [crs-xxxxxxxx]
""",
    },
    {
        "module": "mongodb_instance_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.mongodb.v20190725",
        "client_module": "mongodb_client",
        "client_class": "MongodbClient",
        "sdk_package": "tencentcloud-sdk-python-mongodb",
        "endpoint": "mongodb.tencentcloudapi.com",
        "action": "DescribeDBInstances",
        "request_class": "DescribeDBInstancesRequest",
        "ids": {
            "param": "instance_ids",
            "field": "InstanceIds",
            "doc": "Instance IDs to return.",
        },
        "filters": None,  # DescribeDBInstances has no Filters field.
        "extra_params": [],
        "response_items": "InstanceDetails",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for MongoDB instances",
        "description": "Returns TencentDB for MongoDB instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TencentDB for MongoDB instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all TencentDB for MongoDB instances
  tencentcloud.cloud.mongodb_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.mongodb_instance_info:
    region: ap-guangzhou
    instance_ids: [cmgo-xxxxxxxx]
""",
    },
    {
        "module": "kms_key_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.kms.v20190118",
        "client_module": "kms_client",
        "client_class": "KmsClient",
        "sdk_package": "tencentcloud-sdk-python-kms",
        "endpoint": "kms.tencentcloudapi.com",
        # ListKeysRequest only has Offset/Limit/Role/HsmClusterId; key IDs
        # are described through the dedicated DescribeKeys action instead.
        "action": "ListKeys",
        "request_class": "ListKeysRequest",
        "ids": {
            "param": "key_ids",
            "field": "KeyIds",
            "doc": "Key IDs to describe. When given, the keys are returned directly without pagination.",
            # Key IDs are not secret; silences validate-modules no-log-needed.
            "no_log": False,
        },
        "ids_action": {
            "action": "DescribeKeys",
            "request_class": "DescribeKeysRequest",
            "response_items": "KeyMetadatas",
        },
        "filters": None,
        "extra_params": [],
        "response_items": "Keys",
        "response_total": "TotalCount",
        "result_key": "kms_keys",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud KMS keys",
        "description": "Returns KMS keys visible in a Tencent Cloud region.",
        "return_items_doc": "Matching KMS keys.",
        "return_total_doc": "Number of keys reported by the API, or the number of requested keys.",
        "examples": """\
- name: List all KMS keys
  tencentcloud.cloud.kms_key_info:
    region: ap-guangzhou

- name: Describe specific KMS keys
  tencentcloud.cloud.kms_key_info:
    region: ap-guangzhou
    key_ids: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx]
""",
    },
    {
        "module": "dnspod_record_info",
        "version_added": LEGACY_VERSION_ADDED,
        "service_package": "tencentcloud.dnspod.v20210323",
        "client_module": "dnspod_client",
        "client_class": "DnspodClient",
        "sdk_package": "tencentcloud-sdk-python-dnspod",
        "endpoint": "dnspod.tencentcloudapi.com",
        "action": "DescribeRecordList",
        "request_class": "DescribeRecordListRequest",
        "ids": None,  # DescribeRecordList cannot filter by record ID.
        "filters": None,
        "extra_params": [
            {
                "name": "domain",
                "field": "Domain",
                "type": "str",
                "required": True,
                "doc": "Domain name whose DNS records are returned.",
            },
        ],
        "response_items": "RecordList",
        "response_total": "RecordCountInfo.TotalCount",
        "result_key": "records",
        "pagination_type": "int",
        "short_description": "Gather information about DNSPod records",
        "description": "Returns the DNS records of a DNSPod domain.",
        "return_items_doc": "Matching DNS records.",
        "return_total_doc": "Total number of records of the domain reported by the API.",
        "examples": """\
- name: List DNS records for a domain
  tencentcloud.cloud.dnspod_record_info:
    region: ap-guangzhou
    domain: example.com
""",
    },
    {
        "module": "as_scaling_group_info",
        # The SDK product dir is "autoscaling" ("as" is a Python keyword).
        "service_package": "tencentcloud.autoscaling.v20180419",
        "client_module": "autoscaling_client",
        "client_class": "AutoscalingClient",
        "sdk_package": "tencentcloud-sdk-python-autoscaling",
        "endpoint": "as.tencentcloudapi.com",
        "action": "DescribeAutoScalingGroups",
        "request_class": "DescribeAutoScalingGroupsRequest",
        "ids": {
            "param": "auto_scaling_group_ids",
            "field": "AutoScalingGroupIds",
            "doc": "Auto scaling group IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "Auto Scaling API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "AutoScalingGroupSet",
        "response_total": "TotalCount",
        "result_key": "scaling_groups",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud auto scaling groups",
        "description": "Returns auto scaling groups visible in a Tencent Cloud region.",
        "return_items_doc": "Matching auto scaling groups.",
        "return_total_doc": "Number of auto scaling groups reported by the API.",
        "examples": """\
- name: List all auto scaling groups
  tencentcloud.cloud.as_scaling_group_info:
    region: ap-guangzhou

- name: Find auto scaling groups by ID
  tencentcloud.cloud.as_scaling_group_info:
    region: ap-guangzhou
    auto_scaling_group_ids: [asg-xxxxxxxx]
""",
    },
    {
        "module": "scf_function_info",
        "service_package": "tencentcloud.scf.v20180416",
        "client_module": "scf_client",
        "client_class": "ScfClient",
        "sdk_package": "tencentcloud-sdk-python-scf",
        "endpoint": "scf.tencentcloudapi.com",
        "action": "ListFunctions",
        "request_class": "ListFunctionsRequest",
        "ids": None,  # ListFunctions cannot filter by function name/ID directly.
        "filters": {"doc": "SCF API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "Functions",
        "response_total": "TotalCount",
        "result_key": "functions",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud SCF functions",
        "description": "Returns SCF (Serverless Cloud Function) functions visible in a Tencent Cloud region.",
        "return_items_doc": "Matching SCF functions.",
        "return_total_doc": "Number of functions reported by the API.",
        "examples": """\
- name: List all SCF functions
  tencentcloud.cloud.scf_function_info:
    region: ap-guangzhou
""",
    },
    {
        "module": "cfs_file_system_info",
        "service_package": "tencentcloud.cfs.v20190719",
        "client_module": "cfs_client",
        "client_class": "CfsClient",
        "sdk_package": "tencentcloud-sdk-python-cfs",
        "endpoint": "cfs.tencentcloudapi.com",
        "action": "DescribeCfsFileSystems",
        "request_class": "DescribeCfsFileSystemsRequest",
        "ids": None,  # The API takes a single FileSystemId string, not a list.
        "filters": None,  # DescribeCfsFileSystems has no Filters field.
        "extra_params": [
            {
                "name": "file_system_id",
                "field": "FileSystemId",
                "type": "str",
                "doc": "Return only the file system with this ID.",
            },
        ],
        "response_items": "FileSystems",
        "response_total": "TotalCount",
        "result_key": "file_systems",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CFS file systems",
        "description": "Returns CFS (Cloud File Storage) file systems visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CFS file systems.",
        "return_total_doc": "Number of file systems reported by the API.",
        "examples": """\
- name: List all CFS file systems
  tencentcloud.cloud.cfs_file_system_info:
    region: ap-guangzhou

- name: Describe a single file system
  tencentcloud.cloud.cfs_file_system_info:
    region: ap-guangzhou
    file_system_id: cfs-xxxxxxxx
""",
    },
    {
        "module": "lighthouse_instance_info",
        "service_package": "tencentcloud.lighthouse.v20200324",
        "client_module": "lighthouse_client",
        "client_class": "LighthouseClient",
        "sdk_package": "tencentcloud-sdk-python-lighthouse",
        "endpoint": "lighthouse.tencentcloudapi.com",
        "action": "DescribeInstances",
        "request_class": "DescribeInstancesRequest",
        "ids": {
            "param": "instance_ids",
            "field": "InstanceIds",
            "doc": "Instance IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "Lighthouse API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "InstanceSet",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud Lighthouse instances",
        "description": "Returns Lighthouse instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching Lighthouse instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all Lighthouse instances
  tencentcloud.cloud.lighthouse_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.lighthouse_instance_info:
    region: ap-guangzhou
    instance_ids: [lhins-xxxxxxxx]
""",
    },
    {
        "module": "cynosdb_cluster_info",
        "service_package": "tencentcloud.cynosdb.v20190107",
        "client_module": "cynosdb_client",
        "client_class": "CynosdbClient",
        "sdk_package": "tencentcloud-sdk-python-cynosdb",
        "endpoint": "cynosdb.tencentcloudapi.com",
        "action": "DescribeClusters",
        "request_class": "DescribeClustersRequest",
        "ids": None,  # DescribeClusters filters by ID through Filters only.
        "filters": {
            "doc": "CynosDB API filter names (ClusterId, InstanceId, InstanceName) "
                   "mapped to lists of values.",
            # CynosDB uses QueryFilter{Names, Values} instead of Filter{Name, Values}.
            "model": "QueryFilter",
            "name_field": "Names",
            "name_wrap": True,
        },
        "extra_params": [],
        "response_items": "ClusterSet",
        "response_total": "TotalCount",
        "result_key": "clusters",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for CynosDB clusters",
        "description": "Returns CynosDB clusters visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CynosDB clusters.",
        "return_total_doc": "Number of clusters reported by the API.",
        "examples": """\
- name: List all CynosDB clusters
  tencentcloud.cloud.cynosdb_cluster_info:
    region: ap-guangzhou

- name: Find a cluster by ID
  tencentcloud.cloud.cynosdb_cluster_info:
    region: ap-guangzhou
    filters:
      ClusterId: [cynosdbmysql-xxxxxxxx]
""",
    },
    {
        "module": "postgres_instance_info",
        "service_package": "tencentcloud.postgres.v20170312",
        "client_module": "postgres_client",
        "client_class": "PostgresClient",
        "sdk_package": "tencentcloud-sdk-python-postgres",
        "endpoint": "postgres.tencentcloudapi.com",
        "action": "DescribeDBInstances",
        "request_class": "DescribeDBInstancesRequest",
        "ids": None,  # DescribeDBInstances filters by ID through Filters only.
        "filters": {"doc": "PostgreSQL API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "DBInstanceSet",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for PostgreSQL instances",
        "description": "Returns TencentDB for PostgreSQL instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TencentDB for PostgreSQL instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all TencentDB for PostgreSQL instances
  tencentcloud.cloud.postgres_instance_info:
    region: ap-guangzhou

- name: Find an instance by ID
  tencentcloud.cloud.postgres_instance_info:
    region: ap-guangzhou
    filters:
      db-instance-id: [postgres-xxxxxxxx]
""",
    },
    {
        "module": "sqlserver_instance_info",
        "service_package": "tencentcloud.sqlserver.v20180328",
        "client_module": "sqlserver_client",
        "client_class": "SqlserverClient",
        "sdk_package": "tencentcloud-sdk-python-sqlserver",
        "endpoint": "sqlserver.tencentcloudapi.com",
        "action": "DescribeDBInstances",
        "request_class": "DescribeDBInstancesRequest",
        "ids": {
            "param": "instance_ids",
            # The SQL Server API calls its ID list InstanceIdSet.
            "field": "InstanceIdSet",
            "doc": "Instance IDs to return.",
        },
        "filters": None,  # DescribeDBInstances has no Filters field.
        "extra_params": [],
        "response_items": "DBInstances",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for SQL Server instances",
        "description": "Returns TencentDB for SQL Server instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TencentDB for SQL Server instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all TencentDB for SQL Server instances
  tencentcloud.cloud.sqlserver_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.sqlserver_instance_info:
    region: ap-guangzhou
    instance_ids: [mssql-xxxxxxxx]
""",
    },
    {
        "module": "mariadb_instance_info",
        "service_package": "tencentcloud.mariadb.v20170312",
        "client_module": "mariadb_client",
        "client_class": "MariadbClient",
        "sdk_package": "tencentcloud-sdk-python-mariadb",
        "endpoint": "mariadb.tencentcloudapi.com",
        "action": "DescribeDBInstances",
        "request_class": "DescribeDBInstancesRequest",
        "ids": {
            "param": "instance_ids",
            "field": "InstanceIds",
            "doc": "Instance IDs to return.",
        },
        "filters": None,  # DescribeDBInstances has no Filters field.
        "extra_params": [],
        "response_items": "Instances",
        "response_total": "TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about TencentDB for MariaDB instances",
        "description": "Returns TencentDB for MariaDB instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TencentDB for MariaDB instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all TencentDB for MariaDB instances
  tencentcloud.cloud.mariadb_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.mariadb_instance_info:
    region: ap-guangzhou
    instance_ids: [tdsql-xxxxxxxx]
""",
    },
    {
        "module": "es_cluster_info",
        "service_package": "tencentcloud.es.v20180416",
        "client_module": "es_client",
        "client_class": "EsClient",
        "sdk_package": "tencentcloud-sdk-python-es",
        "endpoint": "es.tencentcloudapi.com",
        "action": "DescribeInstances",
        "request_class": "DescribeInstancesRequest",
        "ids": {
            "param": "instance_ids",
            "field": "InstanceIds",
            "doc": "Instance IDs to return.",
        },
        "filters": None,  # DescribeInstances has no Filters field.
        "extra_params": [],
        "response_items": "InstanceList",
        "response_total": "TotalCount",
        "result_key": "clusters",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud Elasticsearch clusters",
        "description": "Returns Elasticsearch Service (ES) clusters visible in a Tencent Cloud region.",
        "return_items_doc": "Matching Elasticsearch clusters.",
        "return_total_doc": "Number of clusters reported by the API.",
        "examples": """\
- name: List all Elasticsearch clusters
  tencentcloud.cloud.es_cluster_info:
    region: ap-guangzhou

- name: Find clusters by ID
  tencentcloud.cloud.es_cluster_info:
    region: ap-guangzhou
    instance_ids: [es-xxxxxxxx]
""",
    },
    {
        "module": "ckafka_instance_info",
        "service_package": "tencentcloud.ckafka.v20190819",
        "client_module": "ckafka_client",
        "client_class": "CkafkaClient",
        "sdk_package": "tencentcloud-sdk-python-ckafka",
        "endpoint": "ckafka.tencentcloudapi.com",
        # DescribeInstancesDetail is the canonical paginated list action.
        "action": "DescribeInstancesDetail",
        "request_class": "DescribeInstancesDetailRequest",
        "ids": {
            "param": "instance_ids",
            # InstanceIds is deprecated by the SDK; InstanceIdList replaced it.
            "field": "InstanceIdList",
            "doc": "Instance IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "CKafka API filter names mapped to lists of values."},
        "extra_params": [],
        # The response nests the result under Result (InstanceResponse).
        "response_items": "Result.InstanceList",
        "response_total": "Result.TotalCount",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CKafka instances",
        "description": "Returns CKafka (Cloud Kafka) instances visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CKafka instances.",
        "return_total_doc": "Number of instances reported by the API.",
        "examples": """\
- name: List all CKafka instances
  tencentcloud.cloud.ckafka_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  tencentcloud.cloud.ckafka_instance_info:
    region: ap-guangzhou
    instance_ids: [ckafka-xxxxxxxx]
""",
    },
    {
        "module": "tcr_instance_info",
        "service_package": "tencentcloud.tcr.v20190924",
        "client_module": "tcr_client",
        "client_class": "TcrClient",
        "sdk_package": "tencentcloud-sdk-python-tcr",
        "endpoint": "tcr.tencentcloudapi.com",
        "action": "DescribeInstances",
        "request_class": "DescribeInstancesRequest",
        "ids": {
            "param": "registry_ids",
            # The TCR API spells its ID list Registryids (lowercase "ids").
            "field": "Registryids",
            "doc": "Registry IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "TCR API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "Registries",
        "response_total": "TotalCount",
        "result_key": "registries",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud TCR registries",
        "description": "Returns TCR (Tencent Container Registry) Enterprise instances "
                       "visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TCR registries.",
        "return_total_doc": "Number of registries reported by the API.",
        "examples": """\
- name: List all TCR registries
  tencentcloud.cloud.tcr_instance_info:
    region: ap-guangzhou

- name: Find registries by ID
  tencentcloud.cloud.tcr_instance_info:
    region: ap-guangzhou
    registry_ids: [tcr-xxxxxxxx]
""",
    },
    {
        "module": "apigateway_service_info",
        "service_package": "tencentcloud.apigateway.v20180808",
        "client_module": "apigateway_client",
        "client_class": "ApigatewayClient",
        "sdk_package": "tencentcloud-sdk-python-apigateway",
        "endpoint": "apigateway.tencentcloudapi.com",
        "action": "DescribeServicesStatus",
        "request_class": "DescribeServicesStatusRequest",
        "ids": None,  # DescribeServicesStatus filters by ID through Filters only.
        "filters": {"doc": "API Gateway filter names mapped to lists of values."},
        "extra_params": [],
        # The response nests the result under Result (ServicesStatus).
        "response_items": "Result.ServiceSet",
        "response_total": "Result.TotalCount",
        "result_key": "services",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud API Gateway services",
        "description": "Returns API Gateway services visible in a Tencent Cloud region.",
        "return_items_doc": "Matching API Gateway services.",
        "return_total_doc": "Number of services reported by the API.",
        "examples": """\
- name: List all API Gateway services
  tencentcloud.cloud.apigateway_service_info:
    region: ap-guangzhou

- name: Find a service by ID
  tencentcloud.cloud.apigateway_service_info:
    region: ap-guangzhou
    filters:
      ServiceId: [service-xxxxxxxx]
""",
    },
    # --- Batch 2 (version_added "0.7.0") -----------------------------------
    {
        "module": "nat_gateway_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.vpc.v20170312",
        "client_module": "vpc_client",
        "client_class": "VpcClient",
        "sdk_package": "tencentcloud-sdk-python-vpc",
        "endpoint": "vpc.tencentcloudapi.com",
        "action": "DescribeNatGateways",
        "request_class": "DescribeNatGatewaysRequest",
        "ids": {
            "param": "nat_gateway_ids",
            "field": "NatGatewayIds",
            "doc": "NAT gateway IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "VPC API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "NatGatewaySet",
        "response_total": "TotalCount",
        "result_key": "nat_gateways",
        # Unlike DescribeVpcs, the NAT gateway API takes int Offset/Limit.
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud NAT gateways",
        "description": "Returns NAT gateways visible in a Tencent Cloud region.",
        "return_items_doc": "Matching NAT gateways.",
        "return_total_doc": "Number of NAT gateways reported by the API.",
        "examples": """\
- name: List all NAT gateways
  tencentcloud.cloud.nat_gateway_info:
    region: ap-guangzhou

- name: Find NAT gateways by ID
  tencentcloud.cloud.nat_gateway_info:
    region: ap-guangzhou
    nat_gateway_ids: [nat-xxxxxxxx]
""",
    },
    {
        "module": "vpn_gateway_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.vpc.v20170312",
        "client_module": "vpc_client",
        "client_class": "VpcClient",
        "sdk_package": "tencentcloud-sdk-python-vpc",
        "endpoint": "vpc.tencentcloudapi.com",
        "action": "DescribeVpnGateways",
        "request_class": "DescribeVpnGatewaysRequest",
        "ids": {
            "param": "vpn_gateway_ids",
            "field": "VpnGatewayIds",
            "doc": "VPN gateway IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {
            "doc": "VPC API filter names mapped to lists of values.",
            # DescribeVpnGateways filters use FilterObject, same shape as Filter.
            "model": "FilterObject",
        },
        "extra_params": [],
        "response_items": "VpnGatewaySet",
        "response_total": "TotalCount",
        "result_key": "vpn_gateways",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud VPN gateways",
        "description": "Returns VPN gateways visible in a Tencent Cloud region.",
        "return_items_doc": "Matching VPN gateways.",
        "return_total_doc": "Number of VPN gateways reported by the API.",
        "examples": """\
- name: List all VPN gateways
  tencentcloud.cloud.vpn_gateway_info:
    region: ap-guangzhou

- name: Find VPN gateways by ID
  tencentcloud.cloud.vpn_gateway_info:
    region: ap-guangzhou
    vpn_gateway_ids: [vpngw-xxxxxxxx]
""",
    },
    {
        "module": "gaap_proxy_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.gaap.v20180529",
        "client_module": "gaap_client",
        "client_class": "GaapClient",
        "sdk_package": "tencentcloud-sdk-python-gaap",
        "endpoint": "gaap.tencentcloudapi.com",
        "action": "DescribeProxies",
        "request_class": "DescribeProxiesRequest",
        "ids": {
            "param": "proxy_ids",
            # InstanceIds is the deprecated spelling; ProxyIds replaced it.
            "field": "ProxyIds",
            "doc": "Proxy IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "GAAP API filter names mapped to lists of values."},
        "extra_params": [],
        # InstanceSet is the deprecated response field; ProxySet replaced it.
        "response_items": "ProxySet",
        "response_total": "TotalCount",
        "result_key": "proxies",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud GAAP proxies",
        "description": "Returns GAAP (Global Application Acceleration Platform) proxies "
                       "visible in a Tencent Cloud region.",
        "return_items_doc": "Matching GAAP proxies.",
        "return_total_doc": "Number of proxies reported by the API.",
        "examples": """\
- name: List all GAAP proxies
  tencentcloud.cloud.gaap_proxy_info:
    region: ap-guangzhou

- name: Find proxies by ID
  tencentcloud.cloud.gaap_proxy_info:
    region: ap-guangzhou
    proxy_ids: [link-xxxxxxxx]
""",
    },
    {
        "module": "cdn_domain_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.cdn.v20180606",
        "client_module": "cdn_client",
        "client_class": "CdnClient",
        "sdk_package": "tencentcloud-sdk-python-cdn",
        "endpoint": "cdn.tencentcloudapi.com",
        "action": "DescribeDomains",
        "request_class": "DescribeDomainsRequest",
        "ids": None,  # DescribeDomains cannot filter by a list of domain IDs.
        "filters": {
            "doc": "CDN API domain filter names mapped to lists of values.",
            # CDN uses DomainFilter{Name, Value, Fuzzy}, not Filter{Name, Values}.
            "model": "DomainFilter",
            "value_field": "Value",
        },
        "extra_params": [],
        "response_items": "Domains",
        # The CDN API calls its total count TotalNumber.
        "response_total": "TotalNumber",
        "result_key": "domains",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CDN domains",
        "description": "Returns CDN acceleration domains visible in a Tencent Cloud account.",
        "return_items_doc": "Matching CDN domains.",
        "return_total_doc": "Number of domains reported by the API.",
        "examples": """\
- name: List all CDN domains
  tencentcloud.cloud.cdn_domain_info:
    region: ap-guangzhou

- name: Find a domain by name
  tencentcloud.cloud.cdn_domain_info:
    region: ap-guangzhou
    filters:
      domain: [www.example.com]
""",
    },
    {
        "module": "cloudaudit_event_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.cloudaudit.v20190319",
        "client_module": "cloudaudit_client",
        "client_class": "CloudauditClient",
        "sdk_package": "tencentcloud-sdk-python-cloudaudit",
        "endpoint": "cloudaudit.tencentcloudapi.com",
        # LookUpEvents is the canonical CloudTrail-style lookup action;
        # DescribeEvents is the legacy event list API.
        "action": "LookUpEvents",
        "request_class": "LookUpEventsRequest",
        "ids": None,
        "filters": None,  # LookUpEvents filters via LookupAttributes, not Filter.
        "extra_params": [
            {
                "name": "start_time",
                "field": "StartTime",
                "type": "int",
                "doc": "Start of the time range as a Unix timestamp.",
            },
            {
                "name": "end_time",
                "field": "EndTime",
                "type": "int",
                "doc": "End of the time range as a Unix timestamp.",
            },
        ],
        "response_items": "Events",
        "response_total": "TotalCount",
        "result_key": "events",
        # LookUpEvents paginates with NextToken/MaxResults and caps pages at 50.
        "pagination_type": "token",
        "page_size_default": 50,
        "short_description": "Gather information about Tencent Cloud CloudAudit events",
        "description": "Returns CloudAudit operation events visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CloudAudit events.",
        "return_total_doc": "Number of events reported by the API.",
        "examples": """\
- name: List recent CloudAudit events
  tencentcloud.cloud.cloudaudit_event_info:
    region: ap-guangzhou

- name: List events in a time range
  tencentcloud.cloud.cloudaudit_event_info:
    region: ap-guangzhou
    start_time: 1704067200
    end_time: 1704153600
""",
    },
    {
        "module": "cwp_machine_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.cwp.v20180228",
        "client_module": "cwp_client",
        "client_class": "CwpClient",
        "sdk_package": "tencentcloud-sdk-python-cwp",
        "endpoint": "cwp.tencentcloudapi.com",
        "action": "DescribeMachines",
        "request_class": "DescribeMachinesRequest",
        "ids": None,  # Machines are queried by ID through Filters (Uuid/InstanceId).
        "filters": {"doc": "CWP API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "Machines",
        "response_total": "TotalCount",
        "result_key": "machines",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CWP machines",
        "description": "Returns machines protected by Host Security (CWP) "
                       "visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CWP machines.",
        "return_total_doc": "Number of machines reported by the API.",
        "examples": """\
- name: List all CWP machines
  tencentcloud.cloud.cwp_machine_info:
    region: ap-guangzhou

- name: Find a machine by ID
  tencentcloud.cloud.cwp_machine_info:
    region: ap-guangzhou
    filters:
      InstanceId: [ins-xxxxxxxx]
""",
    },
    {
        "module": "waf_instance_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.waf.v20180125",
        "client_module": "waf_client",
        "client_class": "WafClient",
        "sdk_package": "tencentcloud-sdk-python-waf",
        "endpoint": "waf.tencentcloudapi.com",
        "action": "DescribeInstances",
        "request_class": "DescribeInstancesRequest",
        "ids": None,  # DescribeInstances filters by ID through Filters only.
        "filters": {
            "doc": "WAF API filter names mapped to lists of values.",
            # WAF uses FiltersItemNew{Name, Values, ExactMatch}.
            "model": "FiltersItemNew",
        },
        "extra_params": [],
        "response_items": "Instances",
        # The WAF API calls its total count Total.
        "response_total": "Total",
        "result_key": "instances",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud WAF instances",
        "description": "Returns Web Application Firewall (WAF) instances "
                       "visible in a Tencent Cloud region.",
        "return_items_doc": "Matching WAF instances.",
        "return_total_doc": "Number of WAF instances reported by the API.",
        "examples": """\
- name: List all WAF instances
  tencentcloud.cloud.waf_instance_info:
    region: ap-guangzhou

- name: Find a WAF instance by ID
  tencentcloud.cloud.waf_instance_info:
    region: ap-guangzhou
    filters:
      InstanceId: [waf_xxxxxxxx]
""",
    },
    {
        "module": "ssl_certificate_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.ssl.v20191205",
        "client_module": "ssl_client",
        "client_class": "SslClient",
        "sdk_package": "tencentcloud-sdk-python-ssl",
        "endpoint": "ssl.tencentcloudapi.com",
        "action": "DescribeCertificates",
        "request_class": "DescribeCertificatesRequest",
        "ids": {
            "param": "certificate_ids",
            "field": "CertIds",
            "doc": "Certificate IDs to return.",
        },
        "filters": None,  # DescribeCertificates has no Filters field.
        "extra_params": [],
        "response_items": "Certificates",
        "response_total": "TotalCount",
        "result_key": "certificates",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud SSL certificates",
        "description": "Returns SSL certificates visible in a Tencent Cloud account.",
        "return_items_doc": "Matching SSL certificates.",
        "return_total_doc": "Number of certificates reported by the API.",
        "examples": """\
- name: List all SSL certificates
  tencentcloud.cloud.ssl_certificate_info:
    region: ap-guangzhou

- name: Find certificates by ID
  tencentcloud.cloud.ssl_certificate_info:
    region: ap-guangzhou
    certificate_ids: ["xxxxxxxx"]
""",
    },
    {
        "module": "organization_member_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.organization.v20210331",
        "client_module": "organization_client",
        "client_class": "OrganizationClient",
        "sdk_package": "tencentcloud-sdk-python-organization",
        "endpoint": "organization.tencentcloudapi.com",
        "action": "DescribeOrganizationMembers",
        "request_class": "DescribeOrganizationMembersRequest",
        "ids": None,  # DescribeOrganizationMembers cannot filter by member ID.
        "filters": None,  # DescribeOrganizationMembers has no Filters field.
        "extra_params": [],
        "response_items": "Items",
        # The Organization API calls its total count Total.
        "response_total": "Total",
        "result_key": "members",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud Organization members",
        "description": "Returns the members of a Tencent Cloud Organization.",
        "return_items_doc": "Organization members.",
        "return_total_doc": "Number of members reported by the API.",
        "examples": """\
- name: List all organization members
  tencentcloud.cloud.organization_member_info:
    region: ap-guangzhou
""",
    },
    {
        "module": "monitor_alarm_policy_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.monitor.v20180724",
        "client_module": "monitor_client",
        "client_class": "MonitorClient",
        "sdk_package": "tencentcloud-sdk-python-monitor",
        "endpoint": "monitor.tencentcloudapi.com",
        "action": "DescribeAlarmPolicies",
        "request_class": "DescribeAlarmPoliciesRequest",
        "ids": None,  # DescribeAlarmPolicies cannot filter by policy ID.
        "filters": None,  # DescribeAlarmPolicies has no Filters field.
        "extra_params": [
            {
                "name": "module",
                "field": "Module",
                "type": "str",
                # The API requires Module; "monitor" is its only valid value.
                "default": "monitor",
                "doc": "Service type. The only valid value is C(monitor).",
            },
        ],
        "response_items": "Policies",
        "response_total": "TotalCount",
        "result_key": "alarm_policies",
        # The monitor API paginates with 1-based PageNumber/PageSize.
        "pagination_type": "page",
        "short_description": "Gather information about Tencent Cloud Monitor alarm policies",
        "description": "Returns Cloud Monitor alarm policies visible in a Tencent Cloud account.",
        "return_items_doc": "Matching alarm policies.",
        "return_total_doc": "Number of alarm policies reported by the API.",
        "examples": """\
- name: List all alarm policies
  tencentcloud.cloud.monitor_alarm_policy_info:
    region: ap-guangzhou
""",
    },
    {
        "module": "cls_topic_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.cls.v20201016",
        "client_module": "cls_client",
        "client_class": "ClsClient",
        "sdk_package": "tencentcloud-sdk-python-cls",
        "endpoint": "cls.tencentcloudapi.com",
        "action": "DescribeTopics",
        "request_class": "DescribeTopicsRequest",
        "ids": None,  # DescribeTopics filters by ID through Filters only.
        "filters": {
            "doc": "CLS API filter keys mapped to lists of values.",
            # The CLS Filter model spells its name field Key.
            "name_field": "Key",
        },
        "extra_params": [],
        "response_items": "Topics",
        "response_total": "TotalCount",
        "result_key": "topics",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud CLS log topics",
        "description": "Returns CLS (Cloud Log Service) log topics visible in a Tencent Cloud region.",
        "return_items_doc": "Matching CLS log topics.",
        "return_total_doc": "Number of log topics reported by the API.",
        "examples": """\
- name: List all CLS log topics
  tencentcloud.cloud.cls_topic_info:
    region: ap-guangzhou

- name: Find topics of a logset
  tencentcloud.cloud.cls_topic_info:
    region: ap-guangzhou
    filters:
      logsetId: [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx]
""",
    },
    {
        "module": "tat_command_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.tat.v20201028",
        "client_module": "tat_client",
        "client_class": "TatClient",
        "sdk_package": "tencentcloud-sdk-python-tat",
        "endpoint": "tat.tencentcloudapi.com",
        "action": "DescribeCommands",
        "request_class": "DescribeCommandsRequest",
        "ids": {
            "param": "command_ids",
            "field": "CommandIds",
            "doc": "Command IDs to return. Mutually exclusive with O(filters).",
        },
        "filters": {"doc": "TAT API filter names mapped to lists of values."},
        "extra_params": [],
        "response_items": "CommandSet",
        "response_total": "TotalCount",
        "result_key": "commands",
        "pagination_type": "int",
        "short_description": "Gather information about Tencent Cloud TAT commands",
        "description": "Returns TAT (TencentCloud Automation Tools) commands "
                       "visible in a Tencent Cloud region.",
        "return_items_doc": "Matching TAT commands.",
        "return_total_doc": "Number of commands reported by the API.",
        "examples": """\
- name: List all TAT commands
  tencentcloud.cloud.tat_command_info:
    region: ap-guangzhou

- name: Find commands by ID
  tencentcloud.cloud.tat_command_info:
    region: ap-guangzhou
    command_ids: [cmd-xxxxxxxx]
""",
    },
    {
        "module": "billing_balance_info",
        "version_added": "0.7.0",
        "service_package": "tencentcloud.billing.v20180709",
        "client_module": "billing_client",
        "client_class": "BillingClient",
        "sdk_package": "tencentcloud-sdk-python-billing",
        "endpoint": "billing.tencentcloudapi.com",
        # DescribeAccountBalance takes no request arguments and is not
        # paginated; it returns a single account balance object.
        "action": "DescribeAccountBalance",
        "request_class": "DescribeAccountBalanceRequest",
        "ids": None,
        "filters": None,
        "extra_params": [],
        "response_items": None,
        "response_total": None,
        "result_key": "balance",
        "pagination_type": "none",
        "short_description": "Gather information about the Tencent Cloud account balance",
        "description": "Returns the balance of the Tencent Cloud account.",
        "return_items_doc": "Account balance as reported by the API.",
        "return_total_doc": "",
        "examples": """\
- name: Show the account balance
  tencentcloud.cloud.billing_balance_info:
    region: ap-guangzhou
""",
    },
]


def _load_auto_specs():
    """Load auto-discovered specs from ``scripts/info_specs_auto.py``.

    The file is written by ``scripts/discover_info_specs.py``. Loading it by
    path (rather than a plain import) keeps the combined spec list available
    when this script is exec'd via importlib by the contract/unit tests.
    """
    path = Path(__file__).with_name("info_specs_auto.py")
    if not path.exists():
        return []
    spec = importlib.util.spec_from_file_location("info_specs_auto", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return list(module.SPECS_AUTO)


SPECS = SPECS + _load_auto_specs()

HEADER = f"""\
#!/usr/bin/python
# -*- coding: utf-8 -*-
{MARKER}
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type
"""

IMPORTS = """\
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)
"""

PAGINATOR_IMPORT = ("from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging "
                    "import Paginator\n")


def _page_size_field(spec):
    """Return the request field receiving the page size, or None.

    Defaults by pagination type: Limit (int), PageSize (page), MaxResults
    (token). A spec may set ``page_size_field`` to override the name, or to
    None for token APIs without a page-size field (chdfs, faceid).
    """
    pagination = spec.get("pagination_type", "int")
    if pagination in ("none", "list"):
        return None
    default = {"int": "Limit", "page": "PageSize", "token": "MaxResults"}[pagination]
    return spec.get("page_size_field", default)


def _imports(spec):
    """Render the import block; token/none/list specs do not use the Paginator."""
    if spec.get("pagination_type", "int") in ("token", "none", "list"):
        return IMPORTS
    return IMPORTS.replace(
        "from ansible.module_utils.basic import AnsibleModule\n",
        "from ansible.module_utils.basic import AnsibleModule\n" + PAGINATOR_IMPORT)


def _documentation(spec):
    lines = [
        "---",
        f"module: {spec['module']}",
        f"short_description: {spec['short_description']}",
        f'version_added: "{spec.get("version_added", VERSION_ADDED)}"',
        f"description: {spec['description']}",
        "options:",
    ]
    option_lines = []
    for param in spec["extra_params"]:
        option_lines += [
            f"  {param['name']}:",
            f"    description: {param['doc']}",
            f"    type: {param['type']}",
        ]
        if param.get("required"):
            option_lines.append("    required: true")
        if "default" in param:
            option_lines.append(f"    default: {param['default']}")
    if spec["ids"]:
        option_lines += [
            f"  {spec['ids']['param']}:",
            f"    description: {spec['ids']['doc']}",
            "    type: list",
            "    elements: str",
        ]
    if spec["filters"]:
        option_lines += [
            "  filters:",
            f"    description: {spec['filters']['doc']}",
            "    type: dict",
            "    default: {}",
        ]
    if _page_size_field(spec) is not None:
        option_lines += [
            "  page_size:",
            "    description: Number of results requested per API call.",
            "    type: int",
            f"    default: {spec.get('page_size_default', 100)}",
        ]
    if option_lines:
        lines += option_lines
    else:
        lines[-1] = "options: {}"
    lines += [
        f"extends_documentation_fragment: {DOC_FRAGMENT}",
        f"author: {AUTHOR}",
    ]
    return "\n".join(lines)


def _return_block(spec):
    if spec.get("pagination_type") == "none":
        return f"""\
{spec['result_key']}:
  description: {spec['return_items_doc']}
  returned: always
  type: dict"""
    return f"""\
{spec['result_key']}:
  description: {spec['return_items_doc']}
  returned: always
  type: list
  elements: dict
total_count:
  description: {spec['return_total_doc']}
  returned: always
  type: int"""


def _build_request_source(spec):
    """Render the module-level request builder function(s)."""
    request_class = spec["request_class"]
    if spec.get("ids_action"):
        ids = spec["ids"]
        ids_action = spec.get("ids_action")
        return f"""\
def build_list_request(models, offset, limit):
    request = models.{request_class}()
    request.Offset = offset
    request.Limit = limit
    return request


def build_describe_request(models, {ids['param']}):
    request = models.{ids_action['request_class']}()
    request.{ids['field']} = {ids['param']}
    return request
"""
    pagination = spec.get("pagination_type", "int")
    args = ["models"]
    args += [param["name"] for param in spec["extra_params"]]
    if spec["ids"]:
        args.append(spec["ids"]["param"])
    if spec["filters"]:
        args.append("filters")
    if pagination == "token":
        args += ["next_token", "max_results"]
    else:
        args += ["offset", "limit"]
    lines = [
        f"def build_request({', '.join(args)}):",
        f"    request = models.{request_class}()",
    ]
    if pagination == "page":
        page_number_field = spec.get("page_number_field", "PageNumber")
        lines += [
            f"    request.{page_number_field} = offset // limit + 1",
            f"    request.{_page_size_field(spec)} = limit",
        ]
    elif pagination == "token":
        if _page_size_field(spec) is not None:
            lines.append(f"    request.{_page_size_field(spec)} = max_results")
    elif pagination in ("none", "list"):
        if pagination == "none":
            comment = (f"    # {spec['action']} takes no request arguments and is not\n"
                       "    # paginated; offset and limit are accepted for signature uniformity.")
        else:
            comment = (f"    # {spec['action']} returns the full list in one call and is not\n"
                       "    # paginated; offset and limit are accepted for signature uniformity.")
        lines.insert(1, comment)
    else:
        lines += [
            "    request.Offset = offset",
            f"    request.{_page_size_field(spec)} = limit",
        ]
    for param in spec["extra_params"]:
        if param.get("required") or "default" in param:
            lines.append(f"    request.{param['field']} = {param['name']}")
        else:
            lines += [
                f"    if {param['name']} is not None:",
                f"        request.{param['field']} = {param['name']}",
            ]
    if spec["ids"]:
        lines += [
            f"    if {spec['ids']['param']}:",
            f"        request.{spec['ids']['field']} = {spec['ids']['param']}",
        ]
    if spec["filters"]:
        filter_model = spec["filters"].get("model", "Filter")
        name_field = spec["filters"].get("name_field", "Name")
        value_field = spec["filters"].get("value_field", "Values")
        if spec["filters"].get("name_wrap"):
            name_value = "[name]"
        else:
            name_value = "name"
        lines += [
            "    if filters:",
            "        request.Filters = []",
            "        for name, values in sorted(filters.items()):",
            f"            api_filter = models.{filter_model}()",
            f"            api_filter.{name_field} = {name_value}",
            f"            api_filter.{value_field} = values if isinstance(values, list) else [values]",
            "            request.Filters.append(api_filter)",
        ]
    if pagination == "token":
        token_field = spec.get("token_request_field", "NextToken")
        lines += [
            "    if next_token:",
            f"        request.{token_field} = next_token",
        ]
    lines.append("    return request")
    return "\n".join(lines) + "\n"


def _nested_lambda(path):
    """Render a response accessor lambda; dotted paths guard the holder."""
    if "." in path:
        holder, _dot, field = path.partition(".")
        return (f"lambda response: response.{holder}.{field} "
                f"if response.{holder} is not None else None")
    return f"lambda response: response.{path}"


def _total_lambda(spec):
    if spec["response_total"] is None:
        # The API reports no total; pagination stops at the first short page.
        return "lambda response: None"
    return _nested_lambda(spec["response_total"])


def _items_lambda(spec):
    return _nested_lambda(spec["response_items"])


def _argument_spec_lines(spec):
    argument_lines = []
    for param in spec["extra_params"]:
        entry = f'{{"type": "{param["type"]}"'
        if param.get("required"):
            entry += ', "required": True'
        if "default" in param:
            entry += f', "default": "{param["default"]}"'
        entry += "}"
        argument_lines.append(f'        "{param["name"]}": {entry},')
    if spec["ids"]:
        ids_entry = '{"type": "list", "elements": "str"'
        if spec["ids"].get("no_log") is False:
            ids_entry += ', "no_log": False'
        ids_entry += "}"
        argument_lines.append(f'        "{spec["ids"]["param"]}": {ids_entry},')
    if spec["filters"]:
        argument_lines.append('        "filters": {"type": "dict", "default": {}},')
    if _page_size_field(spec) is not None:
        argument_lines.append(
            f'        "page_size": {{"type": "int", "default": {spec.get("page_size_default", 100)}}},')
    return "\n".join(argument_lines)


def _client_setup_source(spec):
    return f"""\
    try:
        from {spec['service_package']} import models, {spec['client_module']}
    except ImportError:
        module.fail_json(msg="The {spec['sdk_package']} package is required.")

    client = {spec['client_module']}.{spec['client_class']}(
        create_credential(module), module.params["region"],
        create_client_profile(module, "{spec['endpoint']}"),
    )
"""


def _run_module_token_source(spec):
    """Render run_module for token-paginated APIs (cloudaudit, alb, ...).

    Field names come from the spec so products whose continuation token is
    not called NextToken (ams PageToken, chdfs FileSystemIdMarker, faceid
    Cursor) share the same loop; cloudaudit keeps the default field names.
    """
    token_response_field = spec.get("token_response_field", "NextToken")
    list_over_field = spec.get("list_over_field", "ListOver")
    has_more_field = spec.get("has_more_field")
    if list_over_field:
        termination = f"response.{list_over_field} or not next_token"
    elif has_more_field:
        termination = f"not response.{has_more_field} or not next_token"
    else:
        termination = "not next_token"
    if spec["response_total"] is not None:
        total_lines = (f"        if total_count is None and response.{spec['response_total']} is not None:\n"
                       f"            total_count = response.{spec['response_total']}\n")
    else:
        total_lines = ""
    page_size_arg = ('module.params["page_size"]' if _page_size_field(spec) is not None
                     else "None")
    build_args = ["models"]
    build_args += [f'module.params["{param["name"]}"]' for param in spec["extra_params"]]
    build_args += ["next_token", page_size_arg]
    build_call = "build_request(\n            " + ",\n            ".join(build_args) + ")"
    argument_lines = _argument_spec_lines(spec)
    if argument_lines:
        update = f"argument_spec.update({{\n{argument_lines}\n    }})"
    else:
        update = "argument_spec.update({})"
    return f"""\
def run_module():
    argument_spec = tencentcloud_argument_spec()
    {update}
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
{_client_setup_source(spec)}    {spec['result_key']} = []
    next_token = None
    total_count = None
    while True:
        request = {build_call}
        response = sdk_call(module, client.{spec['action']}, request)
        batch = response.{spec['response_items']} or []
        {spec['result_key']}.extend(serialize_sdk_object(item) for item in batch)
{total_lines}        next_token = response.{token_response_field}
        if {termination}:
            break
    if total_count is None:
        total_count = len({spec['result_key']})
    module.exit_json(changed=False, {spec['result_key']}={spec['result_key']}, total_count=total_count)
"""


def _run_module_list_source(spec):
    """Render run_module for unpaginated list APIs (advisor, captcha).

    Unlike "none" (billing) the response carries an items list; the whole
    list is returned by a single call and total_count is its length.
    """
    items_expr = spec["response_items"]
    if "." in items_expr:
        holder, _dot, field = items_expr.partition(".")
        items_expr = (f"(response.{holder}.{field} "
                      f"if response.{holder} is not None else None)")
    else:
        items_expr = f"response.{items_expr}"
    argument_lines = _argument_spec_lines(spec)
    if argument_lines:
        update = f"argument_spec.update({{\n{argument_lines}\n    }})"
    else:
        update = "argument_spec.update({})"
    return f"""\
def run_module():
    argument_spec = tencentcloud_argument_spec()
    {update}
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
{_client_setup_source(spec)}    request = build_request(models, 0, 0)
    response = sdk_call(module, client.{spec['action']}, request)
    items = {items_expr} or []
    {spec['result_key']} = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, {spec['result_key']}={spec['result_key']},
                     total_count=len({spec['result_key']}))
"""


def _run_module_none_source(spec):
    """Render run_module for unpaginated single-object APIs (billing)."""
    argument_lines = _argument_spec_lines(spec)
    if argument_lines:
        update = f"argument_spec.update({{\n{argument_lines}\n    }})"
    else:
        update = "argument_spec.update({})"
    return f"""\
def run_module():
    argument_spec = tencentcloud_argument_spec()
    {update}
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
{_client_setup_source(spec)}    request = build_request(models, 0, 0)
    response = sdk_call(module, client.{spec['action']}, request)
    {spec['result_key']} = serialize_sdk_object(response)
    {spec['result_key']}.pop("RequestId", None)
    module.exit_json(changed=False, {spec['result_key']}={spec['result_key']})
"""


def _run_module_source(spec):
    pagination = spec.get("pagination_type", "int")
    if pagination == "token":
        return _run_module_token_source(spec)
    if pagination == "none":
        return _run_module_none_source(spec)
    if pagination == "list":
        return _run_module_list_source(spec)
    argument_spec = _argument_spec_lines(spec)

    mutually_exclusive = ""
    if spec["ids"] and spec["filters"] and not spec.get("ids_action"):
        mutually_exclusive = (f'\n        mutually_exclusive=[("{spec["ids"]["param"]}", "filters")],')

    build_args = ["models"]
    build_args += [f'module.params["{param["name"]}"]' for param in spec["extra_params"]]
    if spec["ids"] and not spec.get("ids_action"):
        build_args.append(f'module.params["{spec["ids"]["param"]}"]')
    if spec["filters"]:
        build_args.append('module.params["filters"]')
    build_args += ["offset", "limit"]
    build_call = f"build_request({', '.join(build_args)})"
    if len(build_call) > 79:
        build_call = "build_request(\n            " + ",\n            ".join(build_args) + ")"

    ids_branch = ""
    if spec.get("ids_action"):
        ids = spec["ids"]
        ids_action = spec.get("ids_action")
        ids_branch = f"""\
    {ids['param']} = module.params["{ids['param']}"]
    if {ids['param']}:
        request = build_describe_request(models, {ids['param']})
        response = sdk_call(module, client.{ids_action['action']}, request)
        items = response.{ids_action['response_items']} or []
        {spec['result_key']} = [serialize_sdk_object(item) for item in items]
        module.exit_json(changed=False, {spec['result_key']}={spec['result_key']},
                         total_count=len({spec['result_key']}))
"""

    builder = "build_list_request(models, offset, limit)" if spec.get("ids_action") else build_call
    builder_lines = f"lambda offset, limit: {builder}"
    if len(builder_lines) > 79:
        builder_lines = ("lambda offset, limit: build_list_request(\n"
                         "            models, offset, limit)" if spec.get("ids_action")
                         else builder_lines)

    return f"""\
def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({{
{argument_spec}
    }})
    module = AnsibleModule(
        argument_spec=argument_spec,{mutually_exclusive}
        supports_check_mode=True,
    )
{_client_setup_source(spec)}{ids_branch}\
    paginator = Paginator(
        module.params["page_size"],
        {builder_lines},
        lambda request: sdk_call(module, client.{spec['action']}, request),
        {_items_lambda(spec)},
        {_total_lambda(spec)},
    )
    item_set, total_count = paginator.fetch_all()
    {spec['result_key']} = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, {spec['result_key']}={spec['result_key']}, total_count=total_count)
"""


def render_module(spec):
    """Render the full source of the module described by *spec*."""
    return f"""\
{HEADER}
DOCUMENTATION = r'''
{_documentation(spec)}
'''

EXAMPLES = r'''
{spec['examples']}'''

RETURN = r'''
{_return_block(spec)}
'''

{_imports(spec)}

{_build_request_source(spec)}

{_run_module_source(spec)}

def main():
    run_module()


if __name__ == "__main__":
    main()
"""


def module_path(spec):
    return MODULES_DIR / f"{spec['module']}.py"


def test_path(spec):
    return TESTS_DIR / f"test_{spec['module']}.py"


def is_simple_spec(spec):
    """True when *spec* fits the generated unit-test template.

    Plain offset/limit or page-number specs (with or without a total-count
    field) and unpaginated top-level list specs are covered; every other
    spec keeps its hand-written test file (never rewritten, never verified
    here).
    """
    pagination = spec.get("pagination_type", "int")
    if pagination == "list":
        return "." not in spec["response_items"]
    return (pagination in ("int", "page")
            and not spec.get("ids_action")
            and not spec["extra_params"])


def _fake_response_fields(spec):
    """Render FakeResponse attribute assignments for possibly dotted paths."""
    holders = {}
    for path, value in ((spec["response_items"], "items"),
                        (spec["response_total"], "total_count")):
        if path is None:
            continue
        if "." in path:
            holder, _dot, field = path.partition(".")
            holders.setdefault(holder, {})[field] = value
        else:
            holders[path] = value
    lines = []
    for attr, value in holders.items():
        if isinstance(value, dict):
            inner = ", ".join(f"{field}={val}" for field, val in sorted(value.items()))
            lines.append(f"        self.{attr} = types.SimpleNamespace({inner})")
        else:
            lines.append(f"        self.{attr} = {value}")
    return "\n".join(lines)


def render_list_test(spec):
    """Render the unit test file for an unpaginated list spec."""
    module = spec["module"]
    product = spec["service_package"].split(".")[1]
    return f'''\
{MARKER}
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.tencentcloud.cloud.plugins.modules import {module}


class FakeRequest:
    pass


class FakeModels:
    {spec["request_class"]} = FakeRequest


class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {{"Marker": self.marker}}


class FakeResponse:
    def __init__(self, items):
        self.{spec["response_items"]} = items


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def {spec["action"]}(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        raise AssertionError("fail_json called: %r" % (kwargs,))


def _run(monkeypatch, client, **params):
    service = types.ModuleType("{spec['service_package']}")
    service.models = FakeModels
    service.{spec["client_module"]} = types.SimpleNamespace({spec["client_class"]}=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.{product}",
                        types.ModuleType("tencentcloud.{product}"))
    monkeypatch.setitem(sys.modules, "{spec['service_package']}", service)
    fake = FakeModule(params)
    monkeypatch.setattr({module}, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr({module}, "create_credential", lambda module: object())
    monkeypatch.setattr({module}, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        {module}.run_module()
    return fake


def test_run_module_returns_full_list(monkeypatch):
    client = FakeClient([FakeResponse([FakeItem("a"), FakeItem("b")])])
    fake = _run(monkeypatch, client, region="ap-guangzhou")
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["{spec['result_key']}"]] == ["a", "b"]
    assert payload["total_count"] == 2
    assert len(client.requests) == 1
'''


def render_test(spec):
    """Render the unit test file for a simple spec (see is_simple_spec)."""
    if spec.get("pagination_type") == "list":
        return render_list_test(spec)
    module = spec["module"]
    ids = spec["ids"]
    filters = spec["filters"]
    page = spec.get("pagination_type", "int") == "page"
    product = spec["service_package"].split(".")[1]

    fake_filter = ""
    if filters:
        fake_filter = """

class FakeFilter:
    pass
"""

    fake_models = f'    {spec["request_class"]} = FakeRequest'
    if filters:
        fake_models = f'    {filters.get("model", "Filter")} = FakeFilter\n' + fake_models

    def build_call(ids_value, filters_value, offset, limit):
        parts = ["FakeModels"]
        if ids:
            parts.append(ids_value)
        if filters:
            parts.append(filters_value)
        parts += [offset, limit]
        return f"{module}.build_request({', '.join(parts)})"

    if page:
        page_number_field = spec.get("page_number_field", "PageNumber")
        pagination_asserts = (f"    assert request.{page_number_field} == 3\n"
                              f"    assert request.{_page_size_field(spec)} == 100")
        page_numbers = "[1, 2]"
        page_field = page_number_field
    else:
        pagination_asserts = ("    assert request.Offset == 200\n"
                              f"    assert request.{_page_size_field(spec)} == 100")
        page_numbers = "[0, 2]"
        page_field = "Offset"

    ids_test = ""
    if ids:
        ids_test = f'''

def test_build_request_maps_ids():
    request = {build_call('["x-1"]', "{}", "0", "100")}
    assert request.{ids["field"]} == ["x-1"]
'''

    filters_test = ""
    if filters:
        name_field = filters.get("name_field", "Name")
        value_field = filters.get("value_field", "Values")
        if filters.get("name_wrap"):
            name_a, name_b = '["a-name"]', '["b-name"]'
        else:
            name_a, name_b = '"a-name"', '"b-name"'
        filters_test = f'''

def test_build_request_sorts_filters():
    request = {build_call("None", '{"b-name": ["v1"], "a-name": ["v2"]}', "0", "100")}
    assert [(item.{name_field}, item.{value_field}) for item in request.Filters] == [
        ({name_a}, ["v2"]), ({name_b}, ["v1"]),
    ]
'''

    params = ""
    if ids:
        params += f'{ids["param"]}=None, '
    if filters:
        params += "filters={}, "

    if spec["response_total"] is None:
        # No total-count field: pagination stops at the first short page and
        # total_count falls back to the number of items collected.
        pagination_test = "test_run_module_paginates_until_short_page"
        fake_total = "None"
    else:
        pagination_test = "test_run_module_paginates_until_total_count"
        fake_total = "3"

    return f'''\
{MARKER}
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.tencentcloud.cloud.plugins.modules import {module}
{fake_filter}

class FakeRequest:
    pass


class FakeModels:
{fake_models}


def test_build_request_sets_pagination():
    request = {build_call("None", "{}", "200", "100")}
{pagination_asserts}
{ids_test}{filters_test}

class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {{"Marker": self.marker}}


class FakeResponse:
    def __init__(self, items, total_count):
{_fake_response_fields(spec)}


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def {spec["action"]}(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        raise AssertionError("fail_json called: %r" % (kwargs,))


def _run(monkeypatch, client, **params):
    service = types.ModuleType("{spec['service_package']}")
    service.models = FakeModels
    service.{spec["client_module"]} = types.SimpleNamespace({spec["client_class"]}=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.{product}",
                        types.ModuleType("tencentcloud.{product}"))
    monkeypatch.setitem(sys.modules, "{spec['service_package']}", service)
    fake = FakeModule(params)
    monkeypatch.setattr({module}, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr({module}, "create_credential", lambda module: object())
    monkeypatch.setattr({module}, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        {module}.run_module()
    return fake


def {pagination_test}(monkeypatch):
    client = FakeClient([
        FakeResponse([FakeItem("a"), FakeItem("b")], {fake_total}),
        FakeResponse([FakeItem("c")], {fake_total}),
    ])
    fake = _run(monkeypatch, client, region="ap-guangzhou",
                {params}page_size=2)
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["{spec['result_key']}"]] == ["a", "b", "c"]
    assert payload["total_count"] == 3
    assert [request.{page_field} for request in client.requests] == {page_numbers}
'''


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="do not write files; fail if a generated module is missing or stale",
    )
    args = parser.parse_args(argv)

    stale = []
    for spec in SPECS:
        path = module_path(spec)
        rendered = render_module(spec)
        if args.check:
            if not path.exists() or path.read_text() != rendered:
                stale.append(path.name)
        elif path.exists() and path.read_text() == rendered:
            print(f"up to date: {path}")
        else:
            path.write_text(rendered)
            print(f"wrote: {path}")

        if not is_simple_spec(spec):
            continue
        # Hand-finished test files (no MARKER) are never rewritten or checked.
        tpath = test_path(spec)
        if tpath.exists() and MARKER not in tpath.read_text():
            continue
        trendered = render_test(spec)
        if args.check:
            if not tpath.exists() or tpath.read_text() != trendered:
                stale.append(tpath.name)
        elif tpath.exists() and tpath.read_text() == trendered:
            print(f"up to date: {tpath}")
        else:
            tpath.write_text(trendered)
            print(f"wrote: {tpath}")

    if stale:
        print("stale generated files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
