# -*- coding: utf-8 -*-
"""Generate unit-test skeletons for Tencent Cloud write modules (roadmap #57 lever 1).

A "write module" is a stateful resource module (``state: present|absent``)
whose flow is: lazy ``_load_*`` of the SDK models/client, request builders,
an identify helper (``find*``), optional waiters, a ``run_module`` switch
over state and a ``main``. Hundreds of modules share this shape, but 222 of
the write modules had no dedicated test file (measured 2026-09-02), and the
shared boilerplate (imports, fixtures, fake client, argument dicts) is ~45%
of a finished test file. See ``docs/coverage-batching.md`` for the plan.

This script is the **skeleton** half of that lever: ``--module-test <name>``
statically reads one write module and emits a runnable starting point --

* the harness imports and a ``client`` fixture wiring the shared
  monkeypatches (``require_sdk`` no-op, ``_load_*`` -> fakes,
  ``create_client`` -> an in-memory fake client);
* a ``FakeModule`` and a ``Fake<Service>Client`` whose methods record every
  call (write operations return an empty response and carry a TODO comment
  pointing at the module behavior they must reproduce, so waiter polls can
  converge once finished);
* ``_params()`` pre-filled from the module's ``argument_spec`` (plus the
  shared ``waiter_*``/``retries`` defaults);
* real, runnable tests per unconditional request-builder assignment
  (``request.Field = <literal | params ref | arg ref>``) and for the
  argument-enforcement and wrapped-SDK-error paths of ``run_module`` --
  the three things provable from source alone;
* ``xfail`` stubs, one per remaining helper and per state branch, each
  annotated with the exact module line range it should exercise.

Assertions that encode a resource's drift rules stay human. The generated
file is a starting point, not a pass. Delete the ``MARKER`` line once you
start hand-finishing a file so the generator (and CI ``--check``) never
touches it again.

Run ``--module-test <name> --check`` to verify a committed skeleton is
unmodified (CI), ``--print`` to review instead of writing.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = REPO_ROOT / "plugins" / "modules"
TESTS_DIR = REPO_ROOT / "tests" / "unit" / "plugins" / "modules"

MARKER = "# Skeleton generated by scripts/generate_module_test_skeleton.py -- delete this line when you start hand-finishing."
HARNESS = "ansible_collections.susunola.tencentcloud.tests.unit.plugins.modules.harness"

# Shared argument-spec entries wired by TencentCloudModule (module_utils/base.py).
BASE_PARAMS = {
    "retries": 5,
    "waiter_timeout": 120,
    "waiter_delay": 5,
}

CLIENT_ALIASES = ("client", "cm", "vpc_client", "cvm_client")
READ_OP_RE = re.compile(r"^(Describe|List|Inquiry|Get|Search|Lookup|Status|Query)")

ID_PREFIX = {
    "ccn": "ccn-8b0a1c2d",
    "vpc": "vpc-8b0a1c2d",
    "subnet": "subnet-8b0a1c2d",
    "instance": "ins-8b0a1c2d",
    "disk": "disk-8b0a1c2d",
    "cluster": "cls-8b0a1c2d",
}


class AnalysisError(Exception):
    """The module cannot be analyzed; nothing is written."""


def _id_placeholder(name):
    """A readable, obviously-fake identifier for argument ``name``."""
    for key, value in ID_PREFIX.items():
        if key in name:
            return value
    stem = name.replace("_id", "").replace("_", "-").strip("-")
    return "%s-xxxx" % stem if stem else "example"


def _spec_value(node):
    """Value of a spec option node, or None when not statically known."""
    if node is None:
        return None
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.List):
        return [x.value for x in node.elts if isinstance(x, ast.Constant)]
    if isinstance(node, ast.Tuple):
        return tuple(x.value for x in node.elts if isinstance(x, ast.Constant))
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub) and isinstance(node.operand, ast.Constant):
        return -node.operand.value
    return None


def _literal(node):
    """Render ``node`` as a Python literal when it is fully statically known.

    All-or-nothing for containers: a list whose first element is a variable
    is not renderable, and returning a partial literal would emit a broken
    assertion.
    """
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, (ast.List, ast.Tuple)):
        parts = [_literal(x) for x in node.elts]
        if any(part is None for part in parts):
            return None
        open_, close = ("[", "]") if isinstance(node, ast.List) else ("(", ")")
        inner = ", ".join(parts)
        if isinstance(node, ast.Tuple) and len(parts) == 1:
            inner += ","
        return open_ + inner + close
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub) and isinstance(node.operand, ast.Constant):
        return repr(-node.operand.value)
    return None


def _argument_spec(run_module_node, module_level):
    """Parse the ``argument_spec={...}`` dict from run_module's TencentCloudModule call.

    Falls back to a module-level ``<NAME> = {...}`` assignment when the spec is
    not inlined (``argument_spec=ARGUMENT_SPEC``).
    """
    spec_node = None
    for node in ast.walk(run_module_node):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "TencentCloudModule":
            for keyword in node.keywords:
                if keyword.arg == "argument_spec":
                    spec_node = keyword.value
            if spec_node is not None:
                break
    if isinstance(spec_node, ast.Name):
        for child in module_level.body:
            if isinstance(child, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == spec_node.id for t in child.targets
            ):
                spec_node = child.value
    spec = {}
    if not isinstance(spec_node, ast.Dict):
        return spec
    for key_node, value_node in zip(spec_node.keys, spec_node.values):
        if not isinstance(key_node, ast.Constant):
            continue
        option = {}
        if isinstance(value_node, ast.Dict):
            for okey, ovalue in zip(value_node.keys, value_node.values):
                if not isinstance(okey, ast.Constant):
                    continue
                option[okey.value] = _spec_value(ovalue)
        spec[key_node.value] = option
    return spec


def _loader_names(run_module_node):
    """Names of lazy ``_load_*`` helpers invoked from run_module, in order."""
    names = []
    for node in ast.walk(run_module_node):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id.startswith("_load"):
            if node.func.id not in names:
                names.append(node.func.id)
    return names


def _client_class(run_module_node):
    """Client class name passed to ``create_client`` (e.g. ``ApigatewayClient``)."""
    for node in ast.walk(run_module_node):
        if not isinstance(node, ast.Call) or not (isinstance(node.func, ast.Attribute) and node.func.attr == "create_client"):
            continue
        if node.args and isinstance(node.args[0], ast.Attribute):
            return node.args[0].attr
    return "ServiceClient"


def _operation_calls(tree):
    """Operation names invoked on the client (``client.X`` or ``module.sdk_call(client.X, ...)``)."""
    ops = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if isinstance(func, ast.Attribute) and func.attr == "create_client":
            # create_client(cm.ApigatewayClient, ...) passes a *class* attribute;
            # that is not an SDK operation call.
            continue
        candidates = []
        if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name) and func.value.id in CLIENT_ALIASES:
            candidates.append(func.attr)
        for arg in node.args:
            if isinstance(arg, ast.Attribute) and isinstance(arg.value, ast.Name) and arg.value.id in CLIENT_ALIASES:
                candidates.append(arg.attr)
        for attr in candidates:
            if attr not in ops:
                ops.append(attr)
    return ops


def _has_wrapped_sdk_error(run_module_node):
    """True when run_module has a bare/generic ``except Exception`` handler."""
    for node in ast.walk(run_module_node):
        if not isinstance(node, ast.Try):
            continue
        for handler in node.handlers:
            if handler.type is None:
                return True
            if isinstance(handler.type, ast.Name) and handler.type.id == "Exception":
                return True
    return False


def _module_constraint_kind(run_module_node):
    """Which argument-enforcement constraint run_module declares ("" if none)."""
    for node in ast.walk(run_module_node):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "TencentCloudModule":
            for keyword in node.keywords:
                if keyword.arg in ("required_one_of", "required_together", "mutually_exclusive", "required_if", "required_by"):
                    return keyword.arg
    return ""


def _has_absent_branch(run_module_node):
    for node in ast.walk(run_module_node):
        if isinstance(node, ast.If) and isinstance(node.test, ast.Compare):
            texts = [getattr(c, "value", None) for c in ast.walk(node.test) if isinstance(c, ast.Constant)]
            if "absent" in texts and any(isinstance(c, ast.Constant) and isinstance(c.value, str) for c in ast.walk(node.test)):
                return True
    return False


def _has_check_mode(run_module_node):
    """True when run_module switches on ``module.check_mode`` / ``module._check_mode``.

    Only fires on attribute access through a module-like local name; calls like
    ``params.get("check_mode")`` or helpers reading their own flags never match.
    """
    for node in ast.walk(run_module_node):
        if (
            isinstance(node, ast.Attribute)
            and node.attr in ("check_mode", "_check_mode")
            and isinstance(node.value, ast.Name)
            and node.value.id in ("module", "m", "mod")
        ):
            return True
    return False


def _param_value(name, param):
    """Value placed into ``_params()`` for argument ``name``."""
    if name == "state":
        if param.get("choices"):
            return "present" if "present" in param["choices"] else param["choices"][0]
        return param.get("default", "present")
    if param.get("choices"):
        return param["choices"][0]
    if "default" in param:
        return param["default"]
    if param.get("required") is True:
        return _id_placeholder(name)
    if param.get("type") == "int":
        return 0
    if param.get("type") == "bool":
        return False
    if param.get("type") == "list":
        return []
    return None


def _params_expr(node, spec):
    """Resolve a ``params['key']`` expression against param placeholders."""
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name) and node.value.id in ("p", "params"):
        if isinstance(node.slice, ast.Constant) and isinstance(node.slice.value, str):
            value = _param_value(node.slice.value, spec.get(node.slice.value, {}))
            if value is not None:
                return repr(value)
    return None


def _top_level_assigns(stmts):
    """Assign nodes that are direct children of ``stmts`` (not nested in if/for/try)."""
    found = []
    for stmt in stmts:
        if isinstance(stmt, (ast.If, ast.For, ast.While, ast.Try, ast.With)):
            continue
        if isinstance(stmt, ast.Assign):
            found.append(stmt)
    return found


def _assign_fields(stmt, spec):
    """[(attr, rhs_text, line)] for one ``request.A = x`` / ``request.A, request.B = x, y`` assign."""
    out = []
    targets = stmt.targets[0]
    value = stmt.value
    if isinstance(targets, ast.Attribute) and isinstance(targets.value, ast.Name) and targets.value.id == "request":
        pairs = [(targets.attr, value)]
    elif isinstance(targets, ast.Tuple) and isinstance(value, ast.Tuple) and len(targets.elts) == len(value.elts):
        pairs = [
            (t.attr, v)
            for t, v in zip(targets.elts, value.elts)
            if isinstance(t, ast.Attribute) and isinstance(t.value, ast.Name) and t.value.id == "request"
        ]
    else:
        return out
    for attr, rhs in pairs:
        literal = _literal(rhs)
        if literal is not None:
            out.append((attr, literal, stmt.lineno))
            continue
        resolved = _params_expr(rhs, spec)
        if resolved is not None:
            out.append((attr, resolved, stmt.lineno))
            continue
        if isinstance(rhs, ast.Name) and rhs.id != "request":
            out.append((attr, rhs.id, stmt.lineno))  # resolved against the helper's args at render time
    return out


def analyze(module_name):
    """Analyze ``plugins/modules/<module_name>.py``; returns a payload dict."""
    path = MODULES_DIR / ("%s.py" % module_name)
    if not path.exists():
        raise AnalysisError("no such module: %s" % path)
    try:
        source = path.read_text()
        tree = ast.parse(source)
    except SyntaxError as exc:
        raise AnalysisError("cannot parse %s: %s" % (path, exc))

    functions = [node for node in tree.body if isinstance(node, ast.FunctionDef)]
    run_module_node = next((f for f in functions if f.name == "run_module"), None)
    if run_module_node is None:
        raise AnalysisError("%s has no run_module; only write modules are supported" % module_name)

    spec = _argument_spec(run_module_node, tree)
    loaders = _loader_names(run_module_node)
    if not loaders:
        raise AnalysisError("%s: no lazy _load_* helper found; cannot wire the SDK fixture" % module_name)
    helpers = [
        _analyze_helper(fn, spec)
        for fn in functions
        if fn.name not in ("run_module", "main") and not fn.name.startswith("_load")
    ]
    required_spec = any(option.get("required") is True for option in spec.values())
    constraint = _module_constraint_kind(run_module_node)
    return {
        "name": module_name,
        "path": path,
        "source": source,
        "spec": spec,
        "loaders": _loader_names(run_module_node),
        "client_class": _client_class(run_module_node),
        "ops": _operation_calls(tree),
        "helpers": helpers,
        "has_wrapped_sdk_error": _has_wrapped_sdk_error(run_module_node),
        "has_absent": _has_absent_branch(run_module_node),
        "has_check_mode": _has_check_mode(run_module_node),
        "run_start": run_module_node.lineno,
        "run_end": getattr(run_module_node, "end_lineno", run_module_node.lineno),
        # required-if/by can be satisfied by defaults; only enforcement that
        # always fires on an empty argument set justifies a real test.
        "required_test": required_spec or constraint in ("required_one_of", "required_together", "mutually_exclusive"),
    }


def _analyze_helper(fn, spec):
    """Describe one helper for test emission."""
    info = {
        "name": fn.name,
        "args": [a.arg for a in fn.args.args],
        "line_start": fn.lineno,
        "line_end": getattr(fn, "end_lineno", fn.lineno),
        "is_builder": fn.name.startswith("build"),
        "is_find": fn.name == "find" or fn.name.startswith("find_") or fn.name.startswith("_find"),
        "is_waiter": fn.name.startswith("wait") or fn.name.startswith("_wait"),
        "fields": [],  # [(attr, rhs_or_argname, line)]
    }
    for stmt in _top_level_assigns(fn.body):
        info["fields"].extend(_assign_fields(stmt, spec))
    return info


def _call_argument(name, spec):
    """Expression used when invoking a helper in a generated test."""
    if name == "module":
        return "FakeModule()"
    if name in ("models", "m"):
        return "FakeModels()"
    if name in ("client", "c"):
        return "client"
    if name in ("p", "params"):
        return "_params()"
    if name in spec:
        value = _param_value(name, spec[name])
        if value is not None:
            return repr(value)
    return repr(_id_placeholder(name))


def _sdk_satisfiers(spec):
    """``key=value`` overrides so the SDK-error test clears a module's early gates.

    Every spec option with no statically-known value is a candidate: a plain
    scalar without default/choices is filled with a placeholder so required
    one-of/together checks and body pre-checks (``if not p["name"]``) pass and
    run_module actually reaches the wrapped SDK call. Options with choices or
    list/dict types are skipped -- their placeholders would violate the spec.
    """
    out = []
    for key in sorted(spec):
        if _param_value(key, spec[key]) is not None:
            continue
        if spec[key].get("type") in ("list", "dict"):
            continue
        out.append("%s=%s" % (key, repr(_id_placeholder(key))))
    return out


def _render_helper_tests(info, module_name, alias, spec):
    """Render test functions for one helper."""
    where = "plugins/modules/%s.py:%d-%d" % (module_name, info["line_start"], info["line_end"])
    if info["is_builder"] and info["fields"]:
        call = "%s.%s(%s)" % (
            alias,
            info["name"],
            ", ".join(_call_argument(a, spec) for a in info["args"]),
        )
        lines = ["def test_%s_fields():  # %s" % (info["name"], where)]
        lines.append("    request = %s" % call)
        for attr, rhs, line in info["fields"]:
            if rhs in info["args"]:
                expected = _call_argument(rhs, spec)
                lines.append("    assert request.%s == %s  # module line %d" % (attr, expected, line))
            else:
                lines.append("    assert request.%s == %s  # module line %d" % (attr, rhs, line))
        lines.append("")
        return lines

    # Everything else is wiring we cannot prove from source: the fake store
    # methods are unfinished, so a helper invocation is NOT safe -- find* can
    # crash on the stub response shape and wait* would sleep for the timeout.
    # Emit an xfail stub annotated with the module lines it must exercise.
    kind = "builder" if info["is_builder"] else ("waiter" if info["is_waiter"] else "helper")
    reason = "TODO(human): finish %s %s: assert the module's real contract" % (kind, info["name"])
    lines = ['@pytest.mark.xfail(reason="%s", strict=False)' % reason]
    lines.append("def test_%s_%s(client):  # %s" % (info["name"], kind, where))
    lines.append("    # Seed client.items first, then invoke mod.%s(...) and assert the contract." % info["name"])
    if info["is_waiter"]:
        lines.append("    # Do NOT invoke %s yet: a store that never converges would sleep" % info["name"])
    else:
        lines.append("    # Do not invoke %s yet: it needs a store-backed fake read op." % info["name"])
    lines.append("    pytest.fail(\"unfinished skeleton\")")
    lines.append("")
    return lines


def render(analysis):
    """Render the full skeleton test file for the analyzed module."""
    name = analysis["name"]
    alias = "mod"
    spec = analysis["spec"]
    lines = []
    lines.append(MARKER)
    lines.append('"""Skeleton unit tests for the %s write module (roadmap #57 lever 1).' % name)
    lines.append("")
    lines.append("Generated by scripts/generate_module_test_skeleton.py from a static read of")
    lines.append("``plugins/modules/%s.py``. Assertions that encode the resource's drift rules" % name)
    lines.append("are human work: finish the xfail stubs and the FakeClient store methods,")
    lines.append("then DELETE the marker line so regeneration and CI ``--check`` leave the")
    lines.append("file alone.")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import absolute_import, division, print_function")
    lines.append("")
    lines.append("__metaclass__ = type")
    lines.append("")
    lines.append("from types import SimpleNamespace")
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    lines.append("from ansible_collections.susunola.tencentcloud.plugins.module_utils.base import TencentCloudModule")
    lines.append("from ansible_collections.susunola.tencentcloud.plugins.modules import %s as %s" % (name, alias))
    lines.append("from %s import (" % HARNESS)
    lines.append("    AnsibleFailJson,")
    lines.append("    FakeModels,")
    lines.append("    module_args,")
    lines.append("    run,")
    lines.append(")")
    lines.append("")
    # _params()
    lines.append("def _params(**overrides):")
    lines.append('    """Module parameters pre-filled from the argument spec (base params included)."""')
    lines.append("    params = {")
    entries = []
    for key in sorted(spec):
        # Every spec key is present, even when the value is None: real modules
        # index p["name"] etc. and a missing key would raise KeyError.
        entries.append("        %r: %r," % (key, _param_value(key, spec[key])))
    for key, value in sorted(BASE_PARAMS.items()):
        if key not in spec:
            entries.append("        %r: %r," % (key, value))
    lines.extend(entries)
    lines.append("    }")
    lines.append("    params.update(overrides)")
    lines.append("    return params")
    lines.append("")
    lines.append("")
    lines.append("def _run_args(**extra):")
    lines.append('    """module_args() pre-filled with every module parameter."""')
    lines.append("    args = dict(_params())")
    lines.append("    args.update(extra)")
    lines.append("    return module_args(**args)")
    lines.append("")
    lines.append("")
    # FakeModule
    lines.append("class FakeModule(object):")
    lines.append('    """Minimal stand-in for helpers that need sdk_call / fail_json."""')
    lines.append("")
    lines.append("    def __init__(self, params=None):")
    lines.append("        self.params = params or _params()")
    lines.append("        self.sdk_calls = []")
    lines.append("")
    lines.append("    def sdk_call(self, operation, request):")
    lines.append("        self.sdk_calls.append((operation, request))")
    lines.append("        return operation(request)")
    lines.append("")
    lines.append("    def fail_json(self, **kwargs):")
    lines.append("        raise AnsibleFailJson(kwargs)")
    lines.append("")
    lines.append("")
    # Fake client
    fake_client = "Fake%s" % analysis["client_class"]
    lines.append("class %s(object):" % fake_client)
    lines.append('    """In-memory %s stand-in. TODO(human): give each write op a store' % analysis["client_class"])
    lines.append("    mutation (see tests/unit/plugins/modules/test_ccn_attachment.py for the")
    lines.append('    batch 8-11 pattern) so waiter polls converge on the first retry."""')
    lines.append("")
    lines.append("    def __init__(self, items=None):")
    lines.append("        self.items = [dict(item) for item in (items or [])]")
    lines.append("        self.calls = []")
    lines.append("")
    lines.append("    def _record(self, name, request):")
    lines.append("        self.calls.append((name, request))")
    lines.append("        return request")
    for op in sorted(set(analysis["ops"])):
        lines.append("")
        lines.append("    def %s(self, request):" % op)
        if READ_OP_RE.match(op):
            lines.append('        """TODO(human): return a store-backed page so find*/wait* converge."""')
            lines.append("        self._record(%r, request)" % op)
            lines.append('        return SimpleNamespace(Result=None, RequestId="req-fake")')
        else:
            lines.append('        """TODO(human): mutate self.items from the request fields."""')
            lines.append("        self._record(%r, request)" % op)
            lines.append('        return SimpleNamespace(RequestId="req-fake")')
    lines.append("")
    lines.append("")
    # client fixture
    lines.append("@pytest.fixture")
    lines.append("def client(monkeypatch):")
    lines.append("    fake = %s()" % fake_client)
    lines.append('    monkeypatch.setattr(TencentCloudModule, "require_sdk", lambda self: None)')
    for loader in analysis["loaders"] or ["_load"]:
        lines.append("    monkeypatch.setattr(")
        lines.append("        %s," % alias)
        lines.append("        %r," % loader)
        lines.append("        lambda: (FakeModels(), SimpleNamespace(%s=object))," % analysis["client_class"])
        lines.append("    )")
    lines.append("    monkeypatch.setattr(")
    lines.append("        TencentCloudModule,")
    lines.append('        "create_client",')
    lines.append("        lambda self, client_class, endpoint: fake,")
    lines.append("    )")
    lines.append("    return fake")
    lines.append("")
    lines.append("")
    # helpers
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Helper-level tests")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    for info in analysis["helpers"]:
        lines.extend(_render_helper_tests(info, name, alias, spec))
    # run_module
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# run_module main-path tests")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    if analysis["required_test"]:
        where = "module lines %d-%d" % (analysis["run_start"], analysis["run_end"])
        lines.append("def test_required_arguments_enforced(monkeypatch):  # %s" % where)
        lines.append('    monkeypatch.setattr(TencentCloudModule, "require_sdk", lambda self: None)')
        lines.append("    module_args()")
        lines.append("    with pytest.raises(AnsibleFailJson):")
        lines.append("        run(%s.run_module)" % alias)
        lines.append("")
        lines.append("")
    if analysis["has_wrapped_sdk_error"]:
        where = "module lines %d-%d" % (analysis["run_start"], analysis["run_end"])
        satisfiers = _sdk_satisfiers(spec)
        loaders = analysis["loaders"] or ["_load"]
        loaders_tuple = "(" + ", ".join(repr(x) for x in loaders) + ("," if len(loaders) == 1 else "") + ")"
        lines.append("def test_sdk_error_is_reported(monkeypatch):  # %s" % where)
        lines.append('    monkeypatch.setattr(TencentCloudModule, "require_sdk", lambda self: None)')
        lines.append("    for loader in %s:" % loaders_tuple)
        lines.append("        monkeypatch.setattr(")
        lines.append("            %s," % alias)
        lines.append("            loader,")
        lines.append("            lambda: (FakeModels(), SimpleNamespace(%s=object))," % analysis["client_class"])
        lines.append("        )")
        lines.append('    monkeypatch.setattr(TencentCloudModule, "create_client",')
        lines.append("        lambda self, client_class, endpoint: _BoomClient())")
        if satisfiers:
            lines.append("    # Placeholder values clear the module's early gates (required one-of/")
            lines.append("    # if checks, body pre-checks) so the wrapped SDK error path is reached.")
            lines.append("    _run_args(%s)" % ", ".join(satisfiers))
        else:
            lines.append("    _run_args()")
        lines.append("    with pytest.raises(AnsibleFailJson) as exc:")
        lines.append("        run(%s.run_module)" % alias)
        lines.append("    payload = exc.value.args[0]")
        lines.append('    assert payload["failed"] is True')
        lines.append("")
        lines.append("")
        lines.append("class _BoomClient(object):")
        lines.append('    """Every SDK call raises, so the module\'s wrapped error path is hit."""')
        lines.append("")
        lines.append("    def __getattr__(self, name):")
        lines.append('        def boom(*args, **kwargs):')
        lines.append('            raise RuntimeError("service exploded")')
        lines.append("")
        lines.append("        return boom")
        lines.append("")
        lines.append("")
    # state stubs
    stubs = [("present", "reconcile")]
    if analysis["has_absent"]:
        stubs.append(("absent", "remove"))
    if analysis["has_check_mode"]:
        stubs.append(("check_mode", "dry_run"))
    for state, slug in stubs:
        where = "module lines %d-%d" % (analysis["run_start"], analysis["run_end"])
        reason = "TODO(human): finish the %s %s path: seed the fake store, assert changed/msg/no-write invariants" % (state, slug)
        lines.append('@pytest.mark.xfail(reason="%s", strict=False)' % reason)
        lines.append("def test_run_module_%s_%s(client):  # %s" % (state, slug, where))
        if state == "check_mode":
            lines.append("    _run_args(_ansible_check_mode=True)")
        else:
            lines.append("    _run_args(state=%r)" % state)
        lines.append("    # Wire the store first: seed %s.items, then run and assert" % "client")
        lines.append("    # result[\"changed\"] / result[\"msg\"] and which sdk calls were recorded.")
        lines.append("    pytest.fail(\"unfinished skeleton\")")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _target_path(module_name):
    return TESTS_DIR / ("test_%s.py" % module_name)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--module-test", metavar="MODULE", default=None,
        help="generate a test skeleton for plugins/modules/MODULE.py",
    )
    parser.add_argument(
        "--print", action="store_true",
        help="with --module-test: print the rendered skeleton instead of writing",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="do not write; fail when a committed skeleton (marker still present) drifted",
    )
    args = parser.parse_args(argv)

    if not args.module_test:
        parser.error("--module-test <name> is required")
    name = args.module_test
    try:
        analysis = analyze(name)
    except AnalysisError as exc:
        print("cannot analyze %s: %s" % (name, exc), file=sys.stderr)
        return 1
    rendered = render(analysis)
    target = _target_path(name)

    if args.print:
        sys.stdout.write(rendered)
        return 0

    if target.exists() and MARKER not in target.read_text():
        print("exists and hand-finished: %s (never rewritten)" % target, file=sys.stdout)
        return 0

    if args.check:
        if not target.exists() or target.read_text() != rendered:
            print("stale skeleton: %s (regenerate with --module-test %s)" % (target, name), file=sys.stderr)
            return 1
        print("up to date: %s" % target, file=sys.stdout)
        return 0

    if target.exists() and target.read_text() == rendered:
        print("up to date: %s" % target, file=sys.stdout)
        return 0
    target.write_text(rendered)
    print("wrote skeleton: %s" % target, file=sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
