# -*- coding: utf-8 -*-
"""Generate the product-level capability matrix from collection sources."""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES = ROOT / "plugins" / "modules"
ROLES = ROOT / "roles"
OUTPUT = ROOT / "docs" / "product-capabilities.md"

SDK_SERVICE_RE = re.compile(r"from tencentcloud\.([a-z0-9]+)\.")
SPECIAL_SERVICES = {
    "cos_": "cos",
    "tag": "tag",
}
ROLE_SERVICES = {
    "tc_block_storage": "cbs",
    "tc_autoscaling_group": "autoscaling",
    "tc_container_registry": "tcr",
    "tc_cmq_messaging": "tdmq",
    "tc_kafka_platform": "ckafka",
    "tc_lighthouse_stack": "lighthouse",
    "tc_database_stack": "cdb",
    "tc_dns_zone": "dnspod",
    "tc_cynosdb_cluster": "cynosdb",
    "tc_eventbridge_router": "eb",
    "tc_mongodb_stack": "mongodb",
    "tc_mariadb_stack": "mariadb",
    "tc_mqtt_broker": "mqtt",
    "tc_postgresql_stack": "postgres",
    "tc_private_dns_zone": "privatedns",
    "tc_prometheus_platform": "monitor",
    "tc_rabbitmq_platform": "tdmq",
    "tc_rabbitmq_serverless": "trabbit",
    "tc_redis_stack": "redis",
    "tc_rocketmq_platform": "tdmq",
    "tc_launch": "cvm",
    "tc_clb_http": "clb",
    "tc_alb_application_entry": "alb",
    "tc_api_gateway_platform": "apigateway",
    "tc_config_governance": "config",
    "tc_chdfs_data_lake": "chdfs",
    "tc_cloud_firewall_policy": "cfw",
    "tc_cloudbase_platform": "tcb",
    "tc_elasticsearch_platform": "es",
    "tc_sqlserver_stack": "sqlserver",
    "tc_gwlb_service_chain": "gwlb",
    "tc_organization_governance": "organization",
    "tc_kms_keyring": "kms",
    "tc_direct_connect_fabric": "dc",
    "tc_cdn_delivery": "cdn",
    "tc_goosefs_cache": "goosefs",
    "tc_cloud_audit_governance": "cloudaudit",
    "tc_dts_migration": "dts",
    "tc_dlc_access_governance": "dlc",
    "tc_emr_platform": "emr",
    "tc_gaap_accelerator": "gaap",
    "tc_dcdb_stack": "dcdb",
    "tc_doris_analytics_platform": "cdwdoris",
    "tc_clickhouse_platform": "cdwch",
    "tc_cdwpg_analytics_platform": "cdwpg",
    "tc_oceanus_streaming_platform": "oceanus",
    "tc_observability_baseline": "cls",
    "tc_object_storage_baseline": "cos",
    "tc_serverless_application": "scf",
    "tc_security_baseline": "cam",
    "tc_shared_file_storage": "cfs",
    "tc_tem_application": "tem",
    "tc_edgeone_application": "teo",
    "tc_tke_platform": "tke",
    "tc_tione_ml_pipeline": "tione",
    "tc_tdsql_mysql_platform": "tdmysql",
    "tc_tat_fleet_automation": "tat",
    "tc_ssm_secret_governance": "ssm",
    "tc_vpc_foundation": "vpc",
    "tc_waf_application": "waf",
}


def service_for(name, source):
    """Return the Tencent Cloud service represented by a module."""
    match = SDK_SERVICE_RE.search(source)
    if match:
        return match.group(1)
    for prefix, service in SPECIAL_SERVICES.items():
        if name == prefix or name.startswith(prefix):
            return service
    return name.split("_", 1)[0]


def inventory(modules_dir=MODULES, roles_dir=ROLES):
    """Build deterministic product capability records."""
    products = defaultdict(lambda: {"write": [], "info": [], "roles": []})
    for path in sorted(Path(modules_dir).glob("*.py")):
        if path.name.startswith("__"):
            continue
        name = path.stem
        service = service_for(name, path.read_text(encoding="utf-8"))
        products[service]["info" if name.endswith("_info") else "write"].append(name)

    if Path(roles_dir).exists():
        for path in sorted(Path(roles_dir).iterdir()):
            if not path.is_dir():
                continue
            service = ROLE_SERVICES.get(path.name)
            if service is None:
                role_slug = re.sub(r"[^a-z0-9]", "", path.name.removeprefix("tc_").lower())
                service = next(
                    (candidate for candidate in products
                     if re.sub(r"[^a-z0-9]", "", candidate.lower()) == role_slug),
                    "cross-product",
                )
            products[service]["roles"].append(path.name)
    return dict(products)


def maturity(record):
    """Classify discoverability, manageability and solution packaging."""
    if record["write"] and record["info"] and record["roles"]:
        return "solution"
    if len(record["write"]) >= 3 and record["info"]:
        return "resource-family"
    if record["write"]:
        return "managed"
    if record["info"]:
        return "discovery-only"
    return "role-only"


def render(products):
    total_write = sum(len(value["write"]) for value in products.values())
    total_info = sum(len(value["info"]) for value in products.values())
    total_roles = sum(len(value["roles"]) for value in products.values())
    lines = [
        "# Product capability matrix\n",
        "<!-- Generated by scripts/generate_product_capabilities.py; do not edit. -->\n",
        "This matrix is generated from module SDK imports and role metadata. It is a",
        "navigation and gap-discovery aid, not a claim that every Tencent Cloud API is covered.\n",
        "- Products/services: **%d**" % len(products),
        "- Write modules: **%d**" % total_write,
        "- Information modules: **%d**" % total_info,
        "- Solution roles: **%d**\n" % total_roles,
        "Maturity meanings: `discovery-only` can read resources; `managed` has write",
        "operations; `resource-family` has at least three write modules plus discovery;",
        "`solution` also has a reusable role.\n",
        "| Product | Maturity | Write | Info | Roles | Resource modules |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    for service, record in sorted(products.items()):
        names = record["write"]
        preview = ", ".join("`%s`" % value for value in names[:8])
        if len(names) > 8:
            preview += ", +%d more" % (len(names) - 8)
        roles = ", ".join("`%s`" % value for value in record["roles"]) or "—"
        lines.append(
            "| `%s` | %s | %d | %d | %s | %s |"
            % (service, maturity(record), len(record["write"]), len(record["info"]), roles, preview or "—")
        )
    lines.extend([
        "\n## How to use this matrix\n",
        "Prioritize frequently used `discovery-only` products for their first write module,",
        "then deepen `managed` products into coherent resource families. Add a role only when",
        "the underlying modules can deliver a repeatable end-to-end outcome.",
    ])
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rendered = render(inventory())
    if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == rendered:
        print("up to date: %s" % OUTPUT)
        return 0
    if args.check:
        print("product capability matrix is stale; run scripts/generate_product_capabilities.py", file=sys.stderr)
        return 1
    OUTPUT.write_text(rendered, encoding="utf-8")
    print("wrote: %s" % OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
