#!/usr/bin/env python
"""Materialise non-secret integration inputs where ``ansible-test`` can see them.

``ansible-test`` rebuilds the environment from scratch before it spawns
``ansible-playbook`` (see ``docs/integration-env.md`` 2.3), so every
``TENCENTCLOUD_*`` variable is gone by the time a target evaluates
``lookup('env', ...)``. Credentials get their own escape hatch
(``scripts/integration_credentials.py`` writes a TCCLI profile). This script is
the same trick for everything else - target gates, region/zone overrides,
resource ids, ``GITHUB_RUN_ID`` - by writing them to a small YAML file under
``$HOME``, which is one of the few variables that does survive.

Usage (locally and in CI, before ``ansible-test integration``)::

    python scripts/integration_inputs.py --write
    python scripts/integration_inputs.py --check     # exit 1 when absent

Targets read it with::

    e2e_inputs: >-
      {{ lookup('ansible.builtin.file', lookup('env', 'HOME')
         ~ '/.tencentcloud/e2e_inputs.yml', errors='ignore')
         | default('', true) | from_yaml | default({}, true) }}
    region: "{{ e2e_inputs.TENCENTCLOUD_REGION
                | default(lookup('env', 'TENCENTCLOUD_REGION'), true)
                | default('ap-guangzhou', true) }}"

Secrets belong in the credential profile, not here, so the key pair and the STS
token are never copied into this file even when they are exported.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

import yaml

PROFILE_DIR = ".tencentcloud"
FILE_NAME = "e2e_inputs.yml"

# Credentials are handled by scripts/integration_credentials.py and must never
# be duplicated into this file.
EXCLUDED_KEYS = frozenset({
    "TENCENTCLOUD_SECRET_ID",
    "TENCENTCLOUD_SECRET_KEY",
    "TENCENTCLOUD_TOKEN",
})

# Everything that targets read via lookup('env', ...) today.
PREFIXES = ("TENCENTCLOUD_",)
EXTRA_KEYS = ("GITHUB_RUN_ID",)

# Values that must not be echoed by --check / --dry-run.
SECRET_MARKERS = ("TOKEN", "SECRET", "PASSWORD", "KEY")


def inputs_path(home=None) -> Path:
    """Absolute path of the inputs file for ``home`` (default ``$HOME``)."""
    base = Path(home) if home else Path(os.environ.get("HOME", str(Path.home())))
    return base / PROFILE_DIR / FILE_NAME


def collect(env=None) -> dict:
    """Return the inputs present in ``env`` (default ``os.environ``)."""
    source = os.environ if env is None else env
    values = {}
    for key, value in source.items():
        if key in EXCLUDED_KEYS:
            continue
        if value == "":
            continue
        if key in EXTRA_KEYS or key.startswith(PREFIXES):
            values[key] = value
    return dict(sorted(values.items()))


def render(values) -> str:
    """Render ``values`` as the YAML document written to the inputs file."""
    header = [
        "# Generated by scripts/integration_inputs.py - do not edit by hand.",
        "# ansible-test strips TENCENTCLOUD_* from the environment, so integration",
        "# targets read their inputs back from this file (see docs/integration-env.md).",
    ]
    body = yaml.safe_dump(values or {}, default_flow_style=False, sort_keys=True).strip()
    return "\n".join(header + [body]) + "\n"


def masked(values) -> dict:
    """Return ``values`` with anything secret-looking shortened to its length."""
    out = {}
    for key, value in values.items():
        if any(marker in key for marker in SECRET_MARKERS):
            out[key] = "%s…(%d chars)" % (value[:4], len(value))
        else:
            out[key] = value
    return out


def write(values, home=None) -> Path:
    """Write ``values`` to the inputs file (mode 0600) and return its path."""
    path = inputs_path(home)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(values), encoding="utf-8")
    path.chmod(0o600)
    return path


def read(home=None) -> dict:
    """Return the inputs file contents, or ``{}`` when it does not exist."""
    path = inputs_path(home)
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def check(home=None) -> tuple:
    """Return ``(ok, path, values)`` for the inputs file."""
    path = inputs_path(home)
    if not path.exists():
        return False, path, {}
    return True, path, read(home)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--home", help="Home directory to write under (default $HOME)")
    parser.add_argument("--region", help="Set TENCENTCLOUD_REGION for this run")
    parser.add_argument("--write", action="store_true", help="Write the inputs file (default)")
    parser.add_argument("--check", action="store_true", help="Verify the file exists; exit 1 when it does not")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written, write nothing")
    args = parser.parse_args(argv)

    values = collect()
    if args.region:
        values["TENCENTCLOUD_REGION"] = args.region
        values = dict(sorted(values.items()))

    if args.dry_run:
        print("would write %s" % inputs_path(args.home))
        for key, value in masked(values).items():
            print("  %s=%s" % (key, value))
        return 0

    if args.check:
        ok, path, current = check(args.home)
        if not ok:
            print("missing: %s" % path)
            return 1
        print("ok: %s" % path)
        for key, value in masked(current).items():
            print("  %s=%s" % (key, value))
        return 0

    path = write(values, args.home)
    print("wrote %s (%d key(s))" % (path, len(values)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
