# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.susunola.tencentcloud.plugins.modules import tdcpg_cluster_instance_info


class FakeFilter:
    pass


class FakeRequest:
    pass


class FakeModels:
    Filter = FakeFilter
    DescribeClusterInstancesRequest = FakeRequest


def test_build_request_sets_pagination():
    request = tdcpg_cluster_instance_info.build_request(FakeModels, "sample", {}, 200, 100)
    assert request.PageNumber == 3
    assert request.PageSize == 100


def test_build_request_sorts_filters():
    request = tdcpg_cluster_instance_info.build_request(FakeModels, "sample", {"b-name": ["v1"], "a-name": ["v2"]}, 0, 100)
    assert [(item.Name, item.Values) for item in request.Filters] == [
        ("a-name", ["v2"]), ("b-name", ["v1"]),
    ]


class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {"Marker": self.marker}


class FakeResponse:
    def __init__(self, items, total_count):
        self.InstanceSet = items
        self.TotalCount = total_count
        self.RequestId = "req-page"


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def DescribeClusterInstances(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        raise AssertionError("fail_json called: %r" % (kwargs,))


def _run(monkeypatch, client, **params):
    service = types.ModuleType("tencentcloud.tdcpg.v20211118")
    service.models = FakeModels
    service.tdcpg_client = types.SimpleNamespace(TdcpgClient=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.tdcpg",
                        types.ModuleType("tencentcloud.tdcpg"))
    monkeypatch.setitem(sys.modules, "tencentcloud.tdcpg.v20211118", service)
    fake = FakeModule(params)
    monkeypatch.setattr(tdcpg_cluster_instance_info, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr(tdcpg_cluster_instance_info, "create_credential", lambda module: object())
    monkeypatch.setattr(tdcpg_cluster_instance_info, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        tdcpg_cluster_instance_info.run_module()
    return fake


def test_run_module_paginates_until_total_count(monkeypatch):
    client = FakeClient([
        FakeResponse([FakeItem("a"), FakeItem("b")], 3),
        FakeResponse([FakeItem("c")], 3),
    ])
    fake = _run(monkeypatch, client, region="ap-guangzhou",
                cluster_id="sample", filters={}, page_size=2)
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["cluster_instances"]] == ["a", "b", "c"]
    assert payload["total_count"] == 3
    assert payload["request_id"] == "req-page"
    assert [request.PageNumber for request in client.requests] == [1, 2]
