# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.susunola.tencentcloud.plugins.modules import dcdb_security_config_info


class FakeRequest:
    pass


class FakeModels:
    DescribeDBSecurityGroupsRequest = FakeRequest


class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {"Marker": self.marker}


class FakeResponse:
    def __init__(self, items):
        self.Groups = items
        self.RequestId = "req-list"


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def DescribeDBSecurityGroups(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class ModuleFail(Exception):
    def __init__(self, payload):
        self.payload = payload
        super(ModuleFail, self).__init__("module failed: %r" % (payload,))


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None
        self.fail_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        self.fail_payload = kwargs
        raise ModuleFail(kwargs)


def _inject_sdk(monkeypatch, client):
    service = types.ModuleType("tencentcloud.dcdb.v20180411")
    service.models = FakeModels
    service.dcdb_client = types.SimpleNamespace(DcdbClient=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.dcdb",
                        types.ModuleType("tencentcloud.dcdb"))
    monkeypatch.setitem(sys.modules, "tencentcloud.dcdb.v20180411", service)


def _run(monkeypatch, client, **params):
    _inject_sdk(monkeypatch, client)
    fake = FakeModule(params)
    monkeypatch.setattr(dcdb_security_config_info, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr(dcdb_security_config_info, "create_credential", lambda module: object())
    monkeypatch.setattr(dcdb_security_config_info, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        dcdb_security_config_info.run_module()
    return fake


def test_run_module_returns_full_list(monkeypatch):
    client = FakeClient([FakeResponse([FakeItem("a"), FakeItem("b")])])
    fake = _run(monkeypatch, client, region="ap-guangzhou", product="sample", instance_id="sample")
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["db_security_groups"]] == ["a", "b"]
    assert payload["total_count"] == 2
    assert payload["request_id"] == "req-list"
    assert len(client.requests) == 1


def test_run_module_fails_cleanly_on_sdk_error(monkeypatch):
    class FailingClient:
        def DescribeDBSecurityGroups(self, request):
            raise RuntimeError("api exploded")

    def failing_sdk_call(module, function, request):
        # Mirrors the real sdk_call failure contract pinned in
        # tests/unit/plugins/module_utils/test_tencentcloud.py.
        try:
            return function(request)
        except RuntimeError as exc:
            module.fail_json(
                msg="Tencent Cloud API request failed",
                error=str(exc),
                error_code="UnauthorizedOperation",
                request_id="req-err",
            )

    _inject_sdk(monkeypatch, FailingClient())
    fake = FakeModule({"region": "ap-guangzhou", "product": "sample", "instance_id": "sample"})
    monkeypatch.setattr(dcdb_security_config_info, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr(dcdb_security_config_info, "create_credential", lambda module: object())
    monkeypatch.setattr(dcdb_security_config_info, "create_client_profile", lambda module, endpoint: object())
    monkeypatch.setattr(dcdb_security_config_info, "sdk_call", failing_sdk_call)
    with pytest.raises(ModuleFail) as excinfo:
        dcdb_security_config_info.run_module()
    payload = excinfo.value.payload
    assert payload["msg"] == "Tencent Cloud API request failed"
    assert payload["error_code"] == "UnauthorizedOperation"
    assert payload["request_id"] == "req-err"
