# Skeleton generated by scripts/generate_module_test_skeleton.py -- delete this line when you start hand-finishing.
"""Skeleton unit tests for the api_gateway_api_key write module (roadmap #57 lever 1).

Generated by scripts/generate_module_test_skeleton.py from a static read of
``plugins/modules/api_gateway_api_key.py``. Assertions that encode the resource's drift rules
are human work: finish the xfail stubs and the FakeClient store methods,
then DELETE the marker line so regeneration and CI ``--check`` leave the
file alone.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

from types import SimpleNamespace

import pytest

from ansible_collections.susunola.tencentcloud.plugins.module_utils.base import TencentCloudModule
from ansible_collections.susunola.tencentcloud.plugins.modules import api_gateway_api_key as mod
from ansible_collections.susunola.tencentcloud.tests.unit.plugins.modules.harness import (
    AnsibleFailJson,
    FakeModels,
    module_args,
    run,
)


def _params(**overrides):
    """Module parameters pre-filled from the argument spec (base params included)."""
    params = {
        'access_key_id': None,
        'access_key_secret': None,
        'key_type': 'auto',
        'name': None,
        'state': 'present',
        'retries': 5,
        'waiter_delay': 5,
        'waiter_timeout': 120,
    }
    params.update(overrides)
    return params


def _run_args(**extra):
    """module_args() pre-filled with every module parameter."""
    args = dict(_params())
    args.update(extra)
    return module_args(**args)


class FakeModule(object):
    """Minimal stand-in for helpers that need sdk_call / fail_json."""

    def __init__(self, params=None):
        self.params = params or _params()
        self.sdk_calls = []

    def sdk_call(self, operation, request):
        self.sdk_calls.append((operation, request))
        return operation(request)

    def fail_json(self, **kwargs):
        raise AnsibleFailJson(kwargs)


class FakeApigatewayClient(object):
    """In-memory ApigatewayClient stand-in. TODO(human): give each write op a store
    mutation (see tests/unit/plugins/modules/test_ccn_attachment.py for the
    batch 8-11 pattern) so waiter polls converge on the first retry."""

    def __init__(self, items=None):
        self.items = [dict(item) for item in (items or [])]
        self.calls = []

    def _record(self, name, request):
        self.calls.append((name, request))
        return request

    def CreateApiKey(self, request):
        """TODO(human): mutate self.items from the request fields."""
        self._record('CreateApiKey', request)
        return SimpleNamespace(RequestId="req-fake")

    def DeleteApiKey(self, request):
        """TODO(human): mutate self.items from the request fields."""
        self._record('DeleteApiKey', request)
        return SimpleNamespace(RequestId="req-fake")

    def DescribeApiKey(self, request):
        """TODO(human): return a store-backed page so find*/wait* converge."""
        self._record('DescribeApiKey', request)
        return SimpleNamespace(Result=None, RequestId="req-fake")

    def DescribeApiKeysStatus(self, request):
        """TODO(human): return a store-backed page so find*/wait* converge."""
        self._record('DescribeApiKeysStatus', request)
        return SimpleNamespace(Result=None, RequestId="req-fake")

    def UpdateApiKey(self, request):
        """TODO(human): mutate self.items from the request fields."""
        self._record('UpdateApiKey', request)
        return SimpleNamespace(RequestId="req-fake")


@pytest.fixture
def client(monkeypatch):
    fake = FakeApigatewayClient()
    monkeypatch.setattr(TencentCloudModule, "require_sdk", lambda self: None)
    monkeypatch.setattr(
        mod,
        '_load',
        lambda: (FakeModels(), SimpleNamespace(ApigatewayClient=object)),
    )
    monkeypatch.setattr(
        TencentCloudModule,
        "create_client",
        lambda self, client_class, endpoint: fake,
    )
    return fake


# ---------------------------------------------------------------------------
# Helper-level tests
# ---------------------------------------------------------------------------


def test_build_get_fields():  # plugins/modules/api_gateway_api_key.py:48-51
    request = mod.build_get(FakeModels(), 'key-xxxx')
    assert request.AccessKeyId == 'key-xxxx'  # module line 50


def test_build_list_fields():  # plugins/modules/api_gateway_api_key.py:54-61
    request = mod.build_list(FakeModels(), 'name-xxxx')
    assert request.Offset == 0  # module line 56
    assert request.Limit == 100  # module line 56


def test_build_create_fields():  # plugins/modules/api_gateway_api_key.py:64-69
    request = mod.build_create(FakeModels(), _params())
    assert request.AccessKeyType == 'auto'  # module line 66


def test_build_update_fields():  # plugins/modules/api_gateway_api_key.py:72-75
    request = mod.build_update(FakeModels(), 'key-xxxx', 'secret-xxxx')
    assert request.AccessKeyId == 'key-xxxx'  # module line 74
    assert request.AccessKeySecret == 'secret-xxxx'  # module line 74


def test_build_delete_fields():  # plugins/modules/api_gateway_api_key.py:78-81
    request = mod.build_delete(FakeModels(), 'key-xxxx')
    assert request.AccessKeyId == 'key-xxxx'  # module line 80


@pytest.mark.xfail(reason="TODO(human): finish helper safe: assert the module's real contract", strict=False)
def test_safe_helper(client):  # plugins/modules/api_gateway_api_key.py:84-89
    # Seed client.items first, then invoke mod.safe(...) and assert the contract.
    # Do not invoke safe yet: it needs a store-backed fake read op.
    pytest.fail("unfinished skeleton")


@pytest.mark.xfail(reason="TODO(human): finish helper find: assert the module's real contract", strict=False)
def test_find_helper(client):  # plugins/modules/api_gateway_api_key.py:92-105
    # Seed client.items first, then invoke mod.find(...) and assert the contract.
    # Do not invoke find yet: it needs a store-backed fake read op.
    pytest.fail("unfinished skeleton")

# ---------------------------------------------------------------------------
# run_module main-path tests
# ---------------------------------------------------------------------------


def test_required_arguments_enforced(monkeypatch):  # module lines 108-150
    monkeypatch.setattr(TencentCloudModule, "require_sdk", lambda self: None)
    module_args()
    with pytest.raises(AnsibleFailJson):
        run(mod.run_module)


def test_sdk_error_is_reported(monkeypatch):  # module lines 108-150
    monkeypatch.setattr(TencentCloudModule, "require_sdk", lambda self: None)
    for loader in ('_load',):
        monkeypatch.setattr(
            mod,
            loader,
            lambda: (FakeModels(), SimpleNamespace(ApigatewayClient=object)),
        )
    monkeypatch.setattr(
        TencentCloudModule,
        "create_client",
        lambda self, client_class, endpoint: _BoomClient(),
    )
    # Placeholder values clear the module's early gates (required one-of/
    # if checks, body pre-checks) so the wrapped SDK error path is reached.
    _run_args(access_key_id='access-key-xxxx', access_key_secret='access-key-secret-xxxx', name='name-xxxx')
    with pytest.raises(AnsibleFailJson) as exc:
        run(mod.run_module)
    payload = exc.value.args[0]
    assert payload["failed"] is True


class _BoomClient(object):
    """Every SDK call raises, so the module's wrapped error path is hit."""

    def __getattr__(self, name):
        def boom(*args, **kwargs):
            raise RuntimeError("service exploded")

        return boom


@pytest.mark.xfail(reason="TODO(human): finish the present reconcile path: seed the fake store, assert changed/msg/no-write invariants", strict=False)
def test_run_module_present_reconcile(client):  # module lines 108-150
    _run_args(state='present')
    # Wire the store first: seed client.items, then run and assert
    # result["changed"] / result["msg"] and which sdk calls were recorded.
    pytest.fail("unfinished skeleton")


@pytest.mark.xfail(reason="TODO(human): finish the absent remove path: seed the fake store, assert changed/msg/no-write invariants", strict=False)
def test_run_module_absent_remove(client):  # module lines 108-150
    _run_args(state='absent')
    # Wire the store first: seed client.items, then run and assert
    # result["changed"] / result["msg"] and which sdk calls were recorded.
    pytest.fail("unfinished skeleton")


@pytest.mark.xfail(reason="TODO(human): finish the check_mode dry_run path: seed the fake store, assert changed/msg/no-write invariants", strict=False)
def test_run_module_check_mode_dry_run(client):  # module lines 108-150
    _run_args(_ansible_check_mode=True)
    # Wire the store first: seed client.items, then run and assert
    # result["changed"] / result["msg"] and which sdk calls were recorded.
    pytest.fail("unfinished skeleton")
