# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.susunola.tencentcloud.plugins.modules import acp_scan_task_info


class FakeRequest:
    pass


class FakeModels:
    DescribeScanTaskListRequest = FakeRequest


def test_build_request_sets_pagination():
    request = acp_scan_task_info.build_request(FakeModels, 200, 100)
    assert request.PageNo == 3
    assert request.PageSize == 100


class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {"Marker": self.marker}


class FakeResponse:
    def __init__(self, items, total_count):
        self.Data = items
        self.Total = total_count


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def DescribeScanTaskList(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        raise AssertionError("fail_json called: %r" % (kwargs,))


def _run(monkeypatch, client, **params):
    service = types.ModuleType("tencentcloud.acp.v20220105")
    service.models = FakeModels
    service.acp_client = types.SimpleNamespace(AcpClient=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.acp",
                        types.ModuleType("tencentcloud.acp"))
    monkeypatch.setitem(sys.modules, "tencentcloud.acp.v20220105", service)
    fake = FakeModule(params)
    monkeypatch.setattr(acp_scan_task_info, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr(acp_scan_task_info, "create_credential", lambda module: object())
    monkeypatch.setattr(acp_scan_task_info, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        acp_scan_task_info.run_module()
    return fake


def test_run_module_paginates_until_total_count(monkeypatch):
    client = FakeClient([
        FakeResponse([FakeItem("a"), FakeItem("b")], 3),
        FakeResponse([FakeItem("c")], 3),
    ])
    fake = _run(monkeypatch, client, region="ap-guangzhou",
                page_size=2)
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["scan_tasks"]] == ["a", "b", "c"]
    assert payload["total_count"] == 3
    assert [request.PageNo for request in client.requests] == [1, 2]
