# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.tencentcloud.cloud.plugins.modules import lowcode_knowledge_set_info


class FakeRequest:
    pass


class FakeModels:
    DescribeKnowledgeSetListRequest = FakeRequest


def test_build_request_sets_pagination():
    request = lowcode_knowledge_set_info.build_request(FakeModels, "sample", 200, 100)
    assert request.Offset == 200
    assert request.Limit == 100


class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {"Marker": self.marker}


class FakeResponse:
    def __init__(self, items, total_count):
        self.Data = types.SimpleNamespace(KnowledgeSets=items, Total=total_count)


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def DescribeKnowledgeSetList(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        raise AssertionError("fail_json called: %r" % (kwargs,))


def _run(monkeypatch, client, **params):
    service = types.ModuleType("tencentcloud.lowcode.v20210108")
    service.models = FakeModels
    service.lowcode_client = types.SimpleNamespace(LowcodeClient=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.lowcode",
                        types.ModuleType("tencentcloud.lowcode"))
    monkeypatch.setitem(sys.modules, "tencentcloud.lowcode.v20210108", service)
    fake = FakeModule(params)
    monkeypatch.setattr(lowcode_knowledge_set_info, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr(lowcode_knowledge_set_info, "create_credential", lambda module: object())
    monkeypatch.setattr(lowcode_knowledge_set_info, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        lowcode_knowledge_set_info.run_module()
    return fake


def test_run_module_paginates_until_total_count(monkeypatch):
    client = FakeClient([
        FakeResponse([FakeItem("a"), FakeItem("b")], 3),
        FakeResponse([FakeItem("c")], 3),
    ])
    fake = _run(monkeypatch, client, region="ap-guangzhou",
                env_id="sample", page_size=2)
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["knowledge_sets"]] == ["a", "b", "c"]
    assert payload["total_count"] == 3
    assert [request.Offset for request in client.requests] == [0, 2]
