# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
from __future__ import absolute_import, division, print_function

__metaclass__ = type

import sys
import types

import pytest

from ansible_collections.susunola.tencentcloud.plugins.modules import cloudstudio_image_info


class FakeRequest:
    pass


class FakeModels:
    DescribeImagesRequest = FakeRequest


class FakeItem:
    def __init__(self, marker):
        self.marker = marker

    def _serialize(self, allow_none=True):
        return {"Marker": self.marker}


class FakeResponse:
    def __init__(self, items):
        self.Images = items


class FakeClient:
    def __init__(self, pages):
        self._pages = list(pages)
        self.requests = []

    def DescribeImages(self, request):
        self.requests.append(request)
        return self._pages.pop(0)


class ModuleExit(Exception):
    pass


class FakeModule:
    def __init__(self, params):
        self.params = params
        self.exit_payload = None

    def exit_json(self, **kwargs):
        self.exit_payload = kwargs
        raise ModuleExit()

    def fail_json(self, **kwargs):
        raise AssertionError("fail_json called: %r" % (kwargs,))


def _run(monkeypatch, client, **params):
    service = types.ModuleType("tencentcloud.cloudstudio.v20230508")
    service.models = FakeModels
    service.cloudstudio_client = types.SimpleNamespace(CloudstudioClient=lambda *args: client)
    monkeypatch.setitem(sys.modules, "tencentcloud", types.ModuleType("tencentcloud"))
    monkeypatch.setitem(sys.modules, "tencentcloud.cloudstudio",
                        types.ModuleType("tencentcloud.cloudstudio"))
    monkeypatch.setitem(sys.modules, "tencentcloud.cloudstudio.v20230508", service)
    fake = FakeModule(params)
    monkeypatch.setattr(cloudstudio_image_info, "AnsibleModule", lambda **kwargs: fake)
    monkeypatch.setattr(cloudstudio_image_info, "create_credential", lambda module: object())
    monkeypatch.setattr(cloudstudio_image_info, "create_client_profile", lambda module, endpoint: object())
    with pytest.raises(ModuleExit):
        cloudstudio_image_info.run_module()
    return fake


def test_run_module_returns_full_list(monkeypatch):
    client = FakeClient([FakeResponse([FakeItem("a"), FakeItem("b")])])
    fake = _run(monkeypatch, client, region="ap-guangzhou")
    payload = fake.exit_payload
    assert payload["changed"] is False
    assert [item["Marker"] for item in payload["images"]] == ["a", "b"]
    assert payload["total_count"] == 2
    assert len(client.requests) == 1
