#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: adp_agent_release_preview_info
short_description: Gather information about Tencent Cloud ADP agent release previews
version_added: "0.8.0"
description: Returns ADP agent release previews visible in a Tencent Cloud region.
options:
  app_id:
    description: Application ID.
    type: str
    required: true
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List agent release previews
  tencentcloud.cloud.adp_agent_release_preview_info:
    region: ap-guangzhou
    app_id: "204000000016"
'''

RETURN = r'''
agent_release_previews:
  description: Matching ADP agent release previews.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of agent release previews reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, app_id, offset, limit):
    request = models.DescribeAgentReleasePreviewListRequest()
    request.PageNumber = offset // limit + 1
    request.PageSize = limit
    request.AppId = app_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "app_id": {"type": "str", "required": True},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.adp.v20260520 import models, adp_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-adp package is required.")

    client = adp_client.AdpClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "adp.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["app_id"], offset, limit),
        lambda request: sdk_call(module, client.DescribeAgentReleasePreviewList, request),
        lambda response: response.ReleaseList,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    agent_release_previews = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, agent_release_previews=agent_release_previews, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
