#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: alb_load_balancer_info
short_description: Gather information about Tencent Cloud ALB instances
version_added: "1.1.0"
description: Returns ALB (Application Load Balancer) instances visible in a Tencent Cloud region.
options:
  filters:
    description: ALB API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all ALB instances
  susunola.tencentcloud.alb_load_balancer_info:
    region: ap-guangzhou
'''

RETURN = r'''
load_balancers:
  description: Matching ALB instances.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of load balancers reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, filters, next_token, max_results):
    request = models.DescribeLoadBalancersRequest()
    request.MaxResults = max_results
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    if next_token:
        request.NextToken = next_token
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.alb.v20251030 import models, alb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-alb package is required.")

    client = alb_client.AlbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "alb.tencentcloudapi.com"),
    )
    load_balancers = []
    next_token = None
    total_count = None
    while True:
        request = build_request(
            models,
            module.params["filters"],
            next_token,
            module.params["page_size"])
        response = sdk_call(module, client.DescribeLoadBalancers, request)
        batch = response.LoadBalancers or []
        load_balancers.extend(serialize_sdk_object(item) for item in batch)
        if total_count is None and response.TotalCount is not None:
            total_count = response.TotalCount
        next_token = response.NextToken
        if response.ListOver or not next_token:
            break
    if total_count is None:
        total_count = len(load_balancers)
    request_id = getattr(response, "RequestId", None)
    module.exit_json(changed=False, load_balancers=load_balancers,
                     total_count=total_count, request_id=request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
