#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: apm_general_span_info
short_description: Gather information about Tencent Cloud APM general spans
version_added: "0.8.0"
description: Returns APM general spans visible in a Tencent Cloud region.
options:
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all general spans
  tencentcloud.cloud.apm_general_span_info:
    region: ap-guangzhou
'''

RETURN = r'''
general_spans:
  description: Matching APM general spans.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of general spans reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    request = models.DescribeGeneralSpanListRequest()
    request.Offset = offset
    request.Limit = limit
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.apm.v20210622 import models, apm_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-apm package is required.")

    client = apm_client.ApmClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "apm.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, offset, limit),
        lambda request: sdk_call(module, client.DescribeGeneralSpanList, request),
        lambda response: response.Spans,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    general_spans = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, general_spans=general_spans, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
