#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: as_scaling_group_info
short_description: Gather information about Tencent Cloud auto scaling groups
version_added: "0.6.0"
description: Returns auto scaling groups visible in a Tencent Cloud region.
options:
  auto_scaling_group_ids:
    description: Auto scaling group IDs to return. Mutually exclusive with O(filters).
    type: list
    elements: str
  filters:
    description: Auto Scaling API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all auto scaling groups
  tencentcloud.cloud.as_scaling_group_info:
    region: ap-guangzhou

- name: Find auto scaling groups by ID
  tencentcloud.cloud.as_scaling_group_info:
    region: ap-guangzhou
    auto_scaling_group_ids: [asg-xxxxxxxx]
'''

RETURN = r'''
scaling_groups:
  description: Matching auto scaling groups.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of auto scaling groups reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, auto_scaling_group_ids, filters, offset, limit):
    request = models.DescribeAutoScalingGroupsRequest()
    request.Offset = offset
    request.Limit = limit
    if auto_scaling_group_ids:
        request.AutoScalingGroupIds = auto_scaling_group_ids
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "auto_scaling_group_ids": {"type": "list", "elements": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        mutually_exclusive=[("auto_scaling_group_ids", "filters")],
        supports_check_mode=True,
    )
    try:
        from tencentcloud.autoscaling.v20180419 import models, autoscaling_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-autoscaling package is required.")

    client = autoscaling_client.AutoscalingClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "as.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["auto_scaling_group_ids"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeAutoScalingGroups, request),
        lambda response: response.AutoScalingGroupSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    scaling_groups = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, scaling_groups=scaling_groups, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
