#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: bdrc_backup_vault_info
short_description: Gather information about Tencent Cloud BDRC backup vaults
version_added: "0.8.0"
description: Returns BDRC backup vaults visible in a Tencent Cloud region.
options:
  backup_vault_ids:
    description: Backup vault IDs to return. Mutually exclusive with O(filters).
    type: list
    elements: str
  filters:
    description: BDRC API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all backup vaults
  tencentcloud.cloud.bdrc_backup_vault_info:
    region: ap-guangzhou

- name: Find backup vaults by ID
  tencentcloud.cloud.bdrc_backup_vault_info:
    region: ap-guangzhou
    backup_vault_ids: [x-xxxxxxxx]
'''

RETURN = r'''
backup_vaults:
  description: Matching BDRC backup vaults.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of backup vaults reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, backup_vault_ids, filters, offset, limit):
    request = models.DescribeBackupVaultsRequest()
    request.Offset = offset
    request.Limit = limit
    if backup_vault_ids:
        request.VaultIds = backup_vault_ids
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.FilterModel()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "backup_vault_ids": {"type": "list", "elements": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        mutually_exclusive=[("backup_vault_ids", "filters")],
        supports_check_mode=True,
    )
    try:
        from tencentcloud.bdrc.v20260330 import models, bdrc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-bdrc package is required.")

    client = bdrc_client.BdrcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "bdrc.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["backup_vault_ids"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeBackupVaults, request),
        lambda response: response.BackupVaultSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    backup_vaults = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, backup_vaults=backup_vaults, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
