#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: bizlive_worker_info
short_description: Gather information about Tencent Cloud BIZLIVE workers
version_added: "0.9.0"
description: Returns BIZLIVE workers visible in a Tencent Cloud region.
options: {}
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all workers
  susunola.tencentcloud.bizlive_worker_info:
    region: ap-guangzhou
'''

RETURN = r'''
workers:
  description: Matching BIZLIVE workers.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of workers returned (the API reports no total count).
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    # DescribeWorkers returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeWorkersRequest()
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({})
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.bizlive.v20190313 import models, bizlive_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-bizlive package is required.")

    client = bizlive_client.BizliveClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "bizlive.tencentcloudapi.com"),
    )
    request = build_request(models, 0, 0)
    response = sdk_call(module, client.DescribeWorkers, request)
    items = response.RegionDetail or []
    workers = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, workers=workers,
                     total_count=len(workers))


def main():
    run_module()


if __name__ == "__main__":
    main()
