#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: bmeip_eip_acl_info
short_description: Gather information about Tencent Cloud BMEIP eip acls
version_added: "0.8.0"
description: Returns BMEIP eip acls visible in a Tencent Cloud region.
options:
  eip_acl_ids:
    description: Eip acl IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all eip acls
  susunola.tencentcloud.bmeip_eip_acl_info:
    region: ap-guangzhou

- name: Find eip acls by ID
  susunola.tencentcloud.bmeip_eip_acl_info:
    region: ap-guangzhou
    eip_acl_ids: [x-xxxxxxxx]
'''

RETURN = r'''
eip_acls:
  description: Matching BMEIP eip acls.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of eip acls reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, eip_acl_ids, offset, limit):
    request = models.DescribeEipAclsRequest()
    request.Offset = offset
    request.Limit = limit
    if eip_acl_ids:
        request.AclIds = eip_acl_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "eip_acl_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.bmeip.v20180625 import models, bmeip_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-bmeip package is required.")

    client = bmeip_client.BmeipClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "bmeip.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["eip_acl_ids"], offset, limit),
        lambda request: sdk_call(module, client.DescribeEipAcls, request),
        lambda response: response.EipAclList,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    eip_acls = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, eip_acls=eip_acls,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
