#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: bmvpc_customer_gateway_info
short_description: Gather information about Tencent Cloud BMVPC customer gateways
version_added: "0.8.0"
description: Returns BMVPC customer gateways visible in a Tencent Cloud region.
options:
  customer_gateway_ids:
    description: Customer gateway IDs to return. Mutually exclusive with O(filters).
    type: list
    elements: str
  filters:
    description: BMVPC API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all customer gateways
  susunola.tencentcloud.bmvpc_customer_gateway_info:
    region: ap-guangzhou

- name: Find customer gateways by ID
  susunola.tencentcloud.bmvpc_customer_gateway_info:
    region: ap-guangzhou
    customer_gateway_ids: [x-xxxxxxxx]
'''

RETURN = r'''
customer_gateways:
  description: Matching BMVPC customer gateways.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of customer gateways reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, customer_gateway_ids, filters, offset, limit):
    request = models.DescribeCustomerGatewaysRequest()
    request.Offset = offset
    request.Limit = limit
    if customer_gateway_ids:
        request.CustomerGatewayIds = customer_gateway_ids
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "customer_gateway_ids": {"type": "list", "elements": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        mutually_exclusive=[("customer_gateway_ids", "filters")],
        supports_check_mode=True,
    )
    try:
        from tencentcloud.bmvpc.v20180625 import models, bmvpc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-bmvpc package is required.")

    client = bmvpc_client.BmvpcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "bmvpc.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["customer_gateway_ids"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeCustomerGateways, request),
        lambda response: response.CustomerGatewaySet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    customer_gateways = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, customer_gateways=customer_gateways,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
