#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cam_group_membership_info
short_description: Gather information about Tencent Cloud CAM group memberships of a user
version_added: "1.2.0"
description: Returns the CAM groups a sub-user belongs to.
options:
  uid:
    description: UID of the sub-user whose group memberships are returned.
    type: int
    required: true
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List the groups of a sub-user
  susunola.tencentcloud.cam_group_membership_info:
    region: ap-guangzhou
    uid: 1000000001

'''

RETURN = r'''
groups:
  description: Groups the user belongs to.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of groups reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, uid, offset, limit):
    request = models.ListGroupsForUserRequest()
    request.Page = offset // limit + 1
    request.Rp = limit
    request.Uid = uid
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "uid": {"type": "int", "required": True},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cam.v20190116 import models, cam_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cam package is required.")

    client = cam_client.CamClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cam.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["uid"], offset, limit),
        lambda request: sdk_call(module, client.ListGroupsForUser, request),
        lambda response: response.GroupInfo,
        lambda response: response.TotalNum,
    )
    item_set, total_count = paginator.fetch_all()
    groups = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, groups=groups,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
