#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cbs_disk_backup_info
short_description: Gather information about Tencent Cloud CBS disk backups
version_added: "1.5.0"
description: Returns CBS disk backups visible in a Tencent Cloud region.
options:
  order:
    description: Order. API field C(Order).
    type: str
  order_field:
    description: Order field. API field C(OrderField).
    type: str
  disk_backup_ids:
    description: Disk backup IDs to return. Mutually exclusive with O(filters).
    type: list
    elements: str
  filters:
    description: CBS API filter names mapped to lists of values.
    type: dict
    default:
      {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all disk backups
  susunola.tencentcloud.cbs_disk_backup_info:
    region: ap-guangzhou

- name: Find disk backups by ID
  susunola.tencentcloud.cbs_disk_backup_info:
    region: ap-guangzhou
    disk_backup_ids: [x-xxxxxxxx]
'''

RETURN = r'''
disk_backups:
  description: Matching CBS disk backups.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of disk backups reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, order, order_field, disk_backup_ids, filters, offset, limit):
    request = models.DescribeDiskBackupsRequest()
    request.Offset = offset
    request.Limit = limit
    if order is not None:
        request.Order = order
    if order_field is not None:
        request.OrderField = order_field
    if disk_backup_ids:
        request.DiskBackupIds = disk_backup_ids
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "order": {"type": "str"},
        "order_field": {"type": "str"},
        "disk_backup_ids": {"type": "list", "elements": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        mutually_exclusive=[("disk_backup_ids", "filters")],
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cbs.v20170312 import models, cbs_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cbs package is required.")

    client = cbs_client.CbsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cbs.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["order"],
            module.params["order_field"],
            module.params["disk_backup_ids"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeDiskBackups, request),
        lambda response: response.DiskBackupSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    disk_backups = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, disk_backups=disk_backups,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
