#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdb_account_privilege_info
short_description: Gather information about Tencent Cloud CDB account privileges
version_added: "1.2.0"
description: Returns the privileges of an account on a CDB instance.
options:
  instance_id:
    description: ID of the CDB instance.
    type: str
    required: true
  user:
    description: Account name whose privileges are returned.
    type: str
    required: true
  host:
    description: Account host, for example C(%) or C(10.0.0.%).
    type: str
    required: true
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: Show the privileges of a CDB account
  susunola.tencentcloud.cdb_account_privilege_info:
    region: ap-guangzhou
    instance_id: "cdb-xxxxxxxx"
    user: "app"
    host: "%"

'''

RETURN = r'''
privileges:
  description: The account privileges (global, database, table and column level).
  returned: always
  type: dict
request_id:
  description: Request ID of the API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_id, user, host, offset, limit):
    # DescribeAccountPrivileges takes no request arguments and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeAccountPrivilegesRequest()
    request.InstanceId = instance_id
    request.User = user
    request.Host = host
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_id": {"type": "str", "required": True},
        "user": {"type": "str", "required": True},
        "host": {"type": "str", "required": True},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdb.v20170320 import models, cdb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdb package is required.")

    client = cdb_client.CdbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdb.tencentcloudapi.com"),
    )
    request = build_request(
        models,
        module.params["instance_id"],
        module.params["user"],
        module.params["host"],
        0,
        0)
    response = sdk_call(module, client.DescribeAccountPrivileges, request)
    privileges = serialize_sdk_object(response)
    privileges.pop("RequestId", None)
    module.exit_json(changed=False, privileges=privileges,
                     request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
