#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdb_audit_rule_template_info
short_description: Gather information about Tencent Cloud CDB audit rule templates
version_added: "1.5.0"
description: Returns CDB audit rule templates visible in a Tencent Cloud region.
options:
  rule_template_names:
    description: Rule template names. API field C(RuleTemplateNames).
    type: list
    elements: str
  alarm_level:
    description: Alarm level. API field C(AlarmLevel).
    type: int
  alarm_policy:
    description: Alarm policy. API field C(AlarmPolicy).
    type: int
  audit_rule_template_ids:
    description: Audit rule template IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - 'Can run in C(check_mode): the module reads the current state and
        predicts the result without issuing a write API call.'
    support: full
  idempotency:
    description:
      - 'Read-only: every run returns the current state and never changes
        the target, so a repeated run reports C(changed=false).'
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all audit rule templates
  susunola.tencentcloud.cdb_audit_rule_template_info:
    region: ap-guangzhou

- name: Find audit rule templates by ID
  susunola.tencentcloud.cdb_audit_rule_template_info:
    region: ap-guangzhou
    audit_rule_template_ids: [x-xxxxxxxx]
'''

RETURN = r'''
audit_rule_templates:
  description: Matching CDB audit rule templates.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of audit rule templates reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, rule_template_names, alarm_level, alarm_policy, audit_rule_template_ids, offset, limit):
    request = models.DescribeAuditRuleTemplatesRequest()
    request.Offset = offset
    request.Limit = limit
    if rule_template_names is not None:
        request.RuleTemplateNames = rule_template_names
    if alarm_level is not None:
        request.AlarmLevel = alarm_level
    if alarm_policy is not None:
        request.AlarmPolicy = alarm_policy
    if audit_rule_template_ids:
        request.RuleTemplateIds = audit_rule_template_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "rule_template_names": {"type": "list", "elements": "str"},
        "alarm_level": {"type": "int"},
        "alarm_policy": {"type": "int"},
        "audit_rule_template_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdb.v20170320 import models, cdb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdb package is required.")

    client = cdb_client.CdbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdb.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["rule_template_names"],
            module.params["alarm_level"],
            module.params["alarm_policy"],
            module.params["audit_rule_template_ids"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeAuditRuleTemplates, request),
        lambda response: response.Items,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    audit_rule_templates = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, audit_rule_templates=audit_rule_templates,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
