#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdb_audit_rule_info
short_description: Gather information about Tencent Cloud CDB audit rules
version_added: "1.5.0"
description: Returns CDB audit rules visible in a Tencent Cloud region.
options:
  rule_id:
    description: Sets the C(RuleId) field of V(DescribeAuditRules); omit it to leave that field unset.
    type: str
  rule_name:
    description: Sets the C(RuleName) field of V(DescribeAuditRules); omit it to leave that field unset.
    type: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.cdb_audit_rule
    description: Create or delete a Tencent Cloud CDB audit rule.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all audit rules
  susunola.tencentcloud.cdb_audit_rule_info:
    region: ap-guangzhou
'''

RETURN = r'''
audit_rules:
  description: Matching CDB audit rules.
  returned: always
  type: list
  elements: dict
  sample:
    - RuleId: null
      CreateTime: null
      ModifyTime: null
      RuleName: null
      Description: null
      RuleFilters:
        - Type: null
          Compare: null
          Value: null
      AuditAll: null
total_count:
  description: Number of audit rules reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, rule_id, rule_name, offset, limit):
    request = models.DescribeAuditRulesRequest()
    request.Offset = offset
    request.Limit = limit
    if rule_id is not None:
        request.RuleId = rule_id
    if rule_name is not None:
        request.RuleName = rule_name
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "rule_id": {"type": "str"},
        "rule_name": {"type": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdb.v20170320 import models, cdb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdb package is required.")

    client = cdb_client.CdbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdb.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["rule_id"],
            module.params["rule_name"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeAuditRules, request),
        lambda response: response.Items,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    audit_rules = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, audit_rules=audit_rules,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
