#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdb_database_info
short_description: Gather information about Tencent Cloud CDB databases
version_added: "1.1.0"
description: Returns the databases of a TencentDB for MySQL (CDB) instance.
options:
  instance_id:
    description: ID of the CDB instance whose databases are returned.
    type: str
    required: true
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List the databases of a CDB instance
  susunola.tencentcloud.cdb_database_info:
    region: ap-guangzhou
    instance_id: "cdb-xxxxxxxx"

'''

RETURN = r'''
databases:
  description: Databases of the instance.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of databases reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_id, offset, limit):
    request = models.DescribeDatabasesRequest()
    request.Offset = offset
    request.Limit = limit
    request.InstanceId = instance_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_id": {"type": "str", "required": True},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdb.v20170320 import models, cdb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdb package is required.")

    client = cdb_client.CdbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdb.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["instance_id"], offset, limit),
        lambda request: sdk_call(module, client.DescribeDatabases, request),
        lambda response: response.Items,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    databases = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, databases=databases,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
