#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdb_parameter_template_info
short_description: Gather information about Tencent Cloud CDB parameter templates
version_added: "1.2.0"
description: Returns CDB parameter templates visible in a Tencent Cloud region.
options: {}
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all CDB parameter templates
  susunola.tencentcloud.cdb_parameter_template_info:
    region: ap-guangzhou

'''

RETURN = r'''
parameter_templates:
  description: Parameter templates.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of templates returned (the API reports no pageable total).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    # DescribeParamTemplates returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeParamTemplatesRequest()
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({})
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdb.v20170320 import models, cdb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdb package is required.")

    client = cdb_client.CdbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdb.tencentcloudapi.com"),
    )
    request = build_request(models, 0, 0)
    response = sdk_call(module, client.DescribeParamTemplates, request)
    items = response.Items or []
    parameter_templates = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, parameter_templates=parameter_templates,
                     total_count=len(parameter_templates), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
