#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdc_dedicated_cluster_order_info
short_description: Gather information about Tencent Cloud CDC dedicated cluster orders
version_added: "0.8.0"
description: Returns CDC dedicated cluster orders visible in a Tencent Cloud region.
options:
  dedicated_cluster_order_ids:
    description: Dedicated cluster order IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all dedicated cluster orders
  tencentcloud.cloud.cdc_dedicated_cluster_order_info:
    region: ap-guangzhou

- name: Find dedicated cluster orders by ID
  tencentcloud.cloud.cdc_dedicated_cluster_order_info:
    region: ap-guangzhou
    dedicated_cluster_order_ids: [x-xxxxxxxx]
'''

RETURN = r'''
dedicated_cluster_orders:
  description: Matching CDC dedicated cluster orders.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of dedicated cluster orders reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, dedicated_cluster_order_ids, offset, limit):
    request = models.DescribeDedicatedClusterOrdersRequest()
    request.Offset = offset
    request.Limit = limit
    if dedicated_cluster_order_ids:
        request.DedicatedClusterIds = dedicated_cluster_order_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "dedicated_cluster_order_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdc.v20201214 import models, cdc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdc package is required.")

    client = cdc_client.CdcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdc.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["dedicated_cluster_order_ids"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeDedicatedClusterOrders, request),
        lambda response: response.DedicatedClusterOrderSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    dedicated_cluster_orders = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, dedicated_cluster_orders=dedicated_cluster_orders, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
