#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdn_cls_log_topic_info
short_description: Gather information about Tencent Cloud CDN cls log topics
version_added: "1.5.0"
description: Returns CDN cls log topics visible in a Tencent Cloud region.
options:
  channel:
    description: Channel. API field C(Channel).
    type: str
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotency:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all cls log topics
  susunola.tencentcloud.cdn_cls_log_topic_info:
    region: ap-guangzhou
'''

RETURN = r'''
cls_log_topics:
  description: Matching CDN cls log topics.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of cls log topics returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, channel, offset, limit):
    # ListClsLogTopics returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.ListClsLogTopicsRequest()
    if channel is not None:
        request.Channel = channel
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "channel": {"type": "str"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdn.v20180606 import models, cdn_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdn package is required.")

    client = cdn_client.CdnClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdn.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["channel"], 0, 0)
    response = sdk_call(module, client.ListClsLogTopics, request)
    items = response.Topics or []
    cls_log_topics = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, cls_log_topics=cls_log_topics,
                     total_count=len(cls_log_topics), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
