#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cdwdoris_user_workload_group_info
short_description: Gather information about Tencent Cloud CDWDORIS user bind workload groups
version_added: "1.5.0"
description: Returns CDWDORIS user bind workload groups visible in a Tencent Cloud region.
options:
  instance_id:
    description: Instance id. API field C(InstanceId).
    type: str
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all user bind workload groups
  susunola.tencentcloud.cdwdoris_user_workload_group_info:
    region: ap-guangzhou
'''

RETURN = r'''
user_bind_workload_groups:
  description: Matching CDWDORIS user bind workload groups.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of user bind workload groups returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_id, offset, limit):
    # DescribeUserBindWorkloadGroup returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeUserBindWorkloadGroupRequest()
    if instance_id is not None:
        request.InstanceId = instance_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_id": {"type": "str"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cdwdoris.v20211228 import models, cdwdoris_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cdwdoris package is required.")

    client = cdwdoris_client.CdwdorisClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cdwdoris.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["instance_id"], 0, 0)
    response = sdk_call(module, client.DescribeUserBindWorkloadGroup, request)
    items = response.UserBindInfos or []
    user_bind_workload_groups = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, user_bind_workload_groups=user_bind_workload_groups,
                     total_count=len(user_bind_workload_groups), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
