#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: chdfs_access_group_info
short_description: Gather information about Tencent Cloud CHDFS access groups
version_added: "1.5.0"
description: Returns CHDFS access groups visible in a Tencent Cloud region.
options:
  vpc_id:
    description: Vpc id. API field C(VpcId).
    type: str
  owner_uin:
    description: Owner uin. API field C(OwnerUin).
    type: int
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.chdfs_access_group
    description: Manage Tencent Cloud CHDFS access groups.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all access groups
  susunola.tencentcloud.chdfs_access_group_info:
    region: ap-guangzhou
'''

RETURN = r'''
access_groups:
  description: Matching CHDFS access groups.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of access groups returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, vpc_id, owner_uin, next_token, max_results):
    request = models.DescribeAccessGroupsRequest()
    if vpc_id is not None:
        request.VpcId = vpc_id
    if owner_uin is not None:
        request.OwnerUin = owner_uin
    if next_token:
        request.AccessGroupIdMarker = next_token
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "vpc_id": {"type": "str"},
        "owner_uin": {"type": "int"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.chdfs.v20201112 import models, chdfs_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-chdfs package is required.")

    client = chdfs_client.ChdfsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "chdfs.tencentcloudapi.com"),
    )
    access_groups = []
    next_token = None
    total_count = None
    while True:
        request = build_request(
            models,
            module.params["vpc_id"],
            module.params["owner_uin"],
            next_token,
            None)
        response = sdk_call(module, client.DescribeAccessGroups, request)
        batch = response.AccessGroups or []
        access_groups.extend(serialize_sdk_object(item) for item in batch)
        next_token = response.NextAccessGroupIdMarker
        if response.IsOver or not next_token:
            break
    if total_count is None:
        total_count = len(access_groups)
    request_id = getattr(response, "RequestId", None)
    module.exit_json(changed=False, access_groups=access_groups,
                     total_count=total_count, request_id=request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
