#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: ckafka_route_info
short_description: Gather information about Tencent Cloud CKAFKA routes
version_added: "1.5.0"
description: Returns CKAFKA routes visible in a Tencent Cloud region.
options:
  instance_id:
    description: Instance id. API field C(InstanceId).
    type: str
  route_id:
    description: Route id. API field C(RouteId).
    type: int
  main_route_flag:
    description: Main route flag. API field C(MainRouteFlag).
    type: bool
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all routes
  susunola.tencentcloud.ckafka_route_info:
    region: ap-guangzhou
'''

RETURN = r'''
routes:
  description: Matching CKAFKA routes.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of routes returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_id, route_id, main_route_flag, offset, limit):
    # DescribeRoute returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeRouteRequest()
    if instance_id is not None:
        request.InstanceId = instance_id
    if route_id is not None:
        request.RouteId = route_id
    if main_route_flag is not None:
        request.MainRouteFlag = main_route_flag
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_id": {"type": "str"},
        "route_id": {"type": "int"},
        "main_route_flag": {"type": "bool"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.ckafka.v20190819 import models, ckafka_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-ckafka package is required.")

    client = ckafka_client.CkafkaClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "ckafka.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["instance_id"], module.params["route_id"], module.params["main_route_flag"], 0, 0)
    response = sdk_call(module, client.DescribeRoute, request)
    items = (response.Result.Routers if response.Result is not None else None) or []
    routes = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, routes=routes,
                     total_count=len(routes), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
