#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: ckafka_acl_info
short_description: Gather information about Tencent Cloud CKAFKA acls
version_added: "1.5.0"
description: Returns CKAFKA acls visible in a Tencent Cloud region.
options:
  instance_id:
    description: Instance id. API field C(InstanceId).
    type: str
  resource_type:
    description: Resource type. API field C(ResourceType).
    type: int
  resource_name:
    description: Resource name. API field C(ResourceName).
    type: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all acls
  susunola.tencentcloud.ckafka_acl_info:
    region: ap-guangzhou
'''

RETURN = r'''
acls:
  description: Matching CKAFKA acls.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of acls reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_id, resource_type, resource_name, offset, limit):
    request = models.DescribeACLRequest()
    request.Offset = offset
    request.Limit = limit
    if instance_id is not None:
        request.InstanceId = instance_id
    if resource_type is not None:
        request.ResourceType = resource_type
    if resource_name is not None:
        request.ResourceName = resource_name
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_id": {"type": "str"},
        "resource_type": {"type": "int"},
        "resource_name": {"type": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.ckafka.v20190819 import models, ckafka_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-ckafka package is required.")

    client = ckafka_client.CkafkaClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "ckafka.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["instance_id"],
            module.params["resource_type"],
            module.params["resource_name"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeACL, request),
        lambda response: response.Result.AclList if response.Result is not None else None,
        lambda response: response.Result.TotalCount if response.Result is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    acls = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, acls=acls,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
