#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: ckafka_datahub_connection_info
short_description: Gather information about Tencent Cloud CKAFKA datahub connections
version_added: "1.5.0"
description: Returns CKAFKA datahub connections visible in a Tencent Cloud region.
options:
  type:
    description: Type. API field C(Type).
    type: str
  search_word:
    description: Search word. API field C(SearchWord).
    type: str
  resource_region:
    description: Resource region. API field C(ResourceRegion).
    type: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all datahub connections
  susunola.tencentcloud.ckafka_datahub_connection_info:
    region: ap-guangzhou
'''

RETURN = r'''
datahub_connections:
  description: Matching CKAFKA datahub connections.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of datahub connections reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, type, search_word, resource_region, offset, limit):
    request = models.DescribeConnectResourcesRequest()
    request.Offset = offset
    request.Limit = limit
    if type is not None:
        request.Type = type
    if search_word is not None:
        request.SearchWord = search_word
    if resource_region is not None:
        request.ResourceRegion = resource_region
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "type": {"type": "str"},
        "search_word": {"type": "str"},
        "resource_region": {"type": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.ckafka.v20190819 import models, ckafka_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-ckafka package is required.")

    client = ckafka_client.CkafkaClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "ckafka.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["type"],
            module.params["search_word"],
            module.params["resource_region"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeConnectResources, request),
        lambda response: response.Result.ConnectResourceList if response.Result is not None else None,
        lambda response: response.Result.TotalCount if response.Result is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    datahub_connections = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, datahub_connections=datahub_connections,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
