#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: ckafka_datahub_task_info
short_description: Gather information about Tencent Cloud CKAFKA datahub tasks
version_added: "1.5.0"
description: Returns CKAFKA datahub tasks visible in a Tencent Cloud region.
options:
  search_word:
    description: Search word. API field C(SearchWord).
    type: str
  target_type:
    description: Target type. API field C(TargetType).
    type: str
  task_type:
    description: Task type. API field C(TaskType).
    type: str
  source_type:
    description: Source type. API field C(SourceType).
    type: str
  resource:
    description: Resource. API field C(Resource).
    type: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotency:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all datahub tasks
  susunola.tencentcloud.ckafka_datahub_task_info:
    region: ap-guangzhou
'''

RETURN = r'''
datahub_tasks:
  description: Matching CKAFKA datahub tasks.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of datahub tasks reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, search_word, target_type, task_type, source_type, resource, offset, limit):
    request = models.DescribeDatahubTasksRequest()
    request.Offset = offset
    request.Limit = limit
    if search_word is not None:
        request.SearchWord = search_word
    if target_type is not None:
        request.TargetType = target_type
    if task_type is not None:
        request.TaskType = task_type
    if source_type is not None:
        request.SourceType = source_type
    if resource is not None:
        request.Resource = resource
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "search_word": {"type": "str"},
        "target_type": {"type": "str"},
        "task_type": {"type": "str"},
        "source_type": {"type": "str"},
        "resource": {"type": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.ckafka.v20190819 import models, ckafka_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-ckafka package is required.")

    client = ckafka_client.CkafkaClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "ckafka.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["search_word"],
            module.params["target_type"],
            module.params["task_type"],
            module.params["source_type"],
            module.params["resource"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeDatahubTasks, request),
        lambda response: response.Result.TaskList if response.Result is not None else None,
        lambda response: response.Result.TotalCount if response.Result is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    datahub_tasks = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, datahub_tasks=datahub_tasks,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
