#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: ckafka_acl_rule_info
short_description: Gather information about Tencent Cloud CKAFKA acl rules
version_added: "1.5.0"
description: Returns CKAFKA acl rules visible in a Tencent Cloud region.
options:
  instance_id:
    description: Instance id. API field C(InstanceId).
    type: str
  rule_name:
    description: Rule name. API field C(RuleName).
    type: str
  pattern_type:
    description: Pattern type. API field C(PatternType).
    type: str
  is_simplified:
    description: Is simplified. API field C(IsSimplified).
    type: bool
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all acl rules
  susunola.tencentcloud.ckafka_acl_rule_info:
    region: ap-guangzhou
'''

RETURN = r'''
acl_rules:
  description: Matching CKAFKA acl rules.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of acl rules reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_id, rule_name, pattern_type, is_simplified, offset, limit):
    # DescribeAclRule returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeAclRuleRequest()
    if instance_id is not None:
        request.InstanceId = instance_id
    if rule_name is not None:
        request.RuleName = rule_name
    if pattern_type is not None:
        request.PatternType = pattern_type
    if is_simplified is not None:
        request.IsSimplified = is_simplified
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_id": {"type": "str"},
        "rule_name": {"type": "str"},
        "pattern_type": {"type": "str"},
        "is_simplified": {"type": "bool"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.ckafka.v20190819 import models, ckafka_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-ckafka package is required.")

    client = ckafka_client.CkafkaClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "ckafka.tencentcloudapi.com"),
    )
    request = build_request(models,
                            module.params["instance_id"],
                            module.params["rule_name"],
                            module.params["pattern_type"],
                            module.params["is_simplified"],
                            0,
                            0)
    response = sdk_call(module, client.DescribeAclRule, request)
    items = (response.Result.AclRuleList if response.Result is not None else None) or []
    acl_rules = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, acl_rules=acl_rules,
                     total_count=len(acl_rules), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
