#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: clb_listener_target_info
short_description: Gather information about Tencent Cloud CLB listener targets
version_added: "0.14.0"
description: Returns the backend targets bound to the listeners of a CLB instance.
options:
  load_balancer_id:
    description: ID of the CLB instance whose listener targets are returned.
    type: str
    required: true
  listener_ids:
    description: Return targets of only these listener IDs.
    type: list
    elements: str
  protocol:
    description: Return targets of listeners of this protocol.
    type: str
  port:
    description: Return targets of listeners on this port.
    type: int
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List the backend targets of a load balancer
  susunola.tencentcloud.clb_listener_target_info:
    region: ap-guangzhou
    load_balancer_id: lb-xxxxxxxx
'''

RETURN = r'''
listeners:
  description: Listeners with their bound backend targets.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of listeners returned (the API reports no pageable total).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, load_balancer_id, listener_ids, protocol, port, offset, limit):
    # DescribeTargets returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeTargetsRequest()
    request.LoadBalancerId = load_balancer_id
    if listener_ids is not None:
        request.ListenerIds = listener_ids
    if protocol is not None:
        request.Protocol = protocol
    if port is not None:
        request.Port = port
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "load_balancer_id": {"type": "str", "required": True},
        "listener_ids": {"type": "list", "elements": "str"},
        "protocol": {"type": "str"},
        "port": {"type": "int"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.clb.v20180317 import models, clb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-clb package is required.")

    client = clb_client.ClbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "clb.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["load_balancer_id"], module.params["listener_ids"], module.params["protocol"], module.params["port"], 0, 0)
    response = sdk_call(module, client.DescribeTargets, request)
    items = response.Listeners or []
    listeners = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, listeners=listeners,
                     total_count=len(listeners), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
