#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cloudaudit_audit_info
short_description: Gather information about Tencent Cloud CLOUDAUDIT audits
version_added: "1.5.0"
description: Returns CLOUDAUDIT audits visible in a Tencent Cloud region.
options:
  {}
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.cloudaudit_audit
    description: Manage Tencent Cloud account-level CloudAudit delivery.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all audits
  susunola.tencentcloud.cloudaudit_audit_info:
    region: ap-guangzhou
'''

RETURN = r'''
audits:
  description: Matching CLOUDAUDIT audits.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of audits returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    # ListAudits returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.ListAuditsRequest()
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({})
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cloudaudit.v20190319 import models, cloudaudit_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cloudaudit package is required.")

    client = cloudaudit_client.CloudauditClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cloudaudit.tencentcloudapi.com"),
    )
    request = build_request(models, 0, 0)
    response = sdk_call(module, client.ListAudits, request)
    items = response.AuditSummarys or []
    audits = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, audits=audits,
                     total_count=len(audits), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
