#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cmq_topic_info
short_description: Gather information about Tencent Cloud CMQ topics
version_added: "1.3.0"
description: Returns CMQ topics visible in a Tencent Cloud region.
options:
  topic_name:
    description: Topic name used to narrow the returned topics.
    type: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List CMQ topics
  susunola.tencentcloud.cmq_topic_info:
    region: ap-guangzhou

- name: Find a CMQ topic by name
  susunola.tencentcloud.cmq_topic_info:
    region: ap-guangzhou
    topic_name: order-events

'''

RETURN = r'''
topics:
  description: Matching CMQ topics.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of CMQ topics reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, topic_name, offset, limit):
    request = models.DescribeCmqTopicsRequest()
    request.Offset = offset
    request.Limit = limit
    if topic_name is not None:
        request.TopicName = topic_name
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "topic_name": {"type": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tdmq.v20200217 import models, tdmq_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tdmq package is required.")

    client = tdmq_client.TdmqClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tdmq.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["topic_name"], offset, limit),
        lambda request: sdk_call(module, client.DescribeCmqTopics, request),
        lambda response: response.TopicList,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    topics = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, topics=topics,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
