#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cngw_cloud_native_api_gateway_llm_model_api_info
short_description: Gather information about Tencent Cloud CNGW cloud native api gateway llm model apis
version_added: "0.8.0"
description: Returns CNGW cloud native api gateway llm model apis visible in a Tencent Cloud region.
options:
  filters:
    description: CNGW API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all cloud native api gateway llm model apis
  susunola.tencentcloud.cngw_cloud_native_api_gateway_llm_model_api_info:
    region: ap-guangzhou
'''

RETURN = r'''
cloud_native_api_gateway_llm_model_apis:
  description: Matching CNGW cloud native api gateway llm model apis.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of cloud native api gateway llm model apis reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, filters, offset, limit):
    request = models.DescribeCloudNativeAPIGatewayLLMModelAPIsRequest()
    request.Offset = offset
    request.Limit = limit
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cngw.v20230418 import models, cngw_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cngw package is required.")

    client = cngw_client.CngwClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cngw.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["filters"], offset, limit),
        lambda request: sdk_call(module, client.DescribeCloudNativeAPIGatewayLLMModelAPIs, request),
        lambda response: response.Result.DataList if response.Result is not None else None,
        lambda response: response.Result.TotalCount if response.Result is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    cloud_native_api_gateway_llm_model_apis = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, cloud_native_api_gateway_llm_model_apis=cloud_native_api_gateway_llm_model_apis,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
