#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: config_remediation_info
short_description: Gather information about Tencent Cloud Config remediations
version_added: "1.1.0"
description: Returns remediations visible in a Tencent Cloud region.
options:
  rule_ids:
    description: Config rule IDs whose remediations are returned.
    type: list
    elements: str
    required: true
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List remediations
  susunola.tencentcloud.config_remediation_info:
    region: ap-guangzhou
    rule_ids: example
'''

RETURN = r'''
remediations:
  description: Matching remediations.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of remediations reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, rule_ids, offset, limit):
    # ListRemediations returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.ListRemediationsRequest()
    request.RuleIds = rule_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "rule_ids": {"type": "list", "elements": "str", "required": True},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.config.v20220802 import models, config_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-config package is required.")

    client = config_client.ConfigClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "config.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["rule_ids"], 0, 0)
    response = sdk_call(module, client.ListRemediations, request)
    items = response.Remediations or []
    remediations = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, remediations=remediations,
                     total_count=len(remediations), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
