#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: cynosdb_cluster_info
short_description: Gather information about TencentDB for CynosDB clusters
version_added: "0.6.0"
description: Returns CynosDB clusters visible in a Tencent Cloud region.
options:
  filters:
    description: CynosDB API filter names (ClusterId, InstanceId, InstanceName) mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all CynosDB clusters
  tencentcloud.cloud.cynosdb_cluster_info:
    region: ap-guangzhou

- name: Find a cluster by ID
  tencentcloud.cloud.cynosdb_cluster_info:
    region: ap-guangzhou
    filters:
      ClusterId: [cynosdbmysql-xxxxxxxx]
'''

RETURN = r'''
clusters:
  description: Matching CynosDB clusters.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of clusters reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, filters, offset, limit):
    request = models.DescribeClustersRequest()
    request.Offset = offset
    request.Limit = limit
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.QueryFilter()
            api_filter.Names = [name]
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.cynosdb.v20190107 import models, cynosdb_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-cynosdb package is required.")

    client = cynosdb_client.CynosdbClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "cynosdb.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["filters"], offset, limit),
        lambda request: sdk_call(module, client.DescribeClusters, request),
        lambda response: response.ClusterSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    clusters = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, clusters=clusters, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
