#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: dbdc_db_custom_cluster_info
short_description: Gather information about Tencent Cloud DBDC db custom clusters
version_added: "0.8.0"
description: Returns DBDC db custom clusters visible in a Tencent Cloud region.
options:
  db_custom_cluster_ids:
    description: Db custom cluster IDs to return. Mutually exclusive with O(filters).
    type: list
    elements: str
  filters:
    description: DBDC API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all db custom clusters
  susunola.tencentcloud.dbdc_db_custom_cluster_info:
    region: ap-guangzhou

- name: Find db custom clusters by ID
  susunola.tencentcloud.dbdc_db_custom_cluster_info:
    region: ap-guangzhou
    db_custom_cluster_ids: [x-xxxxxxxx]
'''

RETURN = r'''
db_custom_clusters:
  description: Matching DBDC db custom clusters.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of db custom clusters reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, db_custom_cluster_ids, filters, offset, limit):
    request = models.DescribeDBCustomClustersRequest()
    request.Offset = offset
    request.Limit = limit
    if db_custom_cluster_ids:
        request.ClusterIds = db_custom_cluster_ids
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "db_custom_cluster_ids": {"type": "list", "elements": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        mutually_exclusive=[("db_custom_cluster_ids", "filters")],
        supports_check_mode=True,
    )
    try:
        from tencentcloud.dbdc.v20201029 import models, dbdc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-dbdc package is required.")

    client = dbdc_client.DbdcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "dbdc.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["db_custom_cluster_ids"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeDBCustomClusters, request),
        lambda response: response.ClusterSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    db_custom_clusters = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, db_custom_clusters=db_custom_clusters, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
