#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: dlc_task_info
short_description: Gather information about Tencent Cloud DLC tasks
version_added: "0.8.0"
description: Returns DLC tasks visible in a Tencent Cloud region.
options:
  task_ids:
    description: Task IDs to return. Mutually exclusive with O(filters).
    type: list
    elements: str
  filters:
    description: DLC API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all tasks
  susunola.tencentcloud.dlc_task_info:
    region: ap-guangzhou

- name: Find tasks by ID
  susunola.tencentcloud.dlc_task_info:
    region: ap-guangzhou
    task_ids: [x-xxxxxxxx]
'''

RETURN = r'''
tasks:
  description: Matching DLC tasks.
  returned: always
  type: list
  elements: dict
  sample:
    - DatabaseName: null
      DataAmount: null
      Id: null
      UsedTime: null
      OutputPath: null
      CreateTime: null
      State: null
      SQLType: null
      SQL: null
      ResultExpired: null
      RowAffectInfo: null
      DataSet: null
      Error: null
      Percentage: null
      OutputMessage: null
      TaskType: null
      ProgressDetail: null
      UpdateTime: null
      DataEngineId: null
      OperateUin: null
      DataEngineName: null
      InputType: null
      InputConf: null
      DataNumber: null
      CanDownload: null
      UserAlias: null
      SparkJobName: null
      SparkJobId: null
      SparkJobFile: null
      UiUrl: null
      TotalTime: null
      CmdArgs: null
      ImageVersion: null
      DriverSize: null
      ExecutorSize: null
      ExecutorNums: null
      ExecutorMaxNumbers: null
      CommonMetrics: null
      SparkMonitorMetrics: null
      PrestoMonitorMetrics: null
      ResultFormat: null
      EngineTypeDetail: null
      ResourceGroupName: null
      Source: null
      SourceExtra: null
      CreatorUin: null
      CreatorAlias: null
      CustomizedConf: null
      TaskTimeSum: null
      StageStartTime: null
      InputRecordsSum: null
      AnalysisStatusType: null
      OutputRecordsSum: null
      OutputBytesSum: null
      OutputFilesNum: null
      OutputSmallFilesNum: null
      ShuffleReadRecordsSum: null
      ShuffleReadBytesSum: null
      SparkAppId: null
      TaskCategory: null
      TaskName: null
      EngineType: null
      EngineHasListenerConfig: null
      ResourceGroupId: null
      JobTimeSum: null
      LaunchTime: null
      GpuDriverSize: null
      GpuExecutorSize: null
      ShuffleWriteBytesSum: null
      ActiveCore: null
      QueueTime: null
      ResourceGroupType: null
total_count:
  description: Number of tasks reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, task_ids, filters, offset, limit):
    request = models.DescribeTaskListRequest()
    request.Offset = offset
    request.Limit = limit
    if task_ids:
        request.HouseIds = task_ids
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "task_ids": {"type": "list", "elements": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        mutually_exclusive=[("task_ids", "filters")],
        supports_check_mode=True,
    )
    try:
        from tencentcloud.dlc.v20210125 import models, dlc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-dlc package is required.")

    client = dlc_client.DlcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "dlc.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["task_ids"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeTaskList, request),
        lambda response: response.TaskList,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    tasks = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, tasks=tasks,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
