#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: dts_migration_check_info
short_description: Gather information about Tencent Cloud DTS migration check jobs
version_added: "1.5.0"
description: Returns DTS migration check jobs visible in a Tencent Cloud region.
options:
  job_id:
    description: Job id. API field C(JobId).
    type: str
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all migration check jobs
  susunola.tencentcloud.dts_migration_check_info:
    region: ap-guangzhou
'''

RETURN = r'''
migration_check_jobs:
  description: Matching DTS migration check jobs.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of migration check jobs returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, job_id, offset, limit):
    # DescribeMigrationCheckJob returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeMigrationCheckJobRequest()
    if job_id is not None:
        request.JobId = job_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "job_id": {"type": "str"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.dts.v20211206 import models, dts_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-dts package is required.")

    client = dts_client.DtsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "dts.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["job_id"], 0, 0)
    response = sdk_call(module, client.DescribeMigrationCheckJob, request)
    items = response.StepInfo or []
    migration_check_jobs = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, migration_check_jobs=migration_check_jobs,
                     total_count=len(migration_check_jobs), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
