#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: elasticsearch_instance_info
short_description: Gather information about Tencent Cloud Elasticsearch instances
version_added: "0.4.0"
description: Returns Elasticsearch Service instances visible in a Tencent Cloud region.
options:
  instance_ids:
    description: Instance IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.elasticsearch_instance
    description: Manage Tencent Cloud Elasticsearch clusters.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all Elasticsearch Service instances
  susunola.tencentcloud.elasticsearch_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  susunola.tencentcloud.elasticsearch_instance_info:
    region: ap-guangzhou
    instance_ids: [es-xxxxxxxx]
'''

RETURN = r'''
instances:
  description: Matching Elasticsearch Service instances.
  returned: always
  type: list
  elements: dict
  sample:
    - InstanceId: null
      InstanceName: null
      Region: null
      Zone: null
      AppId: null
      Uin: null
      VpcUid: null
      SubnetUid: null
      Status: null
      RenewFlag: null
      ChargeType: null
      ChargePeriod: null
      NodeType: null
      NodeNum: null
      CpuNum: null
      MemSize: null
      DiskType: null
      DiskSize: null
      EsDomain: null
      EsVip: null
      EsPort: null
      KibanaUrl: null
      EsVersion: null
      EsConfig: null
      EsAcl: null
      CreateTime: null
      UpdateTime: null
      Deadline: null
      InstanceType: null
      IkConfig: null
      MasterNodeInfo: null
      CosBackup: null
      AllowCosBackup: null
      TagList:
        - TagKey: null
          TagValue: null
      LicenseType: null
      RealLicenseType: null
      EnableHotWarmMode: null
      WarmNodeType: null
      WarmNodeNum: null
      WarmCpuNum: null
      WarmMemSize: null
      WarmDiskType: null
      WarmDiskSize: null
      NodeInfoList:
        - NodeNum: null
          NodeType: null
          Type: null
          DiskType: null
          DiskSize: null
          LocalDiskInfo: null
          DiskCount: null
          DiskEncrypt: null
          KmsKeyId: null
          KmsKeyName: null
          CpuNum: null
          MemSize: null
          DiskEnhance: null
          GpuInfo: null
      EsPublicUrl: null
      MultiZoneInfo:
        - Zone: null
          SubnetId: null
          Hidden: null
      DeployMode: null
      PublicAccess: null
      EsPublicAcl: null
      KibanaPrivateUrl: null
      KibanaPublicAccess: null
      KibanaPrivateAccess: null
      SecurityType: null
      SceneType: null
      KibanaConfig: null
      KibanaNodeInfo: null
      WebNodeTypeInfo: null
      Jdk: null
      Protocol: null
      SecurityGroups: null
      ColdNodeType: null
      ColdNodeNum: null
      ColdCpuNum: null
      ColdMemSize: null
      ColdDiskType: null
      ColdDiskSize: null
      FrozenNodeType: null
      FrozenNodeNum: null
      FrozenCpuNum: null
      FrozenMemSize: null
      FrozenDiskType: null
      FrozenDiskSize: null
      HealthStatus: null
      EsPrivateUrl: null
      EsPrivateDomain: null
      EsConfigSets:
        - Type: null
          EsConfig: null
      OperationDuration: null
      OptionalWebServiceInfos:
        - Type: null
          Status: null
          PublicUrl: null
          PrivateUrl: null
          PublicAccess: null
          PrivateAccess: null
          Version: null
          PrivateVip: null
          CustomPrivateUrl: null
      AutoIndexEnabled: null
      EnableHybridStorage: null
      ProcessPercent: null
      KibanaAlteringPublicAccess: null
      HasKernelUpgrade: null
      CdcId: null
      KibanaPrivateVip: null
      CustomKibanaPrivateUrl: null
      OutboundPublicAcls:
        - NodeType: null
          WhiteHostList: null
      NetConnectScheme: null
      DisasterRecoverGroupAffinity: null
      SubProductCode: null
      CosBucketStorageSize: null
      ReadWriteMode: null
      EnableScheduleRecoverGroup: null
      EnableScheduleOperationDuration: null
      EnableDestroyProtection: null
      ShowKibanaIpPort: null
      IsCdzLite: null
      EsPrivateTcpUrl: null
      IsInRecycleBin: null
      RecycleLockEnabled: null
      MayDestroyPoint: null
      DelayDestroyInterval: null
      EnableAutoReplace: null
      OpenMTLS: null
      ServerCertSource: null
      OldEsVip: null
      OldEsPrivateTcpUrl: null
      NeedOfflineOldNodesNotify: null
total_count:
  description: Number of instances reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_ids, offset, limit):
    request = models.DescribeInstancesRequest()
    request.Offset = offset
    request.Limit = limit
    if instance_ids:
        request.InstanceIds = instance_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.es.v20180416 import models, es_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-es package is required.")

    client = es_client.EsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "es.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["instance_ids"], offset, limit),
        lambda request: sdk_call(module, client.DescribeInstances, request),
        lambda response: response.InstanceList,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    instances = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, instances=instances,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
