#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: gaap_listener_real_servers_info
short_description: Gather information about Tencent Cloud GAAP listener real servers
version_added: "1.5.0"
description: Returns GAAP listener real servers visible in a Tencent Cloud region.
options:
  listener_id:
    description: Sets the C(ListenerId) field of V(DescribeListenerRealServers); omit it to leave that field unset.
    type: str
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.gaap_listener_real_servers
    description: Reconcile Tencent Cloud GAAP listener origin bindings.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all listener real servers
  susunola.tencentcloud.gaap_listener_real_servers_info:
    region: ap-guangzhou
'''

RETURN = r'''
listener_real_servers:
  description: Matching GAAP listener real servers.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of listener real servers reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, listener_id, offset, limit):
    # DescribeListenerRealServers returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeListenerRealServersRequest()
    if listener_id is not None:
        request.ListenerId = listener_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "listener_id": {"type": "str"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.gaap.v20180529 import models, gaap_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-gaap package is required.")

    client = gaap_client.GaapClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "gaap.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["listener_id"], 0, 0)
    response = sdk_call(module, client.DescribeListenerRealServers, request)
    items = response.RealServerSet or []
    listener_real_servers = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, listener_real_servers=listener_real_servers,
                     total_count=len(listener_real_servers), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
