#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: iot_product_info
short_description: Gather information about Tencent Cloud IOT products
version_added: "0.9.0"
description: Returns IOT products visible in a Tencent Cloud region.
options:
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all products
  susunola.tencentcloud.iot_product_info:
    region: ap-guangzhou
'''

RETURN = r'''
products:
  description: Matching IOT products.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of products reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    request = models.GetProductsRequest()
    request.Offset = offset
    request.Length = limit
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.iot.v20180123 import models, iot_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-iot package is required.")

    client = iot_client.IotClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "iot.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, offset, limit),
        lambda request: sdk_call(module, client.GetProducts, request),
        lambda response: response.Products,
        lambda response: response.Total,
    )
    item_set, total_count = paginator.fetch_all()
    products = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, products=products,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
