#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: iotvideo_ai_model_application_info
short_description: Gather information about Tencent Cloud IOTVIDEO ai model applications
version_added: "0.8.0"
description: Returns IOTVIDEO ai model applications visible in a Tencent Cloud region.
options:
  model_id:
    description: AI model ID.
    type: str
    required: true
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List AI model applications
  tencentcloud.cloud.iotvideo_ai_model_application_info:
    region: ap-guangzhou
    model_id: body_detection
'''

RETURN = r'''
ai_model_applications:
  description: Matching IOTVIDEO ai model applications.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of ai model applications reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, model_id, offset, limit):
    request = models.DescribeAIModelApplicationsRequest()
    request.Offset = offset
    request.Limit = limit
    request.ModelId = model_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "model_id": {"type": "str", "required": True},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.iotvideo.v20211125 import models, iotvideo_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-iotvideo package is required.")

    client = iotvideo_client.IotvideoClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "iotvideo.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["model_id"], offset, limit),
        lambda request: sdk_call(module, client.DescribeAIModelApplications, request),
        lambda response: response.Applications,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    ai_model_applications = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, ai_model_applications=ai_model_applications, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
