#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: portal_document_info
short_description: Gather information about Tencent Cloud PORTAL documents
version_added: "0.9.0"
description: Returns PORTAL documents visible in a Tencent Cloud region.
options:
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all documents
  tencentcloud.cloud.portal_document_info:
    region: ap-guangzhou
'''

RETURN = r'''
documents:
  description: Matching PORTAL documents.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of documents reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    request = models.SearchDocumentsRequest()
    request.Page = offset // limit + 1
    request.PageSize = limit
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.portal.v20230413 import models, portal_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-portal package is required.")

    client = portal_client.PortalClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "portal.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, offset, limit),
        lambda request: sdk_call(module, client.SearchDocuments, request),
        lambda response: response.Documents,
        lambda response: response.Total,
    )
    item_set, total_count = paginator.fetch_all()
    documents = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, documents=documents, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
