#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: postgresql_backup_plan_info
short_description: Gather information about Tencent Cloud PostgreSQL backup plans
version_added: "1.2.0"
description: Returns the backup plans of a PostgreSQL instance.
options:
  db_instance_id:
    description: ID of the PostgreSQL instance whose backup plans are returned.
    type: str
    required: true
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List the backup plans of a PostgreSQL instance
  susunola.tencentcloud.postgresql_backup_plan_info:
    region: ap-guangzhou
    db_instance_id: "postgres-xxxxxxxx"

'''

RETURN = r'''
backup_plans:
  description: Backup plans of the instance.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of plans returned (the API reports no pageable total).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, db_instance_id, offset, limit):
    # DescribeBackupPlans returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeBackupPlansRequest()
    request.DBInstanceId = db_instance_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "db_instance_id": {"type": "str", "required": True},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.postgres.v20170312 import models, postgres_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-postgres package is required.")

    client = postgres_client.PostgresClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "postgres.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["db_instance_id"], 0, 0)
    response = sdk_call(module, client.DescribeBackupPlans, request)
    items = response.Plans or []
    backup_plans = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, backup_plans=backup_plans,
                     total_count=len(backup_plans), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
