#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: private_dns_record_info
short_description: Gather information about Tencent Cloud PRIVATEDNS private zone records
version_added: "1.5.0"
description: Returns PRIVATEDNS private zone records visible in a Tencent Cloud region.
options:
  zone_id:
    description: Sets the C(ZoneId) field of V(DescribePrivateZoneRecordList); omit it to leave that field unset.
    type: str
  filters:
    description: PRIVATEDNS API filter names mapped to lists of values.
    type: dict
    default: {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.private_dns_record
    description: Manage a Tencent Cloud Private DNS record.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all private zone records
  susunola.tencentcloud.private_dns_record_info:
    region: ap-guangzhou
'''

RETURN = r'''
private_zone_records:
  description: Matching PRIVATEDNS private zone records.
  returned: always
  type: list
  elements: dict
  sample:
    - RecordId: null
      ZoneId: null
      SubDomain: null
      RecordType: null
      RecordValue: null
      TTL: null
      MX: null
      Status: null
      Weight: null
      CreatedOn: null
      UpdatedOn: null
      Extra: null
      Enabled: null
      Remark: null
total_count:
  description: Number of private zone records reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, zone_id, filters, offset, limit):
    request = models.DescribePrivateZoneRecordListRequest()
    request.Offset = offset
    request.Limit = limit
    if zone_id is not None:
        request.ZoneId = zone_id
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "zone_id": {"type": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.privatedns.v20201028 import models, privatedns_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-privatedns package is required.")

    client = privatedns_client.PrivatednsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "privatedns.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["zone_id"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribePrivateZoneRecordList, request),
        lambda response: response.RecordSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    private_zone_records = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, private_zone_records=private_zone_records,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
