#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: pts_cron_job_info
short_description: Gather information about Tencent Cloud PTS cron jobs
version_added: "0.8.0"
description: Returns PTS cron jobs visible in a Tencent Cloud region.
options:
  cron_job_ids:
    description: Cron job IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all cron jobs
  susunola.tencentcloud.pts_cron_job_info:
    region: ap-guangzhou

- name: Find cron jobs by ID
  susunola.tencentcloud.pts_cron_job_info:
    region: ap-guangzhou
    cron_job_ids: [x-xxxxxxxx]
'''

RETURN = r'''
cron_jobs:
  description: Matching PTS cron jobs.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of cron jobs reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, cron_job_ids, offset, limit):
    request = models.DescribeCronJobsRequest()
    request.Offset = offset
    request.Limit = limit
    if cron_job_ids:
        request.CronJobIds = cron_job_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "cron_job_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.pts.v20210728 import models, pts_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-pts package is required.")

    client = pts_client.PtsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "pts.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["cron_job_ids"], offset, limit),
        lambda request: sdk_call(module, client.DescribeCronJobs, request),
        lambda response: response.CronJobSet,
        lambda response: response.Total,
    )
    item_set, total_count = paginator.fetch_all()
    cron_jobs = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, cron_jobs=cron_jobs,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
