#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: redis_instance_info
short_description: Gather information about TencentDB for Redis instances
version_added: "0.4.0"
description: Returns TencentDB for Redis instances visible in a Tencent Cloud region.
options:
  instance_ids:
    description: Instance IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.redis_instance
    description: Manage Tencent Cloud Redis instances.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all TencentDB for Redis instances
  susunola.tencentcloud.redis_instance_info:
    region: ap-guangzhou

- name: Find instances by ID
  susunola.tencentcloud.redis_instance_info:
    region: ap-guangzhou
    instance_ids: [crs-xxxxxxxx]
'''

RETURN = r'''
instances:
  description: Matching TencentDB for Redis instances.
  returned: always
  type: list
  elements: dict
  sample:
    - InstanceName: null
      InstanceId: null
      Appid: null
      ProjectId: null
      RegionId: null
      ZoneId: null
      VpcId: null
      SubnetId: null
      Status: null
      WanIp: null
      Port: null
      Createtime: null
      Size: null
      SizeUsed: null
      Type: null
      AutoRenewFlag: null
      DeadlineTime: null
      Engine: null
      ProductType: null
      UniqVpcId: null
      UniqSubnetId: null
      BillingMode: null
      InstanceTitle: null
      OfflineTime: null
      SubStatus: null
      Tags: null
      InstanceNode:
        - Id: null
          InstanceClusterNode:
            - Name: null
              RunId: null
              Role: null
              Status: null
              Connected: null
              CreateTime: null
              DownTime: null
              Slots: null
              Keys: null
              Qps: null
              QpsSlope: null
              Storage: null
              StorageSlope: null
      RedisShardSize: null
      RedisShardNum: null
      RedisReplicasNum: null
      PriceId: null
      CloseTime: null
      SlaveReadWeight: null
      InstanceTags:
        - TagKey: null
          TagValue: null
      ProjectName: null
      NoAuth: null
      ClientLimit: null
      DtsStatus: null
      NetLimit: null
      PasswordFree: null
      Vip6: null
      IPv6: null
      ReadOnly: null
      RemainBandwidthDuration: null
      DiskSize: null
      MonitorVersion: null
      ClientLimitMin: null
      ClientLimitMax: null
      NodeSet:
        - NodeType: null
          NodeId: null
          ZoneId: null
          ZoneName: null
      Region: null
      WanAddress: null
      PolarisServer: null
      RedisClusterId: null
      DedicatedClusterId: null
      ProductVersion: null
      CurrentProxyVersion: null
      CurrentRedisVersion: null
      UpgradeProxyVersion: null
      UpgradeRedisVersion: null
      BackupMode: null
      DeleteProtectionSwitch: null
total_count:
  description: Number of instances reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, instance_ids, offset, limit):
    request = models.DescribeInstancesRequest()
    request.Offset = offset
    request.Limit = limit
    if instance_ids:
        request.InstanceIds = instance_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "instance_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.redis.v20180412 import models, redis_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-redis package is required.")

    client = redis_client.RedisClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "redis.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["instance_ids"], offset, limit),
        lambda request: sdk_call(module, client.DescribeInstances, request),
        lambda response: response.InstanceSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    instances = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, instances=instances,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
