#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: scf_custom_domain_info
short_description: Gather information about Tencent Cloud SCF custom domains
version_added: "1.5.0"
description: Returns SCF custom domains visible in a Tencent Cloud region.
options:
  order_by:
    description: Order by. API field C(OrderBy).
    type: str
  order:
    description: Order. API field C(Order).
    type: str
  filters:
    description: SCF API filter names mapped to lists of values.
    type: dict
    default:
      {}
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - 'Can run in C(check_mode): the module reads the current state and
        predicts the result without issuing a write API call.'
    support: full
  idempotency:
    description:
      - 'Read-only: every run returns the current state and never changes
        the target, so a repeated run reports C(changed=false).'
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all custom domains
  susunola.tencentcloud.scf_custom_domain_info:
    region: ap-guangzhou
'''

RETURN = r'''
custom_domains:
  description: Matching SCF custom domains.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of custom domains reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, order_by, order, filters, offset, limit):
    request = models.ListCustomDomainsRequest()
    request.Offset = offset
    request.Limit = limit
    if order_by is not None:
        request.OrderBy = order_by
    if order is not None:
        request.Order = order
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "order_by": {"type": "str"},
        "order": {"type": "str"},
        "filters": {"type": "dict", "default": {}},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.scf.v20180416 import models, scf_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-scf package is required.")

    client = scf_client.ScfClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "scf.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["order_by"],
            module.params["order"],
            module.params["filters"],
            offset,
            limit),
        lambda request: sdk_call(module, client.ListCustomDomains, request),
        lambda response: response.Domains,
        lambda response: response.Total,
    )
    item_set, total_count = paginator.fetch_all()
    custom_domains = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, custom_domains=custom_domains,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
