#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: security_group_rule_info
short_description: Gather information about Tencent Cloud security group rules
version_added: "0.14.0"
description: Returns the ingress and egress rule set of a security group.
options:
  security_group_id:
    description: ID of the security group whose rules are returned.
    type: str
    required: true
  filters:
    description: VPC API filter names mapped to lists of values.
    type: dict
    default: {}
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List the rules of a security group
  susunola.tencentcloud.security_group_rule_info:
    region: ap-guangzhou
    security_group_id: sg-xxxxxxxx
'''

RETURN = r'''
policies:
  description: Security group policy set with Ingress and Egress rule lists.
  returned: always
  type: dict
request_id:
  description: Request ID of the API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, security_group_id, filters, offset, limit):
    # DescribeSecurityGroupPolicies takes no request arguments and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeSecurityGroupPoliciesRequest()
    request.SecurityGroupId = security_group_id
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "security_group_id": {"type": "str", "required": True},
        "filters": {"type": "dict", "default": {}},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.vpc.v20170312 import models, vpc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-vpc package is required.")

    client = vpc_client.VpcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "vpc.tencentcloudapi.com"),
    )
    request = build_request(
        models,
        module.params["security_group_id"],
        module.params["filters"],
        0,
        0)
    response = sdk_call(module, client.DescribeSecurityGroupPolicies, request)
    policies = serialize_sdk_object(response)
    policies.pop("RequestId", None)
    module.exit_json(changed=False, policies=policies,
                     request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
