#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: sms_signature_info
short_description: Gather information about Tencent Cloud SMS signatures
version_added: "1.1.0"
description: Returns SMS signatures of the account.
options:
  sign_ids:
    description: Signature IDs to return.
    type: list
    elements: int
  international:
    description: C(0) for mainland-China signatures, C(1) for international/HK/MO/TW signatures (required by the API).
    type: int
    required: true
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List mainland-China SMS signatures
  susunola.tencentcloud.sms_signature_info:
    region: ap-guangzhou
    international: 0
'''

RETURN = r'''
signatures:
  description: Matching SMS signatures.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of signatures returned (the API reports no total count).
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, sign_ids, international, offset, limit):
    request = models.DescribeSmsSignListRequest()
    request.Offset = offset
    request.Limit = limit
    if sign_ids is not None:
        request.SignIdSet = sign_ids
    request.International = international
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "sign_ids": {"type": "list", "elements": "int"},
        "international": {"type": "int", "required": True},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.sms.v20210111 import models, sms_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-sms package is required.")

    client = sms_client.SmsClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "sms.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["sign_ids"],
            module.params["international"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeSmsSignList, request),
        lambda response: response.DescribeSignListStatusSet,
        lambda response: None,
    )
    item_set, total_count = paginator.fetch_all()
    signatures = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, signatures=signatures,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
