#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: sslpod_domain_info
short_description: Gather information about Tencent Cloud SSLPOD domains
version_added: "0.8.0"
description: Returns SSLPOD domains visible in a Tencent Cloud region.
options:
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all domains
  tencentcloud.cloud.sslpod_domain_info:
    region: ap-guangzhou
'''

RETURN = r'''
domains:
  description: Matching SSLPOD domains.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of domains reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    request = models.DescribeDomainsRequest()
    request.Offset = offset
    request.Limit = limit
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.sslpod.v20190605 import models, sslpod_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-sslpod package is required.")

    client = sslpod_client.SslpodClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "sslpod.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, offset, limit),
        lambda request: sdk_call(module, client.DescribeDomains, request),
        lambda response: response.Data.Result if response.Data is not None else None,
        lambda response: response.Data.Total if response.Data is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    domains = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, domains=domains, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
