#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tbaas_block_info
short_description: Gather information about Tencent Cloud TBAAS blocks
version_added: "0.9.0"
description: Returns TBAAS blocks visible in a Tencent Cloud region.
options:
  module:
    description: Module name; the API requires the fixed value block.
    type: str
    default: block
  operation:
    description: Operation name; the API requires the fixed value block_list.
    type: str
    default: block_list
  channel_id:
    description: Channel ID; the API requires the fixed value 0.
    type: int
    default: 0
  group_id:
    description: Organization ID; the API requires the fixed value 0.
    type: int
    default: 0
  channel_name:
    description: Channel name to query.
    type: str
    required: true
  group_name:
    description: Organization name to query.
    type: str
    required: true
  cluster_id:
    description: Blockchain network ID.
    type: str
    required: true
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List blocks of a channel
  susunola.tencentcloud.tbaas_block_info:
    region: ap-guangzhou
    channel_name: my-channel
    group_name: my-group
    cluster_id: bcos-xxxxxxxx
'''

RETURN = r'''
blocks:
  description: Matching TBAAS blocks.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of blocks reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, module, operation, channel_id, group_id, channel_name, group_name, cluster_id, offset, limit):
    request = models.GetBlockListRequest()
    request.Offset = offset
    request.Limit = limit
    request.Module = module
    request.Operation = operation
    request.ChannelId = channel_id
    request.GroupId = group_id
    request.ChannelName = channel_name
    request.GroupName = group_name
    request.ClusterId = cluster_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "module": {"type": "str", "default": "block"},
        "operation": {"type": "str", "default": "block_list"},
        "channel_id": {"type": "int", "default": 0},
        "group_id": {"type": "int", "default": 0},
        "channel_name": {"type": "str", "required": True},
        "group_name": {"type": "str", "required": True},
        "cluster_id": {"type": "str", "required": True},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tbaas.v20180416 import models, tbaas_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tbaas package is required.")

    client = tbaas_client.TbaasClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tbaas.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["module"],
            module.params["operation"],
            module.params["channel_id"],
            module.params["group_id"],
            module.params["channel_name"],
            module.params["group_name"],
            module.params["cluster_id"],
            offset,
            limit),
        lambda request: sdk_call(module, client.GetBlockList, request),
        lambda response: response.BlockList,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    blocks = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, blocks=blocks, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
