#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tcr_immutable_tag_rule_info
short_description: Gather information about Tencent Cloud TCR immutable tag rules
version_added: "1.5.0"
description: Returns TCR immutable tag rules visible in a Tencent Cloud region.
options:
  registry_id:
    description: Sets the C(RegistryId) field of V(DescribeImmutableTagRules); omit it to leave that field unset.
    type: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.tcr_immutable_tag_rule
    description: Create or delete a Tencent Cloud TCR immutable tag rule.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all immutable tag rules
  susunola.tencentcloud.tcr_immutable_tag_rule_info:
    region: ap-guangzhou
'''

RETURN = r'''
immutable_tag_rules:
  description: Matching TCR immutable tag rules.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of immutable tag rules reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, registry_id, offset, limit):
    request = models.DescribeImmutableTagRulesRequest()
    request.Page = offset // limit + 1
    request.PageSize = limit
    if registry_id is not None:
        request.RegistryId = registry_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "registry_id": {"type": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tcr.v20190924 import models, tcr_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tcr package is required.")

    client = tcr_client.TcrClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tcr.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["registry_id"], offset, limit),
        lambda request: sdk_call(module, client.DescribeImmutableTagRules, request),
        lambda response: response.Rules,
        lambda response: response.Total,
    )
    item_set, total_count = paginator.fetch_all()
    immutable_tag_rules = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, immutable_tag_rules=immutable_tag_rules,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
