#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tdcpg_account_info
short_description: Gather information about Tencent Cloud TDCPG accounts
version_added: "1.5.0"
description: Returns TDCPG accounts visible in a Tencent Cloud region.
options:
  cluster_id:
    description: Cluster id. API field C(ClusterId).
    type: str
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - 'Can run in C(check_mode): the module reads the current state and
        predicts the result without issuing a write API call.'
    support: full
  idempotency:
    description:
      - 'Read-only: every run returns the current state and never changes
        the target, so a repeated run reports C(changed=false).'
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all accounts
  susunola.tencentcloud.tdcpg_account_info:
    region: ap-guangzhou
'''

RETURN = r'''
accounts:
  description: Matching TDCPG accounts.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of accounts reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, cluster_id, offset, limit):
    # DescribeAccounts returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeAccountsRequest()
    if cluster_id is not None:
        request.ClusterId = cluster_id
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "cluster_id": {"type": "str"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tdcpg.v20211118 import models, tdcpg_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tdcpg package is required.")

    client = tdcpg_client.TdcpgClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tdcpg.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["cluster_id"], 0, 0)
    response = sdk_call(module, client.DescribeAccounts, request)
    items = response.AccountSet or []
    accounts = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, accounts=accounts,
                     total_count=len(accounts), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
