#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tke_cluster_route_info
short_description: Gather information about Tencent Cloud TKE cluster routes
version_added: "1.5.0"
description: Returns TKE cluster routes visible in a Tencent Cloud region.
options:
  route_table_name:
    description: Route table name. API field C(RouteTableName).
    type: str
  filters:
    description: TKE API filter names mapped to lists of values.
    type: dict
    default:
      {}
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotent:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
seealso:
  - module: susunola.tencentcloud.tke_cluster_route
    description: Create or delete a route in a Tencent Cloud TKE cluster route table.
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all cluster routes
  susunola.tencentcloud.tke_cluster_route_info:
    region: ap-guangzhou
'''

RETURN = r'''
cluster_routes:
  description: Matching TKE cluster routes.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of cluster routes reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, route_table_name, filters, offset, limit):
    # DescribeClusterRoutes returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeClusterRoutesRequest()
    if route_table_name is not None:
        request.RouteTableName = route_table_name
    if filters:
        request.Filters = []
        for name, values in sorted(filters.items()):
            api_filter = models.Filter()
            api_filter.Name = name
            api_filter.Values = values if isinstance(values, list) else [values]
            request.Filters.append(api_filter)
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "route_table_name": {"type": "str"},
        "filters": {"type": "dict", "default": {}},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tke.v20180525 import models, tke_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tke package is required.")

    client = tke_client.TkeClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tke.tencentcloudapi.com"),
    )
    request = build_request(models, module.params["route_table_name"], module.params["filters"], 0, 0)
    response = sdk_call(module, client.DescribeClusterRoutes, request)
    items = response.RouteSet or []
    cluster_routes = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, cluster_routes=cluster_routes,
                     total_count=len(cluster_routes), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
