#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tke_cluster_route_table_info
short_description: Gather information about Tencent Cloud TKE cluster route tables
version_added: "1.5.0"
description: Returns TKE cluster route tables visible in a Tencent Cloud region.
options: {}
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotency:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all cluster route tables
  susunola.tencentcloud.tke_cluster_route_table_info:
    region: ap-guangzhou
'''

RETURN = r'''
cluster_route_tables:
  description: Matching TKE cluster route tables.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of cluster route tables reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, offset, limit):
    # DescribeClusterRouteTables returns the full list in one call and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeClusterRouteTablesRequest()
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({})
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tke.v20180525 import models, tke_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tke package is required.")

    client = tke_client.TkeClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tke.tencentcloudapi.com"),
    )
    request = build_request(models, 0, 0)
    response = sdk_call(module, client.DescribeClusterRouteTables, request)
    items = response.RouteTableSet or []
    cluster_route_tables = [serialize_sdk_object(item) for item in items]
    module.exit_json(changed=False, cluster_route_tables=cluster_route_tables,
                     total_count=len(cluster_route_tables), request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
