#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tke_cls_log_config_info
short_description: Gather information about Tencent Cloud TKE log config
version_added: "1.5.0"
description: Returns TKE log config visible in a Tencent Cloud region.
options:
  cluster_id:
    description: Cluster id. API field C(ClusterId).
    type: str
  cluster_type:
    description: Cluster type. API field C(ClusterType).
    type: str
  log_config_names:
    description: Log config names. API field C(LogConfigNames).
    type: str
extends_documentation_fragment:
  - susunola.tencentcloud.credentials
  - susunola.tencentcloud.region
  - susunola.tencentcloud.connection
  - susunola.tencentcloud.timeout
attributes:
  check_mode:
    description:
      - Can run in C(check_mode), reading the current state and predicting
        the result without issuing a write API call.
    support: full
  idempotency:
    description:
      - Read-only, so every run returns the current state and never changes
        the target, and a repeated run reports C(changed=false).
    support: full
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: Show the log config
  susunola.tencentcloud.tke_cls_log_config_info:
    region: ap-guangzhou
'''

RETURN = r'''
log_config:
  description: Matching TKE log config.
  returned: always
  type: dict
request_id:
  description: Request ID of the API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, cluster_id, cluster_type, log_config_names, offset, limit):
    # DescribeLogConfigs takes no request arguments and is not
    # paginated; offset and limit are accepted for signature uniformity.
    request = models.DescribeLogConfigsRequest()
    if cluster_id is not None:
        request.ClusterId = cluster_id
    if cluster_type is not None:
        request.ClusterType = cluster_type
    if log_config_names is not None:
        request.LogConfigNames = log_config_names
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "cluster_id": {"type": "str"},
        "cluster_type": {"type": "str"},
        "log_config_names": {"type": "str"},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tke.v20180525 import models, tke_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tke package is required.")

    client = tke_client.TkeClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tke.tencentcloudapi.com"),
    )
    request = build_request(
        models,
        module.params["cluster_id"],
        module.params["cluster_type"],
        module.params["log_config_names"],
        0,
        0)
    response = sdk_call(module, client.DescribeLogConfigs, request)
    log_config = serialize_sdk_object(response)
    log_config.pop("RequestId", None)
    module.exit_json(changed=False, log_config=log_config,
                     request_id=response.RequestId)


def main():
    run_module()


if __name__ == "__main__":
    main()
