#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: trtc_call_info
short_description: Gather information about Tencent Cloud TRTC calls
version_added: "0.8.0"
description: Returns TRTC calls visible in a Tencent Cloud region.
options:
  comm_id:
    description: Call ID in the form SdkAppId_RoomId_CreateTime, e.g. 1400xxxxxx_218695_1590065777 (required by the API).
    type: str
    required: true
  sdk_app_id:
    description: TRTC application ID.
    type: int
    required: true
  start_time:
    description: Start of the query window, a Unix timestamp in seconds.
    type: int
    required: true
  end_time:
    description: End of the query window, a Unix timestamp in seconds.
    type: int
    required: true
  call_ids:
    description: Call IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List call details
  susunola.tencentcloud.trtc_call_info:
    region: ap-guangzhou
    comm_id: 1400000000_218695_1590065777
    sdk_app_id: 1400000000
    start_time: 1700000000
    end_time: 1700003600
'''

RETURN = r'''
calls:
  description: Matching TRTC calls.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of calls reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, comm_id, sdk_app_id, start_time, end_time, call_ids, offset, limit):
    request = models.DescribeCallDetailInfoRequest()
    request.PageNumber = offset // limit
    request.PageSize = limit
    request.CommId = comm_id
    request.SdkAppId = sdk_app_id
    request.StartTime = start_time
    request.EndTime = end_time
    if call_ids:
        request.UserIds = call_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "comm_id": {"type": "str", "required": True},
        "sdk_app_id": {"type": "int", "required": True},
        "start_time": {"type": "int", "required": True},
        "end_time": {"type": "int", "required": True},
        "call_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.trtc.v20190722 import models, trtc_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-trtc package is required.")

    client = trtc_client.TrtcClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "trtc.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["comm_id"],
            module.params["sdk_app_id"],
            module.params["start_time"],
            module.params["end_time"],
            module.params["call_ids"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeCallDetailInfo, request),
        lambda response: response.UserList,
        lambda response: response.Total,
    )
    item_set, total_count = paginator.fetch_all()
    calls = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, calls=calls,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
