#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: tsf_application_info
short_description: Gather information about Tencent Cloud TSF applications
version_added: "0.8.0"
description: Returns TSF applications visible in a Tencent Cloud region.
options:
  application_ids:
    description: Application IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all applications
  tencentcloud.cloud.tsf_application_info:
    region: ap-guangzhou

- name: Find applications by ID
  tencentcloud.cloud.tsf_application_info:
    region: ap-guangzhou
    application_ids: [x-xxxxxxxx]
'''

RETURN = r'''
applications:
  description: Matching TSF applications.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of applications reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, application_ids, offset, limit):
    request = models.DescribeApplicationsRequest()
    request.Offset = offset
    request.Limit = limit
    if application_ids:
        request.ApplicationIdList = application_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "application_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.tsf.v20180326 import models, tsf_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-tsf package is required.")

    client = tsf_client.TsfClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "tsf.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["application_ids"], offset, limit),
        lambda request: sdk_call(module, client.DescribeApplications, request),
        lambda response: response.Result.Content if response.Result is not None else None,
        lambda response: response.Result.TotalCount if response.Result is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    applications = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, applications=applications, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
