#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: weilingwith_element_profile_page_info
short_description: Gather information about Tencent Cloud WEILINGWITH element profile pages
version_added: "0.8.0"
description: Returns WEILINGWITH element profile pages visible in a Tencent Cloud region.
options:
  element_profile_page_ids:
    description: Element profile page IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: susunola.tencentcloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List all element profile pages
  susunola.tencentcloud.weilingwith_element_profile_page_info:
    region: ap-guangzhou

- name: Find element profile pages by ID
  susunola.tencentcloud.weilingwith_element_profile_page_info:
    region: ap-guangzhou
    element_profile_page_ids: [x-xxxxxxxx]
'''

RETURN = r'''
element_profile_pages:
  description: Matching WEILINGWITH element profile pages.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of element profile pages reported by the API.
  returned: always
  type: int
request_id:
  description: Request ID of the last API call, for cross-referencing cloud audit logs.
  returned: always
  type: str
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.susunola.tencentcloud.plugins.module_utils.paging import Paginator
from ansible_collections.susunola.tencentcloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, element_profile_page_ids, offset, limit):
    request = models.DescribeElementProfilePageRequest()
    request.PageNumber = offset // limit + 1
    request.PageSize = limit
    if element_profile_page_ids:
        request.ParentElementIds = element_profile_page_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "element_profile_page_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.weilingwith.v20230427 import models, weilingwith_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-weilingwith package is required.")

    client = weilingwith_client.WeilingwithClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "weilingwith.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(models, module.params["element_profile_page_ids"], offset, limit),
        lambda request: sdk_call(module, client.DescribeElementProfilePage, request),
        lambda response: response.Result.List if response.Result is not None else None,
        lambda response: response.Result.TotalCount if response.Result is not None else None,
    )
    item_set, total_count = paginator.fetch_all()
    element_profile_pages = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, element_profile_pages=element_profile_pages,
                     total_count=total_count, request_id=paginator.request_id)


def main():
    run_module()


if __name__ == "__main__":
    main()
