#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by scripts/generate_info_modules.py -- regenerate instead of editing.
# Copyright: (c) 2026, Tencent Cloud Ansible Collection Contributors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r'''
---
module: yinsuda_ktv_robot_info
short_description: Gather information about Tencent Cloud YINSUDA ktv robots
version_added: "0.8.0"
description: Returns YINSUDA ktv robots visible in a Tencent Cloud region.
options:
  app_name:
    description: Application name.
    type: str
    required: true
  user_id:
    description: User identifier.
    type: str
    required: true
  ktv_robot_ids:
    description: Ktv robot IDs to return.
    type: list
    elements: str
  page_size:
    description: Number of results requested per API call.
    type: int
    default: 100
extends_documentation_fragment: tencentcloud.cloud.tencentcloud
author: Tencent Cloud Ansible Collection Contributors (@susunola)
'''

EXAMPLES = r'''
- name: List KTV robots of a user
  tencentcloud.cloud.yinsuda_ktv_robot_info:
    region: ap-guangzhou
    app_name: ktv
    user_id: "10001"
'''

RETURN = r'''
ktv_robots:
  description: Matching YINSUDA ktv robots.
  returned: always
  type: list
  elements: dict
total_count:
  description: Number of ktv robots reported by the API.
  returned: always
  type: int
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.tencentcloud.cloud.plugins.module_utils.paging import Paginator
from ansible_collections.tencentcloud.cloud.plugins.module_utils.tencentcloud import (
    create_client_profile, create_credential, sdk_call, serialize_sdk_object,
    tencentcloud_argument_spec,
)


def build_request(models, app_name, user_id, ktv_robot_ids, offset, limit):
    request = models.DescribeKTVRobotsRequest()
    request.Offset = offset
    request.Limit = limit
    request.AppName = app_name
    request.UserId = user_id
    if ktv_robot_ids:
        request.RobotIds = ktv_robot_ids
    return request


def run_module():
    argument_spec = tencentcloud_argument_spec()
    argument_spec.update({
        "app_name": {"type": "str", "required": True},
        "user_id": {"type": "str", "required": True},
        "ktv_robot_ids": {"type": "list", "elements": "str"},
        "page_size": {"type": "int", "default": 100},
    })
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    try:
        from tencentcloud.yinsuda.v20220527 import models, yinsuda_client
    except ImportError:
        module.fail_json(msg="The tencentcloud-sdk-python-yinsuda package is required.")

    client = yinsuda_client.YinsudaClient(
        create_credential(module), module.params["region"],
        create_client_profile(module, "yinsuda.tencentcloudapi.com"),
    )
    paginator = Paginator(
        module.params["page_size"],
        lambda offset, limit: build_request(
            models,
            module.params["app_name"],
            module.params["user_id"],
            module.params["ktv_robot_ids"],
            offset,
            limit),
        lambda request: sdk_call(module, client.DescribeKTVRobots, request),
        lambda response: response.KTVRobotInfoSet,
        lambda response: response.TotalCount,
    )
    item_set, total_count = paginator.fetch_all()
    ktv_robots = [serialize_sdk_object(item) for item in item_set]
    module.exit_json(changed=False, ktv_robots=ktv_robots, total_count=total_count)


def main():
    run_module()


if __name__ == "__main__":
    main()
